/*
 *
 * Copyright (C) 1992-2003 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -search_table (implies -row_status) -c Larus58k larus58kMib -agent -per_file_init 
 * 
 */

/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_LARUS58KPART_H
#define SR_LARUS58KPART_H


#ifdef __cplusplus
extern "C" {
#endif

/* only define name strings if we are not compiling LIGHT */
#ifndef LIGHT
#define STdeclare(name, value) static const char name [] = value;
#else	/* LIGHT */
#define STdeclare(name, value)
#endif	/* LIGHT */

/* define the OID components of the OID call table */

#if defined(N_larusMgmt)
#ifdef SNMPPART_DECL
const SR_UINT32 IDlarusMgmt[] = { 1, 3, 6, 1, 4, 1, 24628, 2 };
#else
extern const SR_UINT32 IDlarusMgmt[];
#endif	/* SNMPPART_DECL */
#define LNlarusMgmt 8
#endif	/* defined(N_larusMgmt) */


#if defined(N_larus58kMib)
#ifdef SNMPPART_DECL
const SR_UINT32 IDlarus58kMib[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2 };
#else
extern const SR_UINT32 IDlarus58kMib[];
#endif	/* SNMPPART_DECL */
#define LNlarus58kMib 9
#endif	/* defined(N_larus58kMib) */


#if defined(N_sts58kSystem)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kSystem[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1 };
#else
extern const SR_UINT32 IDsts58kSystem[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystem 10
#endif	/* defined(N_sts58kSystem) */


#if defined(I_sts58kSystemId)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemId, "sts58kSystemId")
const SR_UINT32 IDsts58kSystemId[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 1 };
#else
extern const SR_UINT32 IDsts58kSystemId[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemId 11
#endif	/* defined(I_sts58kSystemId) */


#if defined(I_sts58kSystemMgmtIpOption)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemMgmtIpOption, "sts58kSystemMgmtIpOption")
const SR_UINT32 IDsts58kSystemMgmtIpOption[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 2 };
#else
extern const SR_UINT32 IDsts58kSystemMgmtIpOption[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemMgmtIpOption 11
#endif	/* defined(I_sts58kSystemMgmtIpOption) */


#if defined(I_sts58kSystemMgmtIpAddress)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemMgmtIpAddress, "sts58kSystemMgmtIpAddress")
const SR_UINT32 IDsts58kSystemMgmtIpAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 3 };
#else
extern const SR_UINT32 IDsts58kSystemMgmtIpAddress[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemMgmtIpAddress 11
#endif	/* defined(I_sts58kSystemMgmtIpAddress) */


#if defined(I_sts58kSystemMgmtIpSubnetMask)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemMgmtIpSubnetMask, "sts58kSystemMgmtIpSubnetMask")
const SR_UINT32 IDsts58kSystemMgmtIpSubnetMask[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 4 };
#else
extern const SR_UINT32 IDsts58kSystemMgmtIpSubnetMask[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemMgmtIpSubnetMask 11
#endif	/* defined(I_sts58kSystemMgmtIpSubnetMask) */


#if defined(I_sts58kSystemMgmtIpGatewayAddress)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemMgmtIpGatewayAddress, "sts58kSystemMgmtIpGatewayAddress")
const SR_UINT32 IDsts58kSystemMgmtIpGatewayAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 5 };
#else
extern const SR_UINT32 IDsts58kSystemMgmtIpGatewayAddress[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemMgmtIpGatewayAddress 11
#endif	/* defined(I_sts58kSystemMgmtIpGatewayAddress) */


#if defined(I_sts58kSystemSntpIpOption)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemSntpIpOption, "sts58kSystemSntpIpOption")
const SR_UINT32 IDsts58kSystemSntpIpOption[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 6 };
#else
extern const SR_UINT32 IDsts58kSystemSntpIpOption[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemSntpIpOption 11
#endif	/* defined(I_sts58kSystemSntpIpOption) */


#if defined(I_sts58kSystemSntpIpAddress)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemSntpIpAddress, "sts58kSystemSntpIpAddress")
const SR_UINT32 IDsts58kSystemSntpIpAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 7 };
#else
extern const SR_UINT32 IDsts58kSystemSntpIpAddress[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemSntpIpAddress 11
#endif	/* defined(I_sts58kSystemSntpIpAddress) */


#if defined(I_sts58kSystemSntpIpSubnetMask)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemSntpIpSubnetMask, "sts58kSystemSntpIpSubnetMask")
const SR_UINT32 IDsts58kSystemSntpIpSubnetMask[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 8 };
#else
extern const SR_UINT32 IDsts58kSystemSntpIpSubnetMask[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemSntpIpSubnetMask 11
#endif	/* defined(I_sts58kSystemSntpIpSubnetMask) */


#if defined(I_sts58kSystemSntpIpGatewayAddress)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemSntpIpGatewayAddress, "sts58kSystemSntpIpGatewayAddress")
const SR_UINT32 IDsts58kSystemSntpIpGatewayAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 9 };
#else
extern const SR_UINT32 IDsts58kSystemSntpIpGatewayAddress[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemSntpIpGatewayAddress 11
#endif	/* defined(I_sts58kSystemSntpIpGatewayAddress) */


#if defined(I_sts58kSystemTime)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemTime, "sts58kSystemTime")
const SR_UINT32 IDsts58kSystemTime[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 10 };
#else
extern const SR_UINT32 IDsts58kSystemTime[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemTime 11
#endif	/* defined(I_sts58kSystemTime) */


#if defined(I_sts58kSystemTimeZone)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemTimeZone, "sts58kSystemTimeZone")
const SR_UINT32 IDsts58kSystemTimeZone[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 11 };
#else
extern const SR_UINT32 IDsts58kSystemTimeZone[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemTimeZone 11
#endif	/* defined(I_sts58kSystemTimeZone) */


#if defined(I_sts58kSystemIntegratedAlarm)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemIntegratedAlarm, "sts58kSystemIntegratedAlarm")
const SR_UINT32 IDsts58kSystemIntegratedAlarm[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 12 };
#else
extern const SR_UINT32 IDsts58kSystemIntegratedAlarm[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemIntegratedAlarm 11
#endif	/* defined(I_sts58kSystemIntegratedAlarm) */


#if defined(I_sts58kSystemAlarmAcoMode)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemAlarmAcoMode, "sts58kSystemAlarmAcoMode")
const SR_UINT32 IDsts58kSystemAlarmAcoMode[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 13 };
#else
extern const SR_UINT32 IDsts58kSystemAlarmAcoMode[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemAlarmAcoMode 11
#endif	/* defined(I_sts58kSystemAlarmAcoMode) */


#if defined(I_sts58kSystemAlarmAcoLed)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemAlarmAcoLed, "sts58kSystemAlarmAcoLed")
const SR_UINT32 IDsts58kSystemAlarmAcoLed[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 14 };
#else
extern const SR_UINT32 IDsts58kSystemAlarmAcoLed[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemAlarmAcoLed 11
#endif	/* defined(I_sts58kSystemAlarmAcoLed) */


#if defined(I_sts58kSystemAlarmAcoCutOff)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemAlarmAcoCutOff, "sts58kSystemAlarmAcoCutOff")
const SR_UINT32 IDsts58kSystemAlarmAcoCutOff[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 15 };
#else
extern const SR_UINT32 IDsts58kSystemAlarmAcoCutOff[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemAlarmAcoCutOff 11
#endif	/* defined(I_sts58kSystemAlarmAcoCutOff) */


#if defined(I_sts58kSystemAlarmEscalatingTime)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemAlarmEscalatingTime, "sts58kSystemAlarmEscalatingTime")
const SR_UINT32 IDsts58kSystemAlarmEscalatingTime[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 16 };
#else
extern const SR_UINT32 IDsts58kSystemAlarmEscalatingTime[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemAlarmEscalatingTime 11
#endif	/* defined(I_sts58kSystemAlarmEscalatingTime) */


#if defined(I_sts58kSystemMinorLED)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemMinorLED, "sts58kSystemMinorLED")
const SR_UINT32 IDsts58kSystemMinorLED[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 17 };
#else
extern const SR_UINT32 IDsts58kSystemMinorLED[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemMinorLED 11
#endif	/* defined(I_sts58kSystemMinorLED) */


#if defined(I_sts58kSystemMajorLED)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemMajorLED, "sts58kSystemMajorLED")
const SR_UINT32 IDsts58kSystemMajorLED[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 18 };
#else
extern const SR_UINT32 IDsts58kSystemMajorLED[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemMajorLED 11
#endif	/* defined(I_sts58kSystemMajorLED) */


#if defined(I_sts58kSystemCriticalLED)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemCriticalLED, "sts58kSystemCriticalLED")
const SR_UINT32 IDsts58kSystemCriticalLED[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 19 };
#else
extern const SR_UINT32 IDsts58kSystemCriticalLED[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemCriticalLED 11
#endif	/* defined(I_sts58kSystemCriticalLED) */


#if defined(I_sts58kSystemUpgradeSWAction)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemUpgradeSWAction, "sts58kSystemUpgradeSWAction")
const SR_UINT32 IDsts58kSystemUpgradeSWAction[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 20 };
#else
extern const SR_UINT32 IDsts58kSystemUpgradeSWAction[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemUpgradeSWAction 11
#endif	/* defined(I_sts58kSystemUpgradeSWAction) */


#if defined(I_sts58kSystemCurrentSWVersion)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemCurrentSWVersion, "sts58kSystemCurrentSWVersion")
const SR_UINT32 IDsts58kSystemCurrentSWVersion[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 21 };
#else
extern const SR_UINT32 IDsts58kSystemCurrentSWVersion[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemCurrentSWVersion 11
#endif	/* defined(I_sts58kSystemCurrentSWVersion) */


#if defined(I_sts58kSystemServiceState)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemServiceState, "sts58kSystemServiceState")
const SR_UINT32 IDsts58kSystemServiceState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 22 };
#else
extern const SR_UINT32 IDsts58kSystemServiceState[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemServiceState 11
#endif	/* defined(I_sts58kSystemServiceState) */


#if defined(I_sts58kSystemWarmReset)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemWarmReset, "sts58kSystemWarmReset")
const SR_UINT32 IDsts58kSystemWarmReset[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 23 };
#else
extern const SR_UINT32 IDsts58kSystemWarmReset[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemWarmReset 11
#endif	/* defined(I_sts58kSystemWarmReset) */


#if defined(I_sts58kSystemColdReset)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemColdReset, "sts58kSystemColdReset")
const SR_UINT32 IDsts58kSystemColdReset[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 24 };
#else
extern const SR_UINT32 IDsts58kSystemColdReset[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemColdReset 11
#endif	/* defined(I_sts58kSystemColdReset) */


#if defined(I_sts58kSystemConfigReset)
#ifdef SNMPPART_DECL
STdeclare(STsts58kSystemConfigReset, "sts58kSystemConfigReset")
const SR_UINT32 IDsts58kSystemConfigReset[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 25 };
#else
extern const SR_UINT32 IDsts58kSystemConfigReset[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemConfigReset 11
#endif	/* defined(I_sts58kSystemConfigReset) */


#if defined(N_sts58kClockInput)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kClockInput[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2 };
#else
extern const SR_UINT32 IDsts58kClockInput[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInput 10
#endif	/* defined(N_sts58kClockInput) */


#if defined(I_sts58kClockInputManualSelect)
#ifdef SNMPPART_DECL
STdeclare(STsts58kClockInputManualSelect, "sts58kClockInputManualSelect")
const SR_UINT32 IDsts58kClockInputManualSelect[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2, 1 };
#else
extern const SR_UINT32 IDsts58kClockInputManualSelect[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputManualSelect 11
#endif	/* defined(I_sts58kClockInputManualSelect) */


#if defined(I_sts58kClockInputOperMode)
#ifdef SNMPPART_DECL
STdeclare(STsts58kClockInputOperMode, "sts58kClockInputOperMode")
const SR_UINT32 IDsts58kClockInputOperMode[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2, 2 };
#else
extern const SR_UINT32 IDsts58kClockInputOperMode[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputOperMode 11
#endif	/* defined(I_sts58kClockInputOperMode) */


#if defined(I_sts58kClockInputProtectedPri)
#ifdef SNMPPART_DECL
STdeclare(STsts58kClockInputProtectedPri, "sts58kClockInputProtectedPri")
const SR_UINT32 IDsts58kClockInputProtectedPri[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2, 3 };
#else
extern const SR_UINT32 IDsts58kClockInputProtectedPri[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputProtectedPri 11
#endif	/* defined(I_sts58kClockInputProtectedPri) */


#if defined(I_sts58kClockInputSetSlip)
#ifdef SNMPPART_DECL
STdeclare(STsts58kClockInputSetSlip, "sts58kClockInputSetSlip")
const SR_UINT32 IDsts58kClockInputSetSlip[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2, 4 };
#else
extern const SR_UINT32 IDsts58kClockInputSetSlip[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputSetSlip 11
#endif	/* defined(I_sts58kClockInputSetSlip) */


#if defined(I_sts58kClockInputType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kClockInputType, "sts58kClockInputType")
const SR_UINT32 IDsts58kClockInputType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2, 5 };
#else
extern const SR_UINT32 IDsts58kClockInputType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputType 11
#endif	/* defined(I_sts58kClockInputType) */


#if defined(N_sts58kClockInputSSM)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kClockInputSSM[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 3 };
#else
extern const SR_UINT32 IDsts58kClockInputSSM[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputSSM 10
#endif	/* defined(N_sts58kClockInputSSM) */


#if defined(I_sts58kClockInputSSMSelect)
#ifdef SNMPPART_DECL
STdeclare(STsts58kClockInputSSMSelect, "sts58kClockInputSSMSelect")
const SR_UINT32 IDsts58kClockInputSSMSelect[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 3, 1 };
#else
extern const SR_UINT32 IDsts58kClockInputSSMSelect[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputSSMSelect 11
#endif	/* defined(I_sts58kClockInputSSMSelect) */


#if defined(N_sts58kTop)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kTop[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4 };
#else
extern const SR_UINT32 IDsts58kTop[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTop 10
#endif	/* defined(N_sts58kTop) */


#if defined(I_sts58kTopSourceIpOption)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopSourceIpOption, "sts58kTopSourceIpOption")
const SR_UINT32 IDsts58kTopSourceIpOption[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 1 };
#else
extern const SR_UINT32 IDsts58kTopSourceIpOption[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopSourceIpOption 11
#endif	/* defined(I_sts58kTopSourceIpOption) */


#if defined(I_sts58kTopSourceIpAddress)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopSourceIpAddress, "sts58kTopSourceIpAddress")
const SR_UINT32 IDsts58kTopSourceIpAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 2 };
#else
extern const SR_UINT32 IDsts58kTopSourceIpAddress[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopSourceIpAddress 11
#endif	/* defined(I_sts58kTopSourceIpAddress) */


#if defined(I_sts58kTopSourceIpSubnetMask)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopSourceIpSubnetMask, "sts58kTopSourceIpSubnetMask")
const SR_UINT32 IDsts58kTopSourceIpSubnetMask[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 3 };
#else
extern const SR_UINT32 IDsts58kTopSourceIpSubnetMask[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopSourceIpSubnetMask 11
#endif	/* defined(I_sts58kTopSourceIpSubnetMask) */


#if defined(I_sts58kTopSourceIpGatewayAddress)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopSourceIpGatewayAddress, "sts58kTopSourceIpGatewayAddress")
const SR_UINT32 IDsts58kTopSourceIpGatewayAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 4 };
#else
extern const SR_UINT32 IDsts58kTopSourceIpGatewayAddress[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopSourceIpGatewayAddress 11
#endif	/* defined(I_sts58kTopSourceIpGatewayAddress) */


#if defined(I_sts58kTopPacketRate)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopPacketRate, "sts58kTopPacketRate")
const SR_UINT32 IDsts58kTopPacketRate[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 5 };
#else
extern const SR_UINT32 IDsts58kTopPacketRate[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopPacketRate 11
#endif	/* defined(I_sts58kTopPacketRate) */


#if defined(I_sts58kTopInputSelect)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopInputSelect, "sts58kTopInputSelect")
const SR_UINT32 IDsts58kTopInputSelect[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 6 };
#else
extern const SR_UINT32 IDsts58kTopInputSelect[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopInputSelect 11
#endif	/* defined(I_sts58kTopInputSelect) */


#if defined(I_sts58kTopTxPackets)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopTxPackets, "sts58kTopTxPackets")
const SR_UINT32 IDsts58kTopTxPackets[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 7 };
#else
extern const SR_UINT32 IDsts58kTopTxPackets[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopTxPackets 11
#endif	/* defined(I_sts58kTopTxPackets) */


#if defined(I_sts58kTopTxBytes)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopTxBytes, "sts58kTopTxBytes")
const SR_UINT32 IDsts58kTopTxBytes[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 8 };
#else
extern const SR_UINT32 IDsts58kTopTxBytes[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopTxBytes 11
#endif	/* defined(I_sts58kTopTxBytes) */


#if defined(N_sts58kClockInputStatus)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kClockInputStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 5 };
#else
extern const SR_UINT32 IDsts58kClockInputStatus[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputStatus 10
#endif	/* defined(N_sts58kClockInputStatus) */




#if defined(I_sts58kClockInputStatusIndex)
#ifdef SNMPPART_DECL
STdeclare(STsts58kClockInputStatusIndex, "sts58kClockInputStatusIndex")
const SR_UINT32 IDsts58kClockInputStatusIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 5, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kClockInputStatusIndex[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputStatusIndex 13
#endif	/* defined(I_sts58kClockInputStatusIndex) */


#if defined(I_sts58kClockInputState)
#ifdef SNMPPART_DECL
STdeclare(STsts58kClockInputState, "sts58kClockInputState")
const SR_UINT32 IDsts58kClockInputState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 5, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kClockInputState[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputState 13
#endif	/* defined(I_sts58kClockInputState) */


#if defined(N_sts58kClockInputSSMStatus)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kClockInputSSMStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 6 };
#else
extern const SR_UINT32 IDsts58kClockInputSSMStatus[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputSSMStatus 10
#endif	/* defined(N_sts58kClockInputSSMStatus) */




#if defined(I_sts58kClockInputSSMIndex)
#ifdef SNMPPART_DECL
STdeclare(STsts58kClockInputSSMIndex, "sts58kClockInputSSMIndex")
const SR_UINT32 IDsts58kClockInputSSMIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 6, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kClockInputSSMIndex[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputSSMIndex 13
#endif	/* defined(I_sts58kClockInputSSMIndex) */


#if defined(I_sts58kClockInputSSMType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kClockInputSSMType, "sts58kClockInputSSMType")
const SR_UINT32 IDsts58kClockInputSSMType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 6, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kClockInputSSMType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputSSMType 13
#endif	/* defined(I_sts58kClockInputSSMType) */


#if defined(I_sts58kClockInputSSMValue)
#ifdef SNMPPART_DECL
STdeclare(STsts58kClockInputSSMValue, "sts58kClockInputSSMValue")
const SR_UINT32 IDsts58kClockInputSSMValue[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 6, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kClockInputSSMValue[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputSSMValue 13
#endif	/* defined(I_sts58kClockInputSSMValue) */


#if defined(N_sts58kCard)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kCard[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7 };
#else
extern const SR_UINT32 IDsts58kCard[];
#endif	/* SNMPPART_DECL */
#define LNsts58kCard 10
#endif	/* defined(N_sts58kCard) */




#if defined(I_sts58kCardShelf)
#ifdef SNMPPART_DECL
STdeclare(STsts58kCardShelf, "sts58kCardShelf")
const SR_UINT32 IDsts58kCardShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kCardShelf[];
#endif	/* SNMPPART_DECL */
#define LNsts58kCardShelf 13
#endif	/* defined(I_sts58kCardShelf) */


#if defined(I_sts58kCardIndex)
#ifdef SNMPPART_DECL
STdeclare(STsts58kCardIndex, "sts58kCardIndex")
const SR_UINT32 IDsts58kCardIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kCardIndex[];
#endif	/* SNMPPART_DECL */
#define LNsts58kCardIndex 13
#endif	/* defined(I_sts58kCardIndex) */


#if defined(I_sts58kCardType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kCardType, "sts58kCardType")
const SR_UINT32 IDsts58kCardType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kCardType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kCardType 13
#endif	/* defined(I_sts58kCardType) */


#if defined(I_sts58kCardDescr)
#ifdef SNMPPART_DECL
STdeclare(STsts58kCardDescr, "sts58kCardDescr")
const SR_UINT32 IDsts58kCardDescr[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kCardDescr[];
#endif	/* SNMPPART_DECL */
#define LNsts58kCardDescr 13
#endif	/* defined(I_sts58kCardDescr) */


#if defined(I_sts58kCardSerial)
#ifdef SNMPPART_DECL
STdeclare(STsts58kCardSerial, "sts58kCardSerial")
const SR_UINT32 IDsts58kCardSerial[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 5 };
#else
extern const SR_UINT32 IDsts58kCardSerial[];
#endif	/* SNMPPART_DECL */
#define LNsts58kCardSerial 13
#endif	/* defined(I_sts58kCardSerial) */


#if defined(I_sts58kCardHwVersion)
#ifdef SNMPPART_DECL
STdeclare(STsts58kCardHwVersion, "sts58kCardHwVersion")
const SR_UINT32 IDsts58kCardHwVersion[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 6 };
#else
extern const SR_UINT32 IDsts58kCardHwVersion[];
#endif	/* SNMPPART_DECL */
#define LNsts58kCardHwVersion 13
#endif	/* defined(I_sts58kCardHwVersion) */


#if defined(I_sts58kCardCLEICode)
#ifdef SNMPPART_DECL
STdeclare(STsts58kCardCLEICode, "sts58kCardCLEICode")
const SR_UINT32 IDsts58kCardCLEICode[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 7 };
#else
extern const SR_UINT32 IDsts58kCardCLEICode[];
#endif	/* SNMPPART_DECL */
#define LNsts58kCardCLEICode 13
#endif	/* defined(I_sts58kCardCLEICode) */


#if defined(I_sts58kCardOperStatus)
#ifdef SNMPPART_DECL
STdeclare(STsts58kCardOperStatus, "sts58kCardOperStatus")
const SR_UINT32 IDsts58kCardOperStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 8 };
#else
extern const SR_UINT32 IDsts58kCardOperStatus[];
#endif	/* SNMPPART_DECL */
#define LNsts58kCardOperStatus 13
#endif	/* defined(I_sts58kCardOperStatus) */


#if defined(I_sts58kCardReset)
#ifdef SNMPPART_DECL
STdeclare(STsts58kCardReset, "sts58kCardReset")
const SR_UINT32 IDsts58kCardReset[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 9 };
#else
extern const SR_UINT32 IDsts58kCardReset[];
#endif	/* SNMPPART_DECL */
#define LNsts58kCardReset 13
#endif	/* defined(I_sts58kCardReset) */


#if defined(N_sts58kOscillator)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOscillator[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8 };
#else
extern const SR_UINT32 IDsts58kOscillator[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillator 10
#endif	/* defined(N_sts58kOscillator) */




#if defined(I_sts58kOscillatorIndex)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorIndex, "sts58kOscillatorIndex")
const SR_UINT32 IDsts58kOscillatorIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kOscillatorIndex[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorIndex 13
#endif	/* defined(I_sts58kOscillatorIndex) */


#if defined(I_sts58kOscillatorModuleType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorModuleType, "sts58kOscillatorModuleType")
const SR_UINT32 IDsts58kOscillatorModuleType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kOscillatorModuleType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorModuleType 13
#endif	/* defined(I_sts58kOscillatorModuleType) */


#if defined(I_sts58kOscillatorEFER)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorEFER, "sts58kOscillatorEFER")
const SR_UINT32 IDsts58kOscillatorEFER[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kOscillatorEFER[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorEFER 13
#endif	/* defined(I_sts58kOscillatorEFER) */


#if defined(I_sts58kOscillatorESSD)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorESSD, "sts58kOscillatorESSD")
const SR_UINT32 IDsts58kOscillatorESSD[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kOscillatorESSD[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorESSD 13
#endif	/* defined(I_sts58kOscillatorESSD) */


#if defined(I_sts58kOscillatorESSN)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorESSN, "sts58kOscillatorESSN")
const SR_UINT32 IDsts58kOscillatorESSN[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 5 };
#else
extern const SR_UINT32 IDsts58kOscillatorESSN[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorESSN 13
#endif	/* defined(I_sts58kOscillatorESSN) */


#if defined(I_sts58kOscillatorFAGE)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorFAGE, "sts58kOscillatorFAGE")
const SR_UINT32 IDsts58kOscillatorFAGE[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 6 };
#else
extern const SR_UINT32 IDsts58kOscillatorFAGE[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorFAGE 13
#endif	/* defined(I_sts58kOscillatorFAGE) */


#if defined(I_sts58kOscillatorTIMD)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorTIMD, "sts58kOscillatorTIMD")
const SR_UINT32 IDsts58kOscillatorTIMD[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 7 };
#else
extern const SR_UINT32 IDsts58kOscillatorTIMD[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorTIMD 13
#endif	/* defined(I_sts58kOscillatorTIMD) */


#if defined(I_sts58kOscillatorSetActive)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorSetActive, "sts58kOscillatorSetActive")
const SR_UINT32 IDsts58kOscillatorSetActive[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 8 };
#else
extern const SR_UINT32 IDsts58kOscillatorSetActive[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorSetActive 13
#endif	/* defined(I_sts58kOscillatorSetActive) */


#if defined(I_sts58kOscillatorStatus)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorStatus, "sts58kOscillatorStatus")
const SR_UINT32 IDsts58kOscillatorStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 9 };
#else
extern const SR_UINT32 IDsts58kOscillatorStatus[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorStatus 13
#endif	/* defined(I_sts58kOscillatorStatus) */


#if defined(N_sts58kGPS)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kGPS[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9 };
#else
extern const SR_UINT32 IDsts58kGPS[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGPS 10
#endif	/* defined(N_sts58kGPS) */




#if defined(I_sts58kGpsIndex)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsIndex, "sts58kGpsIndex")
const SR_UINT32 IDsts58kGpsIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kGpsIndex[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsIndex 13
#endif	/* defined(I_sts58kGpsIndex) */


#if defined(I_sts58kGpsStatus)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsStatus, "sts58kGpsStatus")
const SR_UINT32 IDsts58kGpsStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kGpsStatus[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsStatus 13
#endif	/* defined(I_sts58kGpsStatus) */


#if defined(I_sts58kGpsANTD)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsANTD, "sts58kGpsANTD")
const SR_UINT32 IDsts58kGpsANTD[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kGpsANTD[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsANTD 13
#endif	/* defined(I_sts58kGpsANTD) */


#if defined(I_sts58kGpsAZEL)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsAZEL, "sts58kGpsAZEL")
const SR_UINT32 IDsts58kGpsAZEL[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kGpsAZEL[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsAZEL 13
#endif	/* defined(I_sts58kGpsAZEL) */


#if defined(I_sts58kGpsRSTG)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsRSTG, "sts58kGpsRSTG")
const SR_UINT32 IDsts58kGpsRSTG[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 5 };
#else
extern const SR_UINT32 IDsts58kGpsRSTG[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsRSTG 13
#endif	/* defined(I_sts58kGpsRSTG) */


#if defined(I_sts58kGpsBITS)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsBITS, "sts58kGpsBITS")
const SR_UINT32 IDsts58kGpsBITS[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 6 };
#else
extern const SR_UINT32 IDsts58kGpsBITS[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsBITS 13
#endif	/* defined(I_sts58kGpsBITS) */


#if defined(I_sts58kGpsPAVG)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsPAVG, "sts58kGpsPAVG")
const SR_UINT32 IDsts58kGpsPAVG[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 7 };
#else
extern const SR_UINT32 IDsts58kGpsPAVG[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsPAVG 13
#endif	/* defined(I_sts58kGpsPAVG) */


#if defined(I_sts58kGpsSIGQ)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsSIGQ, "sts58kGpsSIGQ")
const SR_UINT32 IDsts58kGpsSIGQ[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 8 };
#else
extern const SR_UINT32 IDsts58kGpsSIGQ[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsSIGQ 13
#endif	/* defined(I_sts58kGpsSIGQ) */


#if defined(I_sts58kGpsSPOS)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsSPOS, "sts58kGpsSPOS")
const SR_UINT32 IDsts58kGpsSPOS[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 9 };
#else
extern const SR_UINT32 IDsts58kGpsSPOS[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsSPOS 13
#endif	/* defined(I_sts58kGpsSPOS) */


#if defined(I_sts58kGpsTRMO)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsTRMO, "sts58kGpsTRMO")
const SR_UINT32 IDsts58kGpsTRMO[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 10 };
#else
extern const SR_UINT32 IDsts58kGpsTRMO[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsTRMO 13
#endif	/* defined(I_sts58kGpsTRMO) */


#if defined(I_sts58kGpsUTCT)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsUTCT, "sts58kGpsUTCT")
const SR_UINT32 IDsts58kGpsUTCT[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 11 };
#else
extern const SR_UINT32 IDsts58kGpsUTCT[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsUTCT 13
#endif	/* defined(I_sts58kGpsUTCT) */


#if defined(I_sts58kGpsVERS)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsVERS, "sts58kGpsVERS")
const SR_UINT32 IDsts58kGpsVERS[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 12 };
#else
extern const SR_UINT32 IDsts58kGpsVERS[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsVERS 13
#endif	/* defined(I_sts58kGpsVERS) */


#if defined(I_sts58kGpsDETF)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsDETF, "sts58kGpsDETF")
const SR_UINT32 IDsts58kGpsDETF[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 13 };
#else
extern const SR_UINT32 IDsts58kGpsDETF[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsDETF 13
#endif	/* defined(I_sts58kGpsDETF) */


#if defined(I_sts58kGpsEFER)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsEFER, "sts58kGpsEFER")
const SR_UINT32 IDsts58kGpsEFER[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 14 };
#else
extern const SR_UINT32 IDsts58kGpsEFER[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsEFER 13
#endif	/* defined(I_sts58kGpsEFER) */


#if defined(I_sts58kGpsESSD)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsESSD, "sts58kGpsESSD")
const SR_UINT32 IDsts58kGpsESSD[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 15 };
#else
extern const SR_UINT32 IDsts58kGpsESSD[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsESSD 13
#endif	/* defined(I_sts58kGpsESSD) */


#if defined(I_sts58kGpsESSN)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsESSN, "sts58kGpsESSN")
const SR_UINT32 IDsts58kGpsESSN[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 16 };
#else
extern const SR_UINT32 IDsts58kGpsESSN[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsESSN 13
#endif	/* defined(I_sts58kGpsESSN) */


#if defined(I_sts58kGpsFAGE)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsFAGE, "sts58kGpsFAGE")
const SR_UINT32 IDsts58kGpsFAGE[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 17 };
#else
extern const SR_UINT32 IDsts58kGpsFAGE[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsFAGE 13
#endif	/* defined(I_sts58kGpsFAGE) */


#if defined(I_sts58kGpsTIMD)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsTIMD, "sts58kGpsTIMD")
const SR_UINT32 IDsts58kGpsTIMD[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 18 };
#else
extern const SR_UINT32 IDsts58kGpsTIMD[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsTIMD 13
#endif	/* defined(I_sts58kGpsTIMD) */


#if defined(I_sts58kGpsReset)
#ifdef SNMPPART_DECL
STdeclare(STsts58kGpsReset, "sts58kGpsReset")
const SR_UINT32 IDsts58kGpsReset[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 19 };
#else
extern const SR_UINT32 IDsts58kGpsReset[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsReset 13
#endif	/* defined(I_sts58kGpsReset) */


#if defined(N_sts58kLink)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kLink[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10 };
#else
extern const SR_UINT32 IDsts58kLink[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLink 10
#endif	/* defined(N_sts58kLink) */




#if defined(I_sts58kLinkIndex)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkIndex, "sts58kLinkIndex")
const SR_UINT32 IDsts58kLinkIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kLinkIndex[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkIndex 13
#endif	/* defined(I_sts58kLinkIndex) */


#if defined(I_sts58kLinkType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkType, "sts58kLinkType")
const SR_UINT32 IDsts58kLinkType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kLinkType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkType 13
#endif	/* defined(I_sts58kLinkType) */


#if defined(I_sts58kLinkEnable)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkEnable, "sts58kLinkEnable")
const SR_UINT32 IDsts58kLinkEnable[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kLinkEnable[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkEnable 13
#endif	/* defined(I_sts58kLinkEnable) */


#if defined(I_sts58kLinkLineCode)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkLineCode, "sts58kLinkLineCode")
const SR_UINT32 IDsts58kLinkLineCode[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kLinkLineCode[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkLineCode 13
#endif	/* defined(I_sts58kLinkLineCode) */


#if defined(I_sts58kLinkFMT)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkFMT, "sts58kLinkFMT")
const SR_UINT32 IDsts58kLinkFMT[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 5 };
#else
extern const SR_UINT32 IDsts58kLinkFMT[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkFMT 13
#endif	/* defined(I_sts58kLinkFMT) */


#if defined(I_sts58kLinkTermination)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkTermination, "sts58kLinkTermination")
const SR_UINT32 IDsts58kLinkTermination[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 6 };
#else
extern const SR_UINT32 IDsts58kLinkTermination[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkTermination 13
#endif	/* defined(I_sts58kLinkTermination) */


#if defined(I_sts58kLinkMFCHK)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkMFCHK, "sts58kLinkMFCHK")
const SR_UINT32 IDsts58kLinkMFCHK[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 7 };
#else
extern const SR_UINT32 IDsts58kLinkMFCHK[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkMFCHK 13
#endif	/* defined(I_sts58kLinkMFCHK) */


#if defined(I_sts58kLinkId)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkId, "sts58kLinkId")
const SR_UINT32 IDsts58kLinkId[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 8 };
#else
extern const SR_UINT32 IDsts58kLinkId[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkId 13
#endif	/* defined(I_sts58kLinkId) */


#if defined(N_sts58kShelf)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11 };
#else
extern const SR_UINT32 IDsts58kShelf[];
#endif	/* SNMPPART_DECL */
#define LNsts58kShelf 10
#endif	/* defined(N_sts58kShelf) */




#if defined(I_sts58kShelfIndex)
#ifdef SNMPPART_DECL
STdeclare(STsts58kShelfIndex, "sts58kShelfIndex")
const SR_UINT32 IDsts58kShelfIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kShelfIndex[];
#endif	/* SNMPPART_DECL */
#define LNsts58kShelfIndex 13
#endif	/* defined(I_sts58kShelfIndex) */


#if defined(I_sts58kShelfSerial)
#ifdef SNMPPART_DECL
STdeclare(STsts58kShelfSerial, "sts58kShelfSerial")
const SR_UINT32 IDsts58kShelfSerial[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kShelfSerial[];
#endif	/* SNMPPART_DECL */
#define LNsts58kShelfSerial 13
#endif	/* defined(I_sts58kShelfSerial) */


#if defined(I_sts58kShelfCLEICode)
#ifdef SNMPPART_DECL
STdeclare(STsts58kShelfCLEICode, "sts58kShelfCLEICode")
const SR_UINT32 IDsts58kShelfCLEICode[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kShelfCLEICode[];
#endif	/* SNMPPART_DECL */
#define LNsts58kShelfCLEICode 13
#endif	/* defined(I_sts58kShelfCLEICode) */


#if defined(I_sts58kShelfReset)
#ifdef SNMPPART_DECL
STdeclare(STsts58kShelfReset, "sts58kShelfReset")
const SR_UINT32 IDsts58kShelfReset[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kShelfReset[];
#endif	/* SNMPPART_DECL */
#define LNsts58kShelfReset 13
#endif	/* defined(I_sts58kShelfReset) */


#if defined(N_sts58kAlarmThreshold)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kAlarmThreshold[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 12 };
#else
extern const SR_UINT32 IDsts58kAlarmThreshold[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmThreshold 10
#endif	/* defined(N_sts58kAlarmThreshold) */




#if defined(I_sts58kAlarmThresholdCurrentMon)
#ifdef SNMPPART_DECL
STdeclare(STsts58kAlarmThresholdCurrentMon, "sts58kAlarmThresholdCurrentMon")
const SR_UINT32 IDsts58kAlarmThresholdCurrentMon[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 12, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kAlarmThresholdCurrentMon[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmThresholdCurrentMon 13
#endif	/* defined(I_sts58kAlarmThresholdCurrentMon) */


#if defined(I_sts58kAlarmThresholdType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kAlarmThresholdType, "sts58kAlarmThresholdType")
const SR_UINT32 IDsts58kAlarmThresholdType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 12, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kAlarmThresholdType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmThresholdType 13
#endif	/* defined(I_sts58kAlarmThresholdType) */


#if defined(I_sts58kAlarmThresholdValue)
#ifdef SNMPPART_DECL
STdeclare(STsts58kAlarmThresholdValue, "sts58kAlarmThresholdValue")
const SR_UINT32 IDsts58kAlarmThresholdValue[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 12, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kAlarmThresholdValue[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmThresholdValue 13
#endif	/* defined(I_sts58kAlarmThresholdValue) */


#if defined(I_sts58kAlarmThresholdTimeInterval)
#ifdef SNMPPART_DECL
STdeclare(STsts58kAlarmThresholdTimeInterval, "sts58kAlarmThresholdTimeInterval")
const SR_UINT32 IDsts58kAlarmThresholdTimeInterval[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 12, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kAlarmThresholdTimeInterval[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmThresholdTimeInterval 13
#endif	/* defined(I_sts58kAlarmThresholdTimeInterval) */


#if defined(N_sts58kLinkAlarmSetting)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kLinkAlarmSetting[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 13 };
#else
extern const SR_UINT32 IDsts58kLinkAlarmSetting[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkAlarmSetting 10
#endif	/* defined(N_sts58kLinkAlarmSetting) */




#if defined(I_sts58kLinkAlarmSettingLinkType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkAlarmSettingLinkType, "sts58kLinkAlarmSettingLinkType")
const SR_UINT32 IDsts58kLinkAlarmSettingLinkType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 13, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kLinkAlarmSettingLinkType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkAlarmSettingLinkType 13
#endif	/* defined(I_sts58kLinkAlarmSettingLinkType) */


#if defined(I_sts58kLinkAlarmSettingType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkAlarmSettingType, "sts58kLinkAlarmSettingType")
const SR_UINT32 IDsts58kLinkAlarmSettingType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 13, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kLinkAlarmSettingType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkAlarmSettingType 13
#endif	/* defined(I_sts58kLinkAlarmSettingType) */


#if defined(I_sts58kLinkAlarmSettingSevirity)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkAlarmSettingSevirity, "sts58kLinkAlarmSettingSevirity")
const SR_UINT32 IDsts58kLinkAlarmSettingSevirity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 13, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kLinkAlarmSettingSevirity[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkAlarmSettingSevirity 13
#endif	/* defined(I_sts58kLinkAlarmSettingSevirity) */


#if defined(I_sts58kLinkAlarmSevirity)
#ifdef SNMPPART_DECL
STdeclare(STsts58kLinkAlarmSevirity, "sts58kLinkAlarmSevirity")
const SR_UINT32 IDsts58kLinkAlarmSevirity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 13, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kLinkAlarmSevirity[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkAlarmSevirity 13
#endif	/* defined(I_sts58kLinkAlarmSevirity) */


#if defined(N_sts58kOscillatorAlarmSetting)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOscillatorAlarmSetting[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 14 };
#else
extern const SR_UINT32 IDsts58kOscillatorAlarmSetting[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorAlarmSetting 10
#endif	/* defined(N_sts58kOscillatorAlarmSetting) */




#if defined(I_sts58kOscillatorAlarmSettingClock)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorAlarmSettingClock, "sts58kOscillatorAlarmSettingClock")
const SR_UINT32 IDsts58kOscillatorAlarmSettingClock[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 14, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kOscillatorAlarmSettingClock[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorAlarmSettingClock 13
#endif	/* defined(I_sts58kOscillatorAlarmSettingClock) */


#if defined(I_sts58kOscillatorAlarmSettingType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorAlarmSettingType, "sts58kOscillatorAlarmSettingType")
const SR_UINT32 IDsts58kOscillatorAlarmSettingType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 14, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kOscillatorAlarmSettingType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorAlarmSettingType 13
#endif	/* defined(I_sts58kOscillatorAlarmSettingType) */


#if defined(I_sts58kOscillatorAlarmSettingSeverity)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorAlarmSettingSeverity, "sts58kOscillatorAlarmSettingSeverity")
const SR_UINT32 IDsts58kOscillatorAlarmSettingSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 14, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kOscillatorAlarmSettingSeverity[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorAlarmSettingSeverity 13
#endif	/* defined(I_sts58kOscillatorAlarmSettingSeverity) */


#if defined(I_sts58kOscillatorAlarmSeverity)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOscillatorAlarmSeverity, "sts58kOscillatorAlarmSeverity")
const SR_UINT32 IDsts58kOscillatorAlarmSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 14, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kOscillatorAlarmSeverity[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorAlarmSeverity 13
#endif	/* defined(I_sts58kOscillatorAlarmSeverity) */


#if defined(N_sts58kOsPwrAlarmSetting)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOsPwrAlarmSetting[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 15 };
#else
extern const SR_UINT32 IDsts58kOsPwrAlarmSetting[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOsPwrAlarmSetting 10
#endif	/* defined(N_sts58kOsPwrAlarmSetting) */




#if defined(I_sts58ksPwrAlarmSettingShelf)
#ifdef SNMPPART_DECL
STdeclare(STsts58ksPwrAlarmSettingShelf, "sts58ksPwrAlarmSettingShelf")
const SR_UINT32 IDsts58ksPwrAlarmSettingShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 15, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58ksPwrAlarmSettingShelf[];
#endif	/* SNMPPART_DECL */
#define LNsts58ksPwrAlarmSettingShelf 13
#endif	/* defined(I_sts58ksPwrAlarmSettingShelf) */


#if defined(I_sts58kOsPwrAlarmSettingOsPwr)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOsPwrAlarmSettingOsPwr, "sts58kOsPwrAlarmSettingOsPwr")
const SR_UINT32 IDsts58kOsPwrAlarmSettingOsPwr[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 15, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kOsPwrAlarmSettingOsPwr[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOsPwrAlarmSettingOsPwr 13
#endif	/* defined(I_sts58kOsPwrAlarmSettingOsPwr) */


#if defined(I_sts58kOsPwrAlarmSettingSeverity)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOsPwrAlarmSettingSeverity, "sts58kOsPwrAlarmSettingSeverity")
const SR_UINT32 IDsts58kOsPwrAlarmSettingSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 15, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kOsPwrAlarmSettingSeverity[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOsPwrAlarmSettingSeverity 13
#endif	/* defined(I_sts58kOsPwrAlarmSettingSeverity) */


#if defined(I_sts58kOsPwrAlarmSeverity)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOsPwrAlarmSeverity, "sts58kOsPwrAlarmSeverity")
const SR_UINT32 IDsts58kOsPwrAlarmSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 15, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kOsPwrAlarmSeverity[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOsPwrAlarmSeverity 13
#endif	/* defined(I_sts58kOsPwrAlarmSeverity) */


#if defined(N_sts58kOutputAlarmSetting)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOutputAlarmSetting[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16 };
#else
extern const SR_UINT32 IDsts58kOutputAlarmSetting[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputAlarmSetting 10
#endif	/* defined(N_sts58kOutputAlarmSetting) */




#if defined(I_sts58kOutputAlarmSettingShelf)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputAlarmSettingShelf, "sts58kOutputAlarmSettingShelf")
const SR_UINT32 IDsts58kOutputAlarmSettingShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kOutputAlarmSettingShelf[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputAlarmSettingShelf 13
#endif	/* defined(I_sts58kOutputAlarmSettingShelf) */


#if defined(I_sts58kOutputAlarmSettingSlot)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputAlarmSettingSlot, "sts58kOutputAlarmSettingSlot")
const SR_UINT32 IDsts58kOutputAlarmSettingSlot[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kOutputAlarmSettingSlot[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputAlarmSettingSlot 13
#endif	/* defined(I_sts58kOutputAlarmSettingSlot) */


#if defined(I_sts58kOutputAlarmSettingPort)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputAlarmSettingPort, "sts58kOutputAlarmSettingPort")
const SR_UINT32 IDsts58kOutputAlarmSettingPort[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kOutputAlarmSettingPort[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputAlarmSettingPort 13
#endif	/* defined(I_sts58kOutputAlarmSettingPort) */


#if defined(I_sts58kOutputAlarmSettingType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputAlarmSettingType, "sts58kOutputAlarmSettingType")
const SR_UINT32 IDsts58kOutputAlarmSettingType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kOutputAlarmSettingType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputAlarmSettingType 13
#endif	/* defined(I_sts58kOutputAlarmSettingType) */


#if defined(I_sts58kOutputAlarmSettingSeverity)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputAlarmSettingSeverity, "sts58kOutputAlarmSettingSeverity")
const SR_UINT32 IDsts58kOutputAlarmSettingSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16, 1, 1, 5 };
#else
extern const SR_UINT32 IDsts58kOutputAlarmSettingSeverity[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputAlarmSettingSeverity 13
#endif	/* defined(I_sts58kOutputAlarmSettingSeverity) */


#if defined(I_sts58kOutputAlarmSeverity)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputAlarmSeverity, "sts58kOutputAlarmSeverity")
const SR_UINT32 IDsts58kOutputAlarmSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16, 1, 1, 6 };
#else
extern const SR_UINT32 IDsts58kOutputAlarmSeverity[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputAlarmSeverity 13
#endif	/* defined(I_sts58kOutputAlarmSeverity) */


#if defined(N_sts58kOutputTiuSetting)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOutputTiuSetting[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17 };
#else
extern const SR_UINT32 IDsts58kOutputTiuSetting[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputTiuSetting 10
#endif	/* defined(N_sts58kOutputTiuSetting) */




#if defined(I_sts58kOutputTiuSettingShelf)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputTiuSettingShelf, "sts58kOutputTiuSettingShelf")
const SR_UINT32 IDsts58kOutputTiuSettingShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kOutputTiuSettingShelf[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputTiuSettingShelf 13
#endif	/* defined(I_sts58kOutputTiuSettingShelf) */


#if defined(I_sts58kOutputTiuSettingSlot)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputTiuSettingSlot, "sts58kOutputTiuSettingSlot")
const SR_UINT32 IDsts58kOutputTiuSettingSlot[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kOutputTiuSettingSlot[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputTiuSettingSlot 13
#endif	/* defined(I_sts58kOutputTiuSettingSlot) */


#if defined(I_sts58kOutputTiuSettingPort)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputTiuSettingPort, "sts58kOutputTiuSettingPort")
const SR_UINT32 IDsts58kOutputTiuSettingPort[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kOutputTiuSettingPort[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputTiuSettingPort 13
#endif	/* defined(I_sts58kOutputTiuSettingPort) */


#if defined(I_sts58kOutputTiuSettingLineCoding)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputTiuSettingLineCoding, "sts58kOutputTiuSettingLineCoding")
const SR_UINT32 IDsts58kOutputTiuSettingLineCoding[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kOutputTiuSettingLineCoding[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputTiuSettingLineCoding 13
#endif	/* defined(I_sts58kOutputTiuSettingLineCoding) */


#if defined(I_sts58kOutputTiuSettingFMT)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputTiuSettingFMT, "sts58kOutputTiuSettingFMT")
const SR_UINT32 IDsts58kOutputTiuSettingFMT[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 5 };
#else
extern const SR_UINT32 IDsts58kOutputTiuSettingFMT[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputTiuSettingFMT 13
#endif	/* defined(I_sts58kOutputTiuSettingFMT) */


#if defined(I_sts58kOutputTiuSettingTermination)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputTiuSettingTermination, "sts58kOutputTiuSettingTermination")
const SR_UINT32 IDsts58kOutputTiuSettingTermination[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 6 };
#else
extern const SR_UINT32 IDsts58kOutputTiuSettingTermination[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputTiuSettingTermination 13
#endif	/* defined(I_sts58kOutputTiuSettingTermination) */


#if defined(N_sts58kPerfMon)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kPerfMon[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18 };
#else
extern const SR_UINT32 IDsts58kPerfMon[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMon 10
#endif	/* defined(N_sts58kPerfMon) */




#if defined(I_sts58kPerfMonInputCurrentMon)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonInputCurrentMon, "sts58kPerfMonInputCurrentMon")
const SR_UINT32 IDsts58kPerfMonInputCurrentMon[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kPerfMonInputCurrentMon[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonInputCurrentMon 13
#endif	/* defined(I_sts58kPerfMonInputCurrentMon) */


#if defined(I_sts58kPerfMonInputMonPeriod)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonInputMonPeriod, "sts58kPerfMonInputMonPeriod")
const SR_UINT32 IDsts58kPerfMonInputMonPeriod[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kPerfMonInputMonPeriod[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonInputMonPeriod 13
#endif	/* defined(I_sts58kPerfMonInputMonPeriod) */


#if defined(I_sts58kPerfMonInputMonBucket)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonInputMonBucket, "sts58kPerfMonInputMonBucket")
const SR_UINT32 IDsts58kPerfMonInputMonBucket[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kPerfMonInputMonBucket[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonInputMonBucket 13
#endif	/* defined(I_sts58kPerfMonInputMonBucket) */


#if defined(I_sts58kPerfMonInputClockType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonInputClockType, "sts58kPerfMonInputClockType")
const SR_UINT32 IDsts58kPerfMonInputClockType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kPerfMonInputClockType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonInputClockType 13
#endif	/* defined(I_sts58kPerfMonInputClockType) */


#if defined(I_sts58kPerfMonPerfCVL)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonPerfCVL, "sts58kPerfMonPerfCVL")
const SR_UINT32 IDsts58kPerfMonPerfCVL[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 5 };
#else
extern const SR_UINT32 IDsts58kPerfMonPerfCVL[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonPerfCVL 13
#endif	/* defined(I_sts58kPerfMonPerfCVL) */


#if defined(I_sts58kPerfMonPerfCVP)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonPerfCVP, "sts58kPerfMonPerfCVP")
const SR_UINT32 IDsts58kPerfMonPerfCVP[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 6 };
#else
extern const SR_UINT32 IDsts58kPerfMonPerfCVP[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonPerfCVP 13
#endif	/* defined(I_sts58kPerfMonPerfCVP) */


#if defined(I_sts58kPerfMonPerfCS)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonPerfCS, "sts58kPerfMonPerfCS")
const SR_UINT32 IDsts58kPerfMonPerfCS[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 7 };
#else
extern const SR_UINT32 IDsts58kPerfMonPerfCS[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonPerfCS 13
#endif	/* defined(I_sts58kPerfMonPerfCS) */


#if defined(I_sts58kPerfMonPerfESP)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonPerfESP, "sts58kPerfMonPerfESP")
const SR_UINT32 IDsts58kPerfMonPerfESP[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 8 };
#else
extern const SR_UINT32 IDsts58kPerfMonPerfESP[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonPerfESP 13
#endif	/* defined(I_sts58kPerfMonPerfESP) */


#if defined(I_sts58kPerfMonPerfJitter)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonPerfJitter, "sts58kPerfMonPerfJitter")
const SR_UINT32 IDsts58kPerfMonPerfJitter[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 9 };
#else
extern const SR_UINT32 IDsts58kPerfMonPerfJitter[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonPerfJitter 13
#endif	/* defined(I_sts58kPerfMonPerfJitter) */


#if defined(I_sts58kPerfMonPerfPhaseData)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonPerfPhaseData, "sts58kPerfMonPerfPhaseData")
const SR_UINT32 IDsts58kPerfMonPerfPhaseData[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 10 };
#else
extern const SR_UINT32 IDsts58kPerfMonPerfPhaseData[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonPerfPhaseData 13
#endif	/* defined(I_sts58kPerfMonPerfPhaseData) */


#if defined(I_sts58kPerfMonPerfSESP)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonPerfSESP, "sts58kPerfMonPerfSESP")
const SR_UINT32 IDsts58kPerfMonPerfSESP[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 11 };
#else
extern const SR_UINT32 IDsts58kPerfMonPerfSESP[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonPerfSESP 13
#endif	/* defined(I_sts58kPerfMonPerfSESP) */


#if defined(I_sts58kPerfMonPerfTIE)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonPerfTIE, "sts58kPerfMonPerfTIE")
const SR_UINT32 IDsts58kPerfMonPerfTIE[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 12 };
#else
extern const SR_UINT32 IDsts58kPerfMonPerfTIE[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonPerfTIE 13
#endif	/* defined(I_sts58kPerfMonPerfTIE) */


#if defined(I_sts58kPerfMonPerfMTIE)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonPerfMTIE, "sts58kPerfMonPerfMTIE")
const SR_UINT32 IDsts58kPerfMonPerfMTIE[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 13 };
#else
extern const SR_UINT32 IDsts58kPerfMonPerfMTIE[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonPerfMTIE 13
#endif	/* defined(I_sts58kPerfMonPerfMTIE) */


#if defined(I_sts58kPerfMonPerfWDR5M)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonPerfWDR5M, "sts58kPerfMonPerfWDR5M")
const SR_UINT32 IDsts58kPerfMonPerfWDR5M[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 14 };
#else
extern const SR_UINT32 IDsts58kPerfMonPerfWDR5M[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonPerfWDR5M 13
#endif	/* defined(I_sts58kPerfMonPerfWDR5M) */


#if defined(I_sts58kPerfMonPerfWDR24H)
#ifdef SNMPPART_DECL
STdeclare(STsts58kPerfMonPerfWDR24H, "sts58kPerfMonPerfWDR24H")
const SR_UINT32 IDsts58kPerfMonPerfWDR24H[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 15 };
#else
extern const SR_UINT32 IDsts58kPerfMonPerfWDR24H[];
#endif	/* SNMPPART_DECL */
#define LNsts58kPerfMonPerfWDR24H 13
#endif	/* defined(I_sts58kPerfMonPerfWDR24H) */


#if defined(N_sts58kAlarmStatus)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kAlarmStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19 };
#else
extern const SR_UINT32 IDsts58kAlarmStatus[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmStatus 10
#endif	/* defined(N_sts58kAlarmStatus) */




#if defined(I_sts58kAlarmSource)
#ifdef SNMPPART_DECL
STdeclare(STsts58kAlarmSource, "sts58kAlarmSource")
const SR_UINT32 IDsts58kAlarmSource[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kAlarmSource[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmSource 13
#endif	/* defined(I_sts58kAlarmSource) */


#if defined(I_sts58kAlarmSourceType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kAlarmSourceType, "sts58kAlarmSourceType")
const SR_UINT32 IDsts58kAlarmSourceType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kAlarmSourceType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmSourceType 13
#endif	/* defined(I_sts58kAlarmSourceType) */


#if defined(I_sts58kAlarmSeverity)
#ifdef SNMPPART_DECL
STdeclare(STsts58kAlarmSeverity, "sts58kAlarmSeverity")
const SR_UINT32 IDsts58kAlarmSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kAlarmSeverity[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmSeverity 13
#endif	/* defined(I_sts58kAlarmSeverity) */


#if defined(I_sts58kAlarmSrvEff)
#ifdef SNMPPART_DECL
STdeclare(STsts58kAlarmSrvEff, "sts58kAlarmSrvEff")
const SR_UINT32 IDsts58kAlarmSrvEff[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kAlarmSrvEff[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmSrvEff 13
#endif	/* defined(I_sts58kAlarmSrvEff) */


#if defined(N_sts58kOutputCard)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOutputCard[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20 };
#else
extern const SR_UINT32 IDsts58kOutputCard[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputCard 10
#endif	/* defined(N_sts58kOutputCard) */




#if defined(I_sts58kOutputShelf)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputShelf, "sts58kOutputShelf")
const SR_UINT32 IDsts58kOutputShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kOutputShelf[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputShelf 13
#endif	/* defined(I_sts58kOutputShelf) */


#if defined(I_sts58kOutputSlot)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputSlot, "sts58kOutputSlot")
const SR_UINT32 IDsts58kOutputSlot[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kOutputSlot[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputSlot 13
#endif	/* defined(I_sts58kOutputSlot) */


#if defined(I_sts58kOutputRedState)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputRedState, "sts58kOutputRedState")
const SR_UINT32 IDsts58kOutputRedState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kOutputRedState[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputRedState 13
#endif	/* defined(I_sts58kOutputRedState) */


#if defined(I_sts58kOutputRedSwitchState)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputRedSwitchState, "sts58kOutputRedSwitchState")
const SR_UINT32 IDsts58kOutputRedSwitchState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kOutputRedSwitchState[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputRedSwitchState 13
#endif	/* defined(I_sts58kOutputRedSwitchState) */


#if defined(I_sts58kOutputCRCCHK)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputCRCCHK, "sts58kOutputCRCCHK")
const SR_UINT32 IDsts58kOutputCRCCHK[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 5 };
#else
extern const SR_UINT32 IDsts58kOutputCRCCHK[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputCRCCHK 13
#endif	/* defined(I_sts58kOutputCRCCHK) */


#if defined(I_sts58kOutputCAS)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputCAS, "sts58kOutputCAS")
const SR_UINT32 IDsts58kOutputCAS[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 6 };
#else
extern const SR_UINT32 IDsts58kOutputCAS[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputCAS 13
#endif	/* defined(I_sts58kOutputCAS) */


#if defined(I_sts58kOutputSSM)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputSSM, "sts58kOutputSSM")
const SR_UINT32 IDsts58kOutputSSM[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 7 };
#else
extern const SR_UINT32 IDsts58kOutputSSM[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputSSM 13
#endif	/* defined(I_sts58kOutputSSM) */


#if defined(I_sts58kOutputSSMValue)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputSSMValue, "sts58kOutputSSMValue")
const SR_UINT32 IDsts58kOutputSSMValue[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 8 };
#else
extern const SR_UINT32 IDsts58kOutputSSMValue[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputSSMValue 13
#endif	/* defined(I_sts58kOutputSSMValue) */


#if defined(I_sts58kOutputTimingFormat)
#ifdef SNMPPART_DECL
STdeclare(STsts58kOutputTimingFormat, "sts58kOutputTimingFormat")
const SR_UINT32 IDsts58kOutputTimingFormat[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 9 };
#else
extern const SR_UINT32 IDsts58kOutputTimingFormat[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputTimingFormat 13
#endif	/* defined(I_sts58kOutputTimingFormat) */


#if defined(N_sts58kEmmStatus)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kEmmStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21 };
#else
extern const SR_UINT32 IDsts58kEmmStatus[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEmmStatus 10
#endif	/* defined(N_sts58kEmmStatus) */




#if defined(I_sts58kEmmShelf)
#ifdef SNMPPART_DECL
STdeclare(STsts58kEmmShelf, "sts58kEmmShelf")
const SR_UINT32 IDsts58kEmmShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kEmmShelf[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEmmShelf 13
#endif	/* defined(I_sts58kEmmShelf) */


#if defined(I_sts58kEmmUnitId)
#ifdef SNMPPART_DECL
STdeclare(STsts58kEmmUnitId, "sts58kEmmUnitId")
const SR_UINT32 IDsts58kEmmUnitId[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kEmmUnitId[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEmmUnitId 13
#endif	/* defined(I_sts58kEmmUnitId) */


#if defined(I_sts58kEmmSensorType)
#ifdef SNMPPART_DECL
STdeclare(STsts58kEmmSensorType, "sts58kEmmSensorType")
const SR_UINT32 IDsts58kEmmSensorType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kEmmSensorType[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEmmSensorType 13
#endif	/* defined(I_sts58kEmmSensorType) */


#if defined(I_sts58kEmmAlarmStatus)
#ifdef SNMPPART_DECL
STdeclare(STsts58kEmmAlarmStatus, "sts58kEmmAlarmStatus")
const SR_UINT32 IDsts58kEmmAlarmStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kEmmAlarmStatus[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEmmAlarmStatus 13
#endif	/* defined(I_sts58kEmmAlarmStatus) */


#if defined(I_sts58kEmmSensorReading)
#ifdef SNMPPART_DECL
STdeclare(STsts58kEmmSensorReading, "sts58kEmmSensorReading")
const SR_UINT32 IDsts58kEmmSensorReading[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 5 };
#else
extern const SR_UINT32 IDsts58kEmmSensorReading[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEmmSensorReading 13
#endif	/* defined(I_sts58kEmmSensorReading) */


#if defined(I_sts58kEmmMajorAlmHiThresh)
#ifdef SNMPPART_DECL
STdeclare(STsts58kEmmMajorAlmHiThresh, "sts58kEmmMajorAlmHiThresh")
const SR_UINT32 IDsts58kEmmMajorAlmHiThresh[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 6 };
#else
extern const SR_UINT32 IDsts58kEmmMajorAlmHiThresh[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEmmMajorAlmHiThresh 13
#endif	/* defined(I_sts58kEmmMajorAlmHiThresh) */


#if defined(I_sts58kEmmMajorAlmLoThresh)
#ifdef SNMPPART_DECL
STdeclare(STsts58kEmmMajorAlmLoThresh, "sts58kEmmMajorAlmLoThresh")
const SR_UINT32 IDsts58kEmmMajorAlmLoThresh[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 7 };
#else
extern const SR_UINT32 IDsts58kEmmMajorAlmLoThresh[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEmmMajorAlmLoThresh 13
#endif	/* defined(I_sts58kEmmMajorAlmLoThresh) */


#if defined(I_sts58kEmmMinorAlmHiThresh)
#ifdef SNMPPART_DECL
STdeclare(STsts58kEmmMinorAlmHiThresh, "sts58kEmmMinorAlmHiThresh")
const SR_UINT32 IDsts58kEmmMinorAlmHiThresh[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 8 };
#else
extern const SR_UINT32 IDsts58kEmmMinorAlmHiThresh[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEmmMinorAlmHiThresh 13
#endif	/* defined(I_sts58kEmmMinorAlmHiThresh) */


#if defined(I_sts58kEmmMinorAlmLoThresh)
#ifdef SNMPPART_DECL
STdeclare(STsts58kEmmMinorAlmLoThresh, "sts58kEmmMinorAlmLoThresh")
const SR_UINT32 IDsts58kEmmMinorAlmLoThresh[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 9 };
#else
extern const SR_UINT32 IDsts58kEmmMinorAlmLoThresh[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEmmMinorAlmLoThresh 13
#endif	/* defined(I_sts58kEmmMinorAlmLoThresh) */


#if defined(N_sts58kAnt)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kAnt[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 22 };
#else
extern const SR_UINT32 IDsts58kAnt[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAnt 10
#endif	/* defined(N_sts58kAnt) */




#if defined(I_sts58kAntIndex)
#ifdef SNMPPART_DECL
STdeclare(STsts58kAntIndex, "sts58kAntIndex")
const SR_UINT32 IDsts58kAntIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 22, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kAntIndex[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAntIndex 13
#endif	/* defined(I_sts58kAntIndex) */


#if defined(I_sts58kAntStatus)
#ifdef SNMPPART_DECL
STdeclare(STsts58kAntStatus, "sts58kAntStatus")
const SR_UINT32 IDsts58kAntStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 22, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kAntStatus[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAntStatus 13
#endif	/* defined(I_sts58kAntStatus) */


#if defined(I_sts58kAntSwitchState)
#ifdef SNMPPART_DECL
STdeclare(STsts58kAntSwitchState, "sts58kAntSwitchState")
const SR_UINT32 IDsts58kAntSwitchState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 22, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kAntSwitchState[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAntSwitchState 13
#endif	/* defined(I_sts58kAntSwitchState) */


#if defined(N_sts58kTopDest)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kTopDest[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23 };
#else
extern const SR_UINT32 IDsts58kTopDest[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopDest 10
#endif	/* defined(N_sts58kTopDest) */




#if defined(I_sts58kTopDestNumber)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopDestNumber, "sts58kTopDestNumber")
const SR_UINT32 IDsts58kTopDestNumber[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kTopDestNumber[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopDestNumber 13
#endif	/* defined(I_sts58kTopDestNumber) */


#if defined(I_sts58kTopDestIp)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopDestIp, "sts58kTopDestIp")
const SR_UINT32 IDsts58kTopDestIp[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kTopDestIp[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopDestIp 13
#endif	/* defined(I_sts58kTopDestIp) */


#if defined(I_sts58kTopDestUdpPort)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopDestUdpPort, "sts58kTopDestUdpPort")
const SR_UINT32 IDsts58kTopDestUdpPort[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kTopDestUdpPort[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopDestUdpPort 13
#endif	/* defined(I_sts58kTopDestUdpPort) */


#if defined(I_sts58kTopDestVlanId)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTopDestVlanId, "sts58kTopDestVlanId")
const SR_UINT32 IDsts58kTopDestVlanId[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kTopDestVlanId[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopDestVlanId 13
#endif	/* defined(I_sts58kTopDestVlanId) */


#if defined(N_sts58kTrapReg)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kTrapReg[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24 };
#else
extern const SR_UINT32 IDsts58kTrapReg[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTrapReg 10
#endif	/* defined(N_sts58kTrapReg) */




#if defined(I_sts58kTrapRegMgrNumber)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTrapRegMgrNumber, "sts58kTrapRegMgrNumber")
const SR_UINT32 IDsts58kTrapRegMgrNumber[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 1 };
#else
extern const SR_UINT32 IDsts58kTrapRegMgrNumber[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTrapRegMgrNumber 13
#endif	/* defined(I_sts58kTrapRegMgrNumber) */


#if defined(I_sts58kTrapRegMgrIp)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTrapRegMgrIp, "sts58kTrapRegMgrIp")
const SR_UINT32 IDsts58kTrapRegMgrIp[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 2 };
#else
extern const SR_UINT32 IDsts58kTrapRegMgrIp[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTrapRegMgrIp 13
#endif	/* defined(I_sts58kTrapRegMgrIp) */


#if defined(I_sts58kTrapRegMgrUdpPort)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTrapRegMgrUdpPort, "sts58kTrapRegMgrUdpPort")
const SR_UINT32 IDsts58kTrapRegMgrUdpPort[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 3 };
#else
extern const SR_UINT32 IDsts58kTrapRegMgrUdpPort[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTrapRegMgrUdpPort 13
#endif	/* defined(I_sts58kTrapRegMgrUdpPort) */


#if defined(I_sts58kTrapRegCommunityStr)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTrapRegCommunityStr, "sts58kTrapRegCommunityStr")
const SR_UINT32 IDsts58kTrapRegCommunityStr[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 4 };
#else
extern const SR_UINT32 IDsts58kTrapRegCommunityStr[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTrapRegCommunityStr 13
#endif	/* defined(I_sts58kTrapRegCommunityStr) */


#if defined(I_sts58kTrapRegState)
#ifdef SNMPPART_DECL
STdeclare(STsts58kTrapRegState, "sts58kTrapRegState")
const SR_UINT32 IDsts58kTrapRegState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 5 };
#else
extern const SR_UINT32 IDsts58kTrapRegState[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTrapRegState 13
#endif	/* defined(I_sts58kTrapRegState) */


#if defined(N_sts58kTrap)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kTrap[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101 };
#else
extern const SR_UINT32 IDsts58kTrap[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTrap 10
#endif	/* defined(N_sts58kTrap) */


#if defined(N_sts58kSystemIpConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kSystemIpConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1001 };
#else
extern const SR_UINT32 IDsts58kSystemIpConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemIpConfigChange 11
#endif	/* defined(N_sts58kSystemIpConfigChange) */


#if defined(N_sts58kSystemConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kSystemConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1002 };
#else
extern const SR_UINT32 IDsts58kSystemConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemConfigChange 11
#endif	/* defined(N_sts58kSystemConfigChange) */


#if defined(N_sts58kSystemReset)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kSystemReset[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1003 };
#else
extern const SR_UINT32 IDsts58kSystemReset[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemReset 11
#endif	/* defined(N_sts58kSystemReset) */


#if defined(N_sts58kSystemAlarmStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kSystemAlarmStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1004 };
#else
extern const SR_UINT32 IDsts58kSystemAlarmStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemAlarmStatusChange 11
#endif	/* defined(N_sts58kSystemAlarmStatusChange) */


#if defined(N_sts58kSystemSWVersionChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kSystemSWVersionChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1005 };
#else
extern const SR_UINT32 IDsts58kSystemSWVersionChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kSystemSWVersionChange 11
#endif	/* defined(N_sts58kSystemSWVersionChange) */


#if defined(N_sts58kClockInputChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kClockInputChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1101 };
#else
extern const SR_UINT32 IDsts58kClockInputChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputChange 11
#endif	/* defined(N_sts58kClockInputChange) */


#if defined(N_sts58kClockInputStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kClockInputStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1102 };
#else
extern const SR_UINT32 IDsts58kClockInputStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputStatusChange 11
#endif	/* defined(N_sts58kClockInputStatusChange) */


#if defined(N_sts58kClockInputSSMConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kClockInputSSMConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1103 };
#else
extern const SR_UINT32 IDsts58kClockInputSSMConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kClockInputSSMConfigChange 11
#endif	/* defined(N_sts58kClockInputSSMConfigChange) */


#if defined(N_sts58kTopConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kTopConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1104 };
#else
extern const SR_UINT32 IDsts58kTopConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopConfigChange 11
#endif	/* defined(N_sts58kTopConfigChange) */


#if defined(N_sts58kTopDestConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kTopDestConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1105 };
#else
extern const SR_UINT32 IDsts58kTopDestConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTopDestConfigChange 11
#endif	/* defined(N_sts58kTopDestConfigChange) */


#if defined(N_sts58kCardStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kCardStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1201 };
#else
extern const SR_UINT32 IDsts58kCardStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kCardStatusChange 11
#endif	/* defined(N_sts58kCardStatusChange) */


#if defined(N_sts58kOscillatorStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOscillatorStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1301 };
#else
extern const SR_UINT32 IDsts58kOscillatorStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorStatusChange 11
#endif	/* defined(N_sts58kOscillatorStatusChange) */


#if defined(N_sts58kGpsStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kGpsStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1401 };
#else
extern const SR_UINT32 IDsts58kGpsStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kGpsStatusChange 11
#endif	/* defined(N_sts58kGpsStatusChange) */


#if defined(N_sts58kLinkConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kLinkConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1501 };
#else
extern const SR_UINT32 IDsts58kLinkConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkConfigChange 11
#endif	/* defined(N_sts58kLinkConfigChange) */


#if defined(N_sts58kAlarmThresholdConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kAlarmThresholdConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1601 };
#else
extern const SR_UINT32 IDsts58kAlarmThresholdConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmThresholdConfigChange 11
#endif	/* defined(N_sts58kAlarmThresholdConfigChange) */


#if defined(N_sts58kLinkAlarmSettingConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kLinkAlarmSettingConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1701 };
#else
extern const SR_UINT32 IDsts58kLinkAlarmSettingConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkAlarmSettingConfigChange 11
#endif	/* defined(N_sts58kLinkAlarmSettingConfigChange) */


#if defined(N_sts58kLinkAlarmStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kLinkAlarmStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1702 };
#else
extern const SR_UINT32 IDsts58kLinkAlarmStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kLinkAlarmStatusChange 11
#endif	/* defined(N_sts58kLinkAlarmStatusChange) */


#if defined(N_sts58kOscillatorAlarmSettingConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOscillatorAlarmSettingConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1801 };
#else
extern const SR_UINT32 IDsts58kOscillatorAlarmSettingConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorAlarmSettingConfigChange 11
#endif	/* defined(N_sts58kOscillatorAlarmSettingConfigChange) */


#if defined(N_sts58kOscillatorAlarmStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOscillatorAlarmStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1802 };
#else
extern const SR_UINT32 IDsts58kOscillatorAlarmStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOscillatorAlarmStatusChange 11
#endif	/* defined(N_sts58kOscillatorAlarmStatusChange) */


#if defined(N_sts58kOsPwrAlarmSettingConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOsPwrAlarmSettingConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1901 };
#else
extern const SR_UINT32 IDsts58kOsPwrAlarmSettingConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOsPwrAlarmSettingConfigChange 11
#endif	/* defined(N_sts58kOsPwrAlarmSettingConfigChange) */


#if defined(N_sts58kOsPwrAlarmStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOsPwrAlarmStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 1902 };
#else
extern const SR_UINT32 IDsts58kOsPwrAlarmStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOsPwrAlarmStatusChange 11
#endif	/* defined(N_sts58kOsPwrAlarmStatusChange) */


#if defined(N_sts58kOutputAlarmSettingConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOutputAlarmSettingConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 2001 };
#else
extern const SR_UINT32 IDsts58kOutputAlarmSettingConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputAlarmSettingConfigChange 11
#endif	/* defined(N_sts58kOutputAlarmSettingConfigChange) */


#if defined(N_sts58kOutputAlarmStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOutputAlarmStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 2002 };
#else
extern const SR_UINT32 IDsts58kOutputAlarmStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputAlarmStatusChange 11
#endif	/* defined(N_sts58kOutputAlarmStatusChange) */


#if defined(N_sts58kOutputTiuSettingConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOutputTiuSettingConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 2003 };
#else
extern const SR_UINT32 IDsts58kOutputTiuSettingConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputTiuSettingConfigChange 11
#endif	/* defined(N_sts58kOutputTiuSettingConfigChange) */


#if defined(N_sts58kAlarmStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kAlarmStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 2101 };
#else
extern const SR_UINT32 IDsts58kAlarmStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAlarmStatusChange 11
#endif	/* defined(N_sts58kAlarmStatusChange) */


#if defined(N_sts58kOutputCardConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kOutputCardConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 2201 };
#else
extern const SR_UINT32 IDsts58kOutputCardConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kOutputCardConfigChange 11
#endif	/* defined(N_sts58kOutputCardConfigChange) */


#if defined(N_sts58kEMMAlarmStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kEMMAlarmStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 2301 };
#else
extern const SR_UINT32 IDsts58kEMMAlarmStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEMMAlarmStatusChange 11
#endif	/* defined(N_sts58kEMMAlarmStatusChange) */


#if defined(N_sts58kEMMAlarmThresholdChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kEMMAlarmThresholdChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 2302 };
#else
extern const SR_UINT32 IDsts58kEMMAlarmThresholdChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kEMMAlarmThresholdChange 11
#endif	/* defined(N_sts58kEMMAlarmThresholdChange) */


#if defined(N_sts58kAntStatusChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kAntStatusChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 2401 };
#else
extern const SR_UINT32 IDsts58kAntStatusChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kAntStatusChange 11
#endif	/* defined(N_sts58kAntStatusChange) */


#if defined(N_sts58kTrapRegMgrConfigChange)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsts58kTrapRegMgrConfigChange[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 101, 2501 };
#else
extern const SR_UINT32 IDsts58kTrapRegMgrConfigChange[];
#endif	/* SNMPPART_DECL */
#define LNsts58kTrapRegMgrConfigChange 11
#endif	/* defined(N_sts58kTrapRegMgrConfigChange) */


#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_LARUS58KPART_H */
