/*
 *
 * Copyright (C) 1992-2003 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -c Larus58k larus58kMib 
 */

/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_LARUS58KMIB_H
#define SR_LARUS58KMIB_H


#ifdef __cplusplus
extern "C" {
#endif

#ifdef SR_MIB_TABLE_HASHING
#define HASHNEXT(x) x, NULL
#else /* SR_MIB_TABLE_HASHING */
#define HASHNEXT(x) x
#endif /* SR_MIB_TABLE_HASHING */

/* SNMP-MIB translation table.  Subitem on left gets
 * translated into subitem on right.
 */

#ifndef LIGHT
static struct MIB_OID orig_mib_oid_table[] =
{
    { "larusMgmt",                       HASHNEXT("1.3.6.1.4.1.24628.2") },
    { "larus58kMib",                     HASHNEXT("1.3.6.1.4.1.24628.2.2") },
    { "sts58kSystem",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.1") },
    { "sts58kSystemId",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.1.1") },
    { "sts58kSystemMgmtIpOption",        HASHNEXT("1.3.6.1.4.1.24628.2.2.1.2") },
    { "sts58kSystemMgmtIpAddress",       HASHNEXT("1.3.6.1.4.1.24628.2.2.1.3") },
    { "sts58kSystemMgmtIpSubnetMask",    HASHNEXT("1.3.6.1.4.1.24628.2.2.1.4") },
    { "sts58kSystemMgmtIpGatewayAddress", HASHNEXT("1.3.6.1.4.1.24628.2.2.1.5") },
    { "sts58kSystemSntpIpOption",        HASHNEXT("1.3.6.1.4.1.24628.2.2.1.6") },
    { "sts58kSystemSntpIpAddress",       HASHNEXT("1.3.6.1.4.1.24628.2.2.1.7") },
    { "sts58kSystemSntpIpSubnetMask",    HASHNEXT("1.3.6.1.4.1.24628.2.2.1.8") },
    { "sts58kSystemSntpIpGatewayAddress", HASHNEXT("1.3.6.1.4.1.24628.2.2.1.9") },
    { "sts58kSystemTime",                HASHNEXT("1.3.6.1.4.1.24628.2.2.1.10") },
    { "sts58kSystemTimeZone",            HASHNEXT("1.3.6.1.4.1.24628.2.2.1.11") },
    { "sts58kSystemIntegratedAlarm",     HASHNEXT("1.3.6.1.4.1.24628.2.2.1.12") },
    { "sts58kSystemAlarmAcoMode",        HASHNEXT("1.3.6.1.4.1.24628.2.2.1.13") },
    { "sts58kSystemAlarmAcoLed",         HASHNEXT("1.3.6.1.4.1.24628.2.2.1.14") },
    { "sts58kSystemAlarmAcoCutOff",      HASHNEXT("1.3.6.1.4.1.24628.2.2.1.15") },
    { "sts58kSystemAlarmEscalatingTime", HASHNEXT("1.3.6.1.4.1.24628.2.2.1.16") },
    { "sts58kSystemMinorLED",            HASHNEXT("1.3.6.1.4.1.24628.2.2.1.17") },
    { "sts58kSystemMajorLED",            HASHNEXT("1.3.6.1.4.1.24628.2.2.1.18") },
    { "sts58kSystemCriticalLED",         HASHNEXT("1.3.6.1.4.1.24628.2.2.1.19") },
    { "sts58kSystemUpgradeSWAction",     HASHNEXT("1.3.6.1.4.1.24628.2.2.1.20") },
    { "sts58kSystemCurrentSWVersion",    HASHNEXT("1.3.6.1.4.1.24628.2.2.1.21") },
    { "sts58kSystemServiceState",        HASHNEXT("1.3.6.1.4.1.24628.2.2.1.22") },
    { "sts58kSystemWarmReset",           HASHNEXT("1.3.6.1.4.1.24628.2.2.1.23") },
    { "sts58kSystemColdReset",           HASHNEXT("1.3.6.1.4.1.24628.2.2.1.24") },
    { "sts58kSystemConfigReset",         HASHNEXT("1.3.6.1.4.1.24628.2.2.1.25") },
    { "sts58kClockInput",                HASHNEXT("1.3.6.1.4.1.24628.2.2.2") },
    { "sts58kClockInputManualSelect",    HASHNEXT("1.3.6.1.4.1.24628.2.2.2.1") },
    { "sts58kClockInputOperMode",        HASHNEXT("1.3.6.1.4.1.24628.2.2.2.2") },
    { "sts58kClockInputProtectedPri",    HASHNEXT("1.3.6.1.4.1.24628.2.2.2.3") },
    { "sts58kClockInputSetSlip",         HASHNEXT("1.3.6.1.4.1.24628.2.2.2.4") },
    { "sts58kClockInputType",            HASHNEXT("1.3.6.1.4.1.24628.2.2.2.5") },
    { "sts58kClockInputSSM",             HASHNEXT("1.3.6.1.4.1.24628.2.2.3") },
    { "sts58kClockInputSSMSelect",       HASHNEXT("1.3.6.1.4.1.24628.2.2.3.1") },
    { "sts58kTop",                       HASHNEXT("1.3.6.1.4.1.24628.2.2.4") },
    { "sts58kTopSourceIpOption",         HASHNEXT("1.3.6.1.4.1.24628.2.2.4.1") },
    { "sts58kTopSourceIpAddress",        HASHNEXT("1.3.6.1.4.1.24628.2.2.4.2") },
    { "sts58kTopSourceIpSubnetMask",     HASHNEXT("1.3.6.1.4.1.24628.2.2.4.3") },
    { "sts58kTopSourceIpGatewayAddress", HASHNEXT("1.3.6.1.4.1.24628.2.2.4.4") },
    { "sts58kTopPacketRate",             HASHNEXT("1.3.6.1.4.1.24628.2.2.4.5") },
    { "sts58kTopInputSelect",            HASHNEXT("1.3.6.1.4.1.24628.2.2.4.6") },
    { "sts58kTopTxPackets",              HASHNEXT("1.3.6.1.4.1.24628.2.2.4.7") },
    { "sts58kTopTxBytes",                HASHNEXT("1.3.6.1.4.1.24628.2.2.4.8") },
    { "sts58kClockInputStatus",          HASHNEXT("1.3.6.1.4.1.24628.2.2.5") },
    { "sts58kClockInputStatusTable",     HASHNEXT("1.3.6.1.4.1.24628.2.2.5.1") },
    { "sts58kClockInputStatusEntry",     HASHNEXT("1.3.6.1.4.1.24628.2.2.5.1.1") },
    { "sts58kClockInputStatusIndex",     HASHNEXT("1.3.6.1.4.1.24628.2.2.5.1.1.1") },
    { "sts58kClockInputState",           HASHNEXT("1.3.6.1.4.1.24628.2.2.5.1.1.2") },
    { "sts58kClockInputSSMStatus",       HASHNEXT("1.3.6.1.4.1.24628.2.2.6") },
    { "sts58kClockInputSSMTable",        HASHNEXT("1.3.6.1.4.1.24628.2.2.6.1") },
    { "sts58kClockInputSSMEntry",        HASHNEXT("1.3.6.1.4.1.24628.2.2.6.1.1") },
    { "sts58kClockInputSSMIndex",        HASHNEXT("1.3.6.1.4.1.24628.2.2.6.1.1.1") },
    { "sts58kClockInputSSMType",         HASHNEXT("1.3.6.1.4.1.24628.2.2.6.1.1.2") },
    { "sts58kClockInputSSMValue",        HASHNEXT("1.3.6.1.4.1.24628.2.2.6.1.1.3") },
    { "sts58kCard",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.7") },
    { "sts58kCardTable",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1") },
    { "sts58kCardEntry",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1") },
    { "sts58kCardShelf",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.1") },
    { "sts58kCardIndex",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.2") },
    { "sts58kCardType",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.3") },
    { "sts58kCardDescr",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.4") },
    { "sts58kCardSerial",                HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.5") },
    { "sts58kCardHwVersion",             HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.6") },
    { "sts58kCardCLEICode",              HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.7") },
    { "sts58kCardOperStatus",            HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.8") },
    { "sts58kCardReset",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.9") },
    { "sts58kOscillator",                HASHNEXT("1.3.6.1.4.1.24628.2.2.8") },
    { "sts58kOscillatorTable",           HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1") },
    { "sts58kOscillatorEntry",           HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1") },
    { "sts58kOscillatorIndex",           HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.1") },
    { "sts58kOscillatorModuleType",      HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.2") },
    { "sts58kOscillatorEFER",            HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.3") },
    { "sts58kOscillatorESSD",            HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.4") },
    { "sts58kOscillatorESSN",            HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.5") },
    { "sts58kOscillatorFAGE",            HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.6") },
    { "sts58kOscillatorTIMD",            HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.7") },
    { "sts58kOscillatorSetActive",       HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.8") },
    { "sts58kOscillatorStatus",          HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.9") },
    { "sts58kGPS",                       HASHNEXT("1.3.6.1.4.1.24628.2.2.9") },
    { "sts58kGpsTable",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1") },
    { "sts58kGpsEntry",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1") },
    { "sts58kGpsIndex",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.1") },
    { "sts58kGpsStatus",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.2") },
    { "sts58kGpsANTD",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.3") },
    { "sts58kGpsAZEL",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.4") },
    { "sts58kGpsRSTG",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.5") },
    { "sts58kGpsBITS",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.6") },
    { "sts58kGpsPAVG",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.7") },
    { "sts58kGpsSIGQ",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.8") },
    { "sts58kGpsSPOS",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.9") },
    { "sts58kGpsTRMO",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.10") },
    { "sts58kGpsUTCT",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.11") },
    { "sts58kGpsVERS",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.12") },
    { "sts58kGpsDETF",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.13") },
    { "sts58kGpsEFER",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.14") },
    { "sts58kGpsESSD",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.15") },
    { "sts58kGpsESSN",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.16") },
    { "sts58kGpsFAGE",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.17") },
    { "sts58kGpsTIMD",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.18") },
    { "sts58kGpsReset",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.19") },
    { "sts58kLink",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.10") },
    { "sts58kLinkTable",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1") },
    { "sts58kLinkEntry",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1") },
    { "sts58kLinkIndex",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.1") },
    { "sts58kLinkType",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.2") },
    { "sts58kLinkEnable",                HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.3") },
    { "sts58kLinkLineCode",              HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.4") },
    { "sts58kLinkFMT",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.5") },
    { "sts58kLinkTermination",           HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.6") },
    { "sts58kLinkMFCHK",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.7") },
    { "sts58kLinkId",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.8") },
    { "sts58kShelf",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.11") },
    { "sts58kShelfTable",                HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1") },
    { "sts58kShelfEntry",                HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1.1") },
    { "sts58kShelfIndex",                HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1.1.1") },
    { "sts58kShelfSerial",               HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1.1.2") },
    { "sts58kShelfCLEICode",             HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1.1.3") },
    { "sts58kShelfReset",                HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1.1.4") },
    { "sts58kAlarmThreshold",            HASHNEXT("1.3.6.1.4.1.24628.2.2.12") },
    { "sts58kAlarmThresholdTable",       HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1") },
    { "sts58kAlarmThresholdEntry",       HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1.1") },
    { "sts58kAlarmThresholdCurrentMon",  HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1.1.1") },
    { "sts58kAlarmThresholdType",        HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1.1.2") },
    { "sts58kAlarmThresholdValue",       HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1.1.3") },
    { "sts58kAlarmThresholdTimeInterval", HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1.1.4") },
    { "sts58kLinkAlarmSetting",          HASHNEXT("1.3.6.1.4.1.24628.2.2.13") },
    { "sts58kLinkAlarmTable",            HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1") },
    { "sts58kLinkAlarmEntry",            HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1.1") },
    { "sts58kLinkAlarmSettingLinkType",  HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1.1.1") },
    { "sts58kLinkAlarmSettingType",      HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1.1.2") },
    { "sts58kLinkAlarmSettingSevirity",  HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1.1.3") },
    { "sts58kLinkAlarmSevirity",         HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1.1.4") },
    { "sts58kOscillatorAlarmSetting",    HASHNEXT("1.3.6.1.4.1.24628.2.2.14") },
    { "sts58kOscillatorAlarmTable",      HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1") },
    { "sts58kOscillatorAlarmEntry",      HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1.1") },
    { "sts58kOscillatorAlarmSettingClock", HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1.1.1") },
    { "sts58kOscillatorAlarmSettingType", HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1.1.2") },
    { "sts58kOscillatorAlarmSettingSeverity", HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1.1.3") },
    { "sts58kOscillatorAlarmSeverity",   HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1.1.4") },
    { "sts58kOsPwrAlarmSetting",         HASHNEXT("1.3.6.1.4.1.24628.2.2.15") },
    { "sts58kOsPwrAlarmTable",           HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1") },
    { "sts58kOsPwrAlarmEntry",           HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1.1") },
    { "sts58ksPwrAlarmSettingShelf",     HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1.1.1") },
    { "sts58kOsPwrAlarmSettingOsPwr",    HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1.1.2") },
    { "sts58kOsPwrAlarmSettingSeverity", HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1.1.3") },
    { "sts58kOsPwrAlarmSeverity",        HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1.1.4") },
    { "sts58kOutputAlarmSetting",        HASHNEXT("1.3.6.1.4.1.24628.2.2.16") },
    { "sts58kOutputAlarmTable",          HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1") },
    { "sts58kOutputAlarmEntry",          HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1") },
    { "sts58kOutputAlarmSettingShelf",   HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.1") },
    { "sts58kOutputAlarmSettingSlot",    HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.2") },
    { "sts58kOutputAlarmSettingPort",    HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.3") },
    { "sts58kOutputAlarmSettingType",    HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.4") },
    { "sts58kOutputAlarmSettingSeverity", HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.5") },
    { "sts58kOutputAlarmSeverity",       HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.6") },
    { "sts58kOutputTiuSetting",          HASHNEXT("1.3.6.1.4.1.24628.2.2.17") },
    { "sts58kOutputTiuSettingTable",     HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1") },
    { "sts58kOutputTiuSettingEntry",     HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1") },
    { "sts58kOutputTiuSettingShelf",     HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.1") },
    { "sts58kOutputTiuSettingSlot",      HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.2") },
    { "sts58kOutputTiuSettingPort",      HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.3") },
    { "sts58kOutputTiuSettingLineCoding", HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.4") },
    { "sts58kOutputTiuSettingFMT",       HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.5") },
    { "sts58kOutputTiuSettingTermination", HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.6") },
    { "sts58kPerfMon",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.18") },
    { "sts58kPerfMonTable",              HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1") },
    { "sts58kPerfMonEntry",              HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1") },
    { "sts58kPerfMonInputCurrentMon",    HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.1") },
    { "sts58kPerfMonInputMonPeriod",     HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.2") },
    { "sts58kPerfMonInputMonBucket",     HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.3") },
    { "sts58kPerfMonInputClockType",     HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.4") },
    { "sts58kPerfMonPerfCVL",            HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.5") },
    { "sts58kPerfMonPerfCVP",            HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.6") },
    { "sts58kPerfMonPerfCS",             HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.7") },
    { "sts58kPerfMonPerfESP",            HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.8") },
    { "sts58kPerfMonPerfJitter",         HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.9") },
    { "sts58kPerfMonPerfPhaseData",      HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.10") },
    { "sts58kPerfMonPerfSESP",           HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.11") },
    { "sts58kPerfMonPerfTIE",            HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.12") },
    { "sts58kPerfMonPerfMTIE",           HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.13") },
    { "sts58kPerfMonPerfWDR5M",          HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.14") },
    { "sts58kPerfMonPerfWDR24H",         HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.15") },
    { "sts58kAlarmStatus",               HASHNEXT("1.3.6.1.4.1.24628.2.2.19") },
    { "sts58kAlarmStatusTable",          HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1") },
    { "sts58kAlarmStatusEntry",          HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1.1") },
    { "sts58kAlarmSource",               HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1.1.1") },
    { "sts58kAlarmSourceType",           HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1.1.2") },
    { "sts58kAlarmSeverity",             HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1.1.3") },
    { "sts58kAlarmSrvEff",               HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1.1.4") },
    { "sts58kOutputCard",                HASHNEXT("1.3.6.1.4.1.24628.2.2.20") },
    { "sts58kOutputCardTable",           HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1") },
    { "sts58kOutputCardEntry",           HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1") },
    { "sts58kOutputShelf",               HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.1") },
    { "sts58kOutputSlot",                HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.2") },
    { "sts58kOutputRedState",            HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.3") },
    { "sts58kOutputRedSwitchState",      HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.4") },
    { "sts58kOutputCRCCHK",              HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.5") },
    { "sts58kOutputCAS",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.6") },
    { "sts58kOutputSSM",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.7") },
    { "sts58kOutputSSMValue",            HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.8") },
    { "sts58kOutputTimingFormat",        HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.9") },
    { "sts58kEmmStatus",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.21") },
    { "sts58kEmmStatusTable",            HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1") },
    { "sts58kEmmStatusEntry",            HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1") },
    { "sts58kEmmShelf",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.1") },
    { "sts58kEmmUnitId",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.2") },
    { "sts58kEmmSensorType",             HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.3") },
    { "sts58kEmmAlarmStatus",            HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.4") },
    { "sts58kEmmSensorReading",          HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.5") },
    { "sts58kEmmMajorAlmHiThresh",       HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.6") },
    { "sts58kEmmMajorAlmLoThresh",       HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.7") },
    { "sts58kEmmMinorAlmHiThresh",       HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.8") },
    { "sts58kEmmMinorAlmLoThresh",       HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.9") },
    { "sts58kAnt",                       HASHNEXT("1.3.6.1.4.1.24628.2.2.22") },
    { "sts58kAntTable",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.22.1") },
    { "sts58kAntEntry",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.22.1.1") },
    { "sts58kAntIndex",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.22.1.1.1") },
    { "sts58kAntStatus",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.22.1.1.2") },
    { "sts58kAntSwitchState",            HASHNEXT("1.3.6.1.4.1.24628.2.2.22.1.1.3") },
    { "sts58kTopDest",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.23") },
    { "sts58kTopDestTable",              HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1") },
    { "sts58kTopDestEntry",              HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1.1") },
    { "sts58kTopDestNumber",             HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1.1.1") },
    { "sts58kTopDestIp",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1.1.2") },
    { "sts58kTopDestUdpPort",            HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1.1.3") },
    { "sts58kTopDestVlanId",             HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1.1.4") },
    { "sts58kTrapReg",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.24") },
    { "sts58kTrapRegTable",              HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1") },
    { "sts58kTrapRegEntry",              HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1") },
    { "sts58kTrapRegMgrNumber",          HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1.1") },
    { "sts58kTrapRegMgrIp",              HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1.2") },
    { "sts58kTrapRegMgrUdpPort",         HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1.3") },
    { "sts58kTrapRegCommunityStr",       HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1.4") },
    { "sts58kTrapRegState",              HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1.5") },
    { "sts58kTrap",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.101") },
    { "sts58kSystemIpConfigChange",      HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1001") },
    { "sts58kSystemConfigChange",        HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1002") },
    { "sts58kSystemReset",               HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1003") },
    { "sts58kSystemAlarmStatusChange",   HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1004") },
    { "sts58kSystemSWVersionChange",     HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1005") },
    { "sts58kClockInputChange",          HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1101") },
    { "sts58kClockInputStatusChange",    HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1102") },
    { "sts58kClockInputSSMConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1103") },
    { "sts58kTopConfigChange",           HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1104") },
    { "sts58kTopDestConfigChange",       HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1105") },
    { "sts58kCardStatusChange",          HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1201") },
    { "sts58kOscillatorStatusChange",    HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1301") },
    { "sts58kGpsStatusChange",           HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1401") },
    { "sts58kLinkConfigChange",          HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1501") },
    { "sts58kAlarmThresholdConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1601") },
    { "sts58kLinkAlarmSettingConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1701") },
    { "sts58kLinkAlarmStatusChange",     HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1702") },
    { "sts58kOscillatorAlarmSettingConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1801") },
    { "sts58kOscillatorAlarmStatusChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1802") },
    { "sts58kOsPwrAlarmSettingConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1901") },
    { "sts58kOsPwrAlarmStatusChange",    HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1902") },
    { "sts58kOutputAlarmSettingConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2001") },
    { "sts58kOutputAlarmStatusChange",   HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2002") },
    { "sts58kOutputTiuSettingConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2003") },
    { "sts58kAlarmStatusChange",         HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2101") },
    { "sts58kOutputCardConfigChange",    HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2201") },
    { "sts58kEMMAlarmStatusChange",      HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2301") },
    { "sts58kEMMAlarmThresholdChange",   HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2302") },
    { "sts58kAntStatusChange",           HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2401") },
    { "sts58kTrapRegMgrConfigChange",    HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2501") },
    { (char *) 0, HASHNEXT((char *) 0) }
};
#else /* LIGHT */
static struct MIB_OID orig_mib_oid_table[] =
{
    { "snmpResearch",                    HASHNEXT("1.3.6.1.4.1.99") },
    { (char *) 0, HASHNEXT((char *) 0) }
};
#endif /* LIGHT */



/* Don't put anything after this #endif */ 

#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_LARUS58KMIB_H */
