/*
 *
 * Copyright (C) 1992-2003 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -search_table (implies -row_status) -c Larus58k larus58kMib -agent -per_file_init 
 * 
 */

/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_LARUS58KDEFS_H
#define SR_LARUS58KDEFS_H


#ifdef __cplusplus
extern "C" {
#endif

/* enumerated values for sts58kSystemMgmtIpOption */
#define D_sts58kSystemMgmtIpOption_static 1
#define D_sts58kSystemMgmtIpOption_dhcp 2

/* enumerated values for sts58kSystemSntpIpOption */
#define D_sts58kSystemSntpIpOption_static 1
#define D_sts58kSystemSntpIpOption_dhcp 2

/* enumerated values for sts58kSystemTimeZone */
#define D_sts58kSystemTimeZone_gmtplus12 1
#define D_sts58kSystemTimeZone_gmtplus11 2
#define D_sts58kSystemTimeZone_gmtplus10 3
#define D_sts58kSystemTimeZone_gmtplus09 4
#define D_sts58kSystemTimeZone_gmtplus08 5
#define D_sts58kSystemTimeZone_gmtplus07 6
#define D_sts58kSystemTimeZone_gmtplus06 7
#define D_sts58kSystemTimeZone_gmtplus05 8
#define D_sts58kSystemTimeZone_gmtplus04 9
#define D_sts58kSystemTimeZone_gmtplus03 10
#define D_sts58kSystemTimeZone_gmtplus02 11
#define D_sts58kSystemTimeZone_gmtplus01 12
#define D_sts58kSystemTimeZone_gmt     13
#define D_sts58kSystemTimeZone_gmtminus01 14
#define D_sts58kSystemTimeZone_gmtminus02 15
#define D_sts58kSystemTimeZone_gmtminus03 16
#define D_sts58kSystemTimeZone_gmtminus04 17
#define D_sts58kSystemTimeZone_gmtminus05 18
#define D_sts58kSystemTimeZone_gmtminus06 19
#define D_sts58kSystemTimeZone_gmtminus07 20
#define D_sts58kSystemTimeZone_gmtminus08 21
#define D_sts58kSystemTimeZone_gmtminus09 22
#define D_sts58kSystemTimeZone_gmtminus10 23
#define D_sts58kSystemTimeZone_gmtminus11 24
#define D_sts58kSystemTimeZone_gmtminus12 25

/* enumerated values for sts58kSystemIntegratedAlarm */
#define D_sts58kSystemIntegratedAlarm_clear 1
#define D_sts58kSystemIntegratedAlarm_minor 2
#define D_sts58kSystemIntegratedAlarm_major 3
#define D_sts58kSystemIntegratedAlarm_critical 4

/* enumerated values for sts58kSystemAlarmAcoMode */
#define D_sts58kSystemAlarmAcoMode_manual 1
#define D_sts58kSystemAlarmAcoMode_auto 2

/* enumerated values for sts58kSystemAlarmAcoLed */
#define D_sts58kSystemAlarmAcoLed_on   1
#define D_sts58kSystemAlarmAcoLed_off  2

/* enumerated values for sts58kSystemAlarmAcoCutOff */
#define D_sts58kSystemAlarmAcoCutOff_no_change 1
#define D_sts58kSystemAlarmAcoCutOff_cutoff 2

/* enumerated values for sts58kSystemMinorLED */
#define D_sts58kSystemMinorLED_off     1
#define D_sts58kSystemMinorLED_on      2

/* enumerated values for sts58kSystemMajorLED */
#define D_sts58kSystemMajorLED_off     1
#define D_sts58kSystemMajorLED_on      2

/* enumerated values for sts58kSystemCriticalLED */
#define D_sts58kSystemCriticalLED_off  1
#define D_sts58kSystemCriticalLED_on   2

/* enumerated values for sts58kSystemUpgradeSWAction */
#define D_sts58kSystemUpgradeSWAction_no_action 1
#define D_sts58kSystemUpgradeSWAction_upgrade 2

/* enumerated values for sts58kSystemServiceState */
#define D_sts58kSystemServiceState_init 1
#define D_sts58kSystemServiceState_inService 2
#define D_sts58kSystemServiceState_outOfService 3

/* enumerated values for sts58kSystemWarmReset */
#define D_sts58kSystemWarmReset_noAction 1
#define D_sts58kSystemWarmReset_reset  2

/* enumerated values for sts58kSystemColdReset */
#define D_sts58kSystemColdReset_noAction 1
#define D_sts58kSystemColdReset_reset  2

/* enumerated values for sts58kSystemConfigReset */
#define D_sts58kSystemConfigReset_noAction 1
#define D_sts58kSystemConfigReset_reset 2

/* enumerated values for sts58kClockInputManualSelect */
#define D_sts58kClockInputManualSelect_esr1 1
#define D_sts58kClockInputManualSelect_esr2 2
#define D_sts58kClockInputManualSelect_prs 3
#define D_sts58kClockInputManualSelect_input1 4
#define D_sts58kClockInputManualSelect_input2 5

/* enumerated values for sts58kClockInputOperMode */
#define D_sts58kClockInputOperMode_protected 1
#define D_sts58kClockInputOperMode_manual 2

/* enumerated values for sts58kClockInputProtectedPri */
#define D_sts58kClockInputProtectedPri_esr 1
#define D_sts58kClockInputProtectedPri_input 2
#define D_sts58kClockInputProtectedPri_prs 3

/* enumerated values for sts58kClockInputSetSlip */
#define D_sts58kClockInputSetSlip_betweenTwoClockModule 1
#define D_sts58kClockInputSetSlip_active_input1 2
#define D_sts58kClockInputSetSlip_active_input2 3
#define D_sts58kClockInputSetSlip_active_input3 4
#define D_sts58kClockInputSetSlip_active_input4 5
#define D_sts58kClockInputSetSlip_active_input5 6

/* enumerated values for sts58kClockInputType */
#define D_sts58kClockInputType_stratum1 1
#define D_sts58kClockInputType_stratum2 2
#define D_sts58kClockInputType_stratum3 3

/* enumerated values for sts58kClockInputSSMSelect */
#define D_sts58kClockInputSSMSelect_e1_sa4_ssm 1
#define D_sts58kClockInputSSMSelect_e1_sa5_ssm 2
#define D_sts58kClockInputSSMSelect_e1_sa6_ssm 3
#define D_sts58kClockInputSSMSelect_e1_sa7_ssm 4
#define D_sts58kClockInputSSMSelect_e1_sa8_ssm 5
#define D_sts58kClockInputSSMSelect_t1_ssm 6

/* enumerated values for sts58kTopSourceIpOption */
#define D_sts58kTopSourceIpOption_static 1
#define D_sts58kTopSourceIpOption_dhcp 2

/* enumerated values for sts58kTopInputSelect */
#define D_sts58kTopInputSelect_e1      1
#define D_sts58kTopInputSelect_t1      2
#define D_sts58kTopInputSelect_cc      3

/* enumerated values for sts58kClockInputStatusIndex */
#define D_sts58kClockInputStatusIndex_esr1 1
#define D_sts58kClockInputStatusIndex_esr2 2
#define D_sts58kClockInputStatusIndex_prs 3
#define D_sts58kClockInputStatusIndex_input1 4
#define D_sts58kClockInputStatusIndex_input2 5

/* enumerated values for sts58kClockInputState */
#define D_sts58kClockInputState_active 1
#define D_sts58kClockInputState_standby 2
#define D_sts58kClockInputState_down   3
#define D_sts58kClockInputState_recovering 4

/* enumerated values for sts58kClockInputSSMIndex */
#define D_sts58kClockInputSSMIndex_input1 1
#define D_sts58kClockInputSSMIndex_input2 2

/* enumerated values for sts58kClockInputSSMType */
#define D_sts58kClockInputSSMType_e1_sa4_ssm 1
#define D_sts58kClockInputSSMType_e1_sa5_ssm 2
#define D_sts58kClockInputSSMType_e1_sa6_ssm 3
#define D_sts58kClockInputSSMType_e1_sa7_ssm 4
#define D_sts58kClockInputSSMType_e1_sa8_ssm 5
#define D_sts58kClockInputSSMType_t1_ssm 6

/* enumerated values for sts58kClockInputSSMValue */
#define D_sts58kClockInputSSMValue_prs 1
#define D_sts58kClockInputSSMValue_stu 2
#define D_sts58kClockInputSSMValue_st2 3
#define D_sts58kClockInputSSMValue_st3 4
#define D_sts58kClockInputSSMValue_sic 5
#define D_sts58kClockInputSSMValue_duc 6

/* enumerated values for sts58kCardShelf */
#define D_sts58kCardShelf_main         100
#define D_sts58kCardShelf_expansion_1  1
#define D_sts58kCardShelf_expansion_2  2
#define D_sts58kCardShelf_expansion_3  3
#define D_sts58kCardShelf_expansion_4  4

/* enumerated values for sts58kCardIndex */
#define D_sts58kCardIndex_output1      1
#define D_sts58kCardIndex_output2      2
#define D_sts58kCardIndex_output3      3
#define D_sts58kCardIndex_output4      4
#define D_sts58kCardIndex_output5      5
#define D_sts58kCardIndex_output6      6
#define D_sts58kCardIndex_output7      7
#define D_sts58kCardIndex_output8      8
#define D_sts58kCardIndex_output9      9
#define D_sts58kCardIndex_output10     10
#define D_sts58kCardIndex_output11     11
#define D_sts58kCardIndex_output12     12
#define D_sts58kCardIndex_output13     13
#define D_sts58kCardIndex_output14     14
#define D_sts58kCardIndex_output15     15
#define D_sts58kCardIndex_output16     16
#define D_sts58kCardIndex_esr1         17
#define D_sts58kCardIndex_esr2         18
#define D_sts58kCardIndex_smu          19
#define D_sts58kCardIndex_oscillator1  20
#define D_sts58kCardIndex_oscillator2  21
#define D_sts58kCardIndex_top          22
#define D_sts58kCardIndex_imu          23

/* enumerated values for sts58kCardType */
#define D_sts58kCardType_cardTypeSmu   1
#define D_sts58kCardType_cardTypeOutputFrequency 2
#define D_sts58kCardType_cardTypeOutputIrig_B 3
#define D_sts58kCardType_cardTypeOutputTiming 4
#define D_sts58kCardType_cardTypeOutputTiu 5
#define D_sts58kCardType_cardTypeOutputF5F10 6
#define D_sts58kCardType_cardTypeOutputTop 7
#define D_sts58kCardType_cardTypeGpsCdma 8
#define D_sts58kCardType_cardTypeGpsFrequency 9
#define D_sts58kCardType_cardTypeGpsUmts 10
#define D_sts58kCardType_cardTypeGpsGsm 11
#define D_sts58kCardType_cardTypeClkRb 12
#define D_sts58kCardType_cardTypeClkCrystalSt2 13
#define D_sts58kCardType_cardTypeClkCrystalSt3 14
#define D_sts58kCardType_cardTypeClkCrystal 15
#define D_sts58kCardType_cardTypeImu   16

/* enumerated values for sts58kCardOperStatus */
#define D_sts58kCardOperStatus_active  1
#define D_sts58kCardOperStatus_standby 2
#define D_sts58kCardOperStatus_failed  3
#define D_sts58kCardOperStatus_notPresent 4
#define D_sts58kCardOperStatus_misMatch 5

/* enumerated values for sts58kCardReset */
#define D_sts58kCardReset_noAction     1
#define D_sts58kCardReset_reset        2

/* enumerated values for sts58kOscillatorIndex */
#define D_sts58kOscillatorIndex_oscillator1 1
#define D_sts58kOscillatorIndex_oscillator2 2

/* enumerated values for sts58kOscillatorModuleType */
#define D_sts58kOscillatorModuleType_rb 1
#define D_sts58kOscillatorModuleType_crystalSt2 2
#define D_sts58kOscillatorModuleType_crystalSt3 3
#define D_sts58kOscillatorModuleType_crystal 4

/* enumerated values for sts58kOscillatorSetActive */
#define D_sts58kOscillatorSetActive_noAction 1
#define D_sts58kOscillatorSetActive_active 2

/* enumerated values for sts58kOscillatorStatus */
#define D_sts58kOscillatorStatus_active 1
#define D_sts58kOscillatorStatus_standby 2
#define D_sts58kOscillatorStatus_holdoversync 3
#define D_sts58kOscillatorStatus_aqrsync 4
#define D_sts58kOscillatorStatus_frngsync 5
#define D_sts58kOscillatorStatus_lkdsync 6
#define D_sts58kOscillatorStatus_absent 7

/* enumerated values for sts58kGpsIndex */
#define D_sts58kGpsIndex_esr1          1
#define D_sts58kGpsIndex_esr2          2

/* enumerated values for sts58kGpsStatus */
#define D_sts58kGpsStatus_active       1
#define D_sts58kGpsStatus_standby      2

/* enumerated values for sts58kGpsReset */
#define D_sts58kGpsReset_noAction      0
#define D_sts58kGpsReset_reset         1

/* enumerated values for sts58kLinkIndex */
#define D_sts58kLinkIndex_mon1         1
#define D_sts58kLinkIndex_mon2         2
#define D_sts58kLinkIndex_mon3         3
#define D_sts58kLinkIndex_mon4         4
#define D_sts58kLinkIndex_mon5         5

/* enumerated values for sts58kLinkType */
#define D_sts58kLinkType_e1            1
#define D_sts58kLinkType_t1            2
#define D_sts58kLinkType_cc            3
#define D_sts58kLinkType_f2            4
#define D_sts58kLinkType_j1            5

/* enumerated values for sts58kLinkEnable */
#define D_sts58kLinkEnable_yes         1
#define D_sts58kLinkEnable_no          2

/* enumerated values for sts58kLinkLineCode */
#define D_sts58kLinkLineCode_ami       1
#define D_sts58kLinkLineCode_b8zs      2
#define D_sts58kLinkLineCode_hdb3      3
#define D_sts58kLinkLineCode_zbtsi     4
#define D_sts58kLinkLineCode_jbzs      5
#define D_sts58kLinkLineCode_other     6

/* enumerated values for sts58kLinkFMT */
#define D_sts58kLinkFMT_t1_d4          1
#define D_sts58kLinkFMT_t1_esf         2
#define D_sts58kLinkFMT_j1_d4          3
#define D_sts58kLinkFMT_j1_esf         4
#define D_sts58kLinkFMT_e1             5
#define D_sts58kLinkFMT_e1_crc         6
#define D_sts58kLinkFMT_e1_mf          7
#define D_sts58kLinkFMT_e1_crc_mf      8
#define D_sts58kLinkFMT_f2             9
#define D_sts58kLinkFMT_cc             10
#define D_sts58kLinkFMT_cc_400         11

/* enumerated values for sts58kLinkTermination */
#define D_sts58kLinkTermination_ohm_75 1
#define D_sts58kLinkTermination_ohm_100 2
#define D_sts58kLinkTermination_ohm_110 3
#define D_sts58kLinkTermination_ohm_120 4

/* enumerated values for sts58kLinkMFCHK */
#define D_sts58kLinkMFCHK_enable       1
#define D_sts58kLinkMFCHK_disable      2

/* enumerated values for sts58kShelfIndex */
#define D_sts58kShelfIndex_main        100
#define D_sts58kShelfIndex_expansion_1 1
#define D_sts58kShelfIndex_expansion_2 2
#define D_sts58kShelfIndex_expansion_3 3
#define D_sts58kShelfIndex_expansion_4 4

/* enumerated values for sts58kShelfReset */
#define D_sts58kShelfReset_noAction    1
#define D_sts58kShelfReset_reset       2

/* enumerated values for sts58kAlarmThresholdCurrentMon */
#define D_sts58kAlarmThresholdCurrentMon_mon1 1
#define D_sts58kAlarmThresholdCurrentMon_mon2 2
#define D_sts58kAlarmThresholdCurrentMon_mon3 3
#define D_sts58kAlarmThresholdCurrentMon_mon4 4
#define D_sts58kAlarmThresholdCurrentMon_mon5 5

/* enumerated values for sts58kAlarmThresholdType */
#define D_sts58kAlarmThresholdType_cvl 1
#define D_sts58kAlarmThresholdType_cvp 2
#define D_sts58kAlarmThresholdType_cs  3
#define D_sts58kAlarmThresholdType_jitter 4
#define D_sts58kAlarmThresholdType_tie 5
#define D_sts58kAlarmThresholdType_mtie 6
#define D_sts58kAlarmThresholdType_wander 7

/* enumerated values for sts58kAlarmThresholdTimeInterval */
#define D_sts58kAlarmThresholdTimeInterval_one_Sec 1
#define D_sts58kAlarmThresholdTimeInterval_ten_Sec 2
#define D_sts58kAlarmThresholdTimeInterval_hundred_Sec 3
#define D_sts58kAlarmThresholdTimeInterval_thousand_Sec 4
#define D_sts58kAlarmThresholdTimeInterval_tenThousand_Sec 5
#define D_sts58kAlarmThresholdTimeInterval_hundredThousand_Sec 6
#define D_sts58kAlarmThresholdTimeInterval_one_Hour 7
#define D_sts58kAlarmThresholdTimeInterval_one_Day 8

/* enumerated values for sts58kLinkAlarmSettingLinkType */
#define D_sts58kLinkAlarmSettingLinkType_mon1 1
#define D_sts58kLinkAlarmSettingLinkType_mon2 2
#define D_sts58kLinkAlarmSettingLinkType_mon3 3
#define D_sts58kLinkAlarmSettingLinkType_mon4 4
#define D_sts58kLinkAlarmSettingLinkType_mon5 5
#define D_sts58kLinkAlarmSettingLinkType_f5F10 6
#define D_sts58kLinkAlarmSettingLinkType_plnk 7
#define D_sts58kLinkAlarmSettingLinkType_slnk 8

/* enumerated values for sts58kLinkAlarmSettingType */
#define D_sts58kLinkAlarmSettingType_act 1
#define D_sts58kLinkAlarmSettingType_los 2
#define D_sts58kLinkAlarmSettingType_aisp 3
#define D_sts58kLinkAlarmSettingType_lof 4
#define D_sts58kLinkAlarmSettingType_cvl 5
#define D_sts58kLinkAlarmSettingType_cvp 6
#define D_sts58kLinkAlarmSettingType_cs 7
#define D_sts58kLinkAlarmSettingType_jitter 8
#define D_sts58kLinkAlarmSettingType_tie 9
#define D_sts58kLinkAlarmSettingType_mtie 10

/* enumerated values for sts58kLinkAlarmSettingSevirity */
#define D_sts58kLinkAlarmSettingSevirity_cr 1
#define D_sts58kLinkAlarmSettingSevirity_mj 2
#define D_sts58kLinkAlarmSettingSevirity_mn 3
#define D_sts58kLinkAlarmSettingSevirity_na 4
#define D_sts58kLinkAlarmSettingSevirity_nr 5

/* enumerated values for sts58kLinkAlarmSevirity */
#define D_sts58kLinkAlarmSevirity_cr   1
#define D_sts58kLinkAlarmSevirity_mj   2
#define D_sts58kLinkAlarmSevirity_mn   3
#define D_sts58kLinkAlarmSevirity_na   4
#define D_sts58kLinkAlarmSevirity_nr   5
#define D_sts58kLinkAlarmSevirity_cl   6

/* enumerated values for sts58kOscillatorAlarmSettingClock */
#define D_sts58kOscillatorAlarmSettingClock_oscillator1 1
#define D_sts58kOscillatorAlarmSettingClock_oscillator2 2
#define D_sts58kOscillatorAlarmSettingClock_all 3

/* enumerated values for sts58kOscillatorAlarmSettingType */
#define D_sts58kOscillatorAlarmSettingType_aqrsync 1
#define D_sts58kOscillatorAlarmSettingType_frngsync 2
#define D_sts58kOscillatorAlarmSettingType_hldovrsync 3
#define D_sts58kOscillatorAlarmSettingType_lkdsync 4
#define D_sts58kOscillatorAlarmSettingType_act 5

/* enumerated values for sts58kOscillatorAlarmSettingSeverity */
#define D_sts58kOscillatorAlarmSettingSeverity_cr 1
#define D_sts58kOscillatorAlarmSettingSeverity_mj 2
#define D_sts58kOscillatorAlarmSettingSeverity_mn 3
#define D_sts58kOscillatorAlarmSettingSeverity_na 4
#define D_sts58kOscillatorAlarmSettingSeverity_nr 5

/* enumerated values for sts58kOscillatorAlarmSeverity */
#define D_sts58kOscillatorAlarmSeverity_cr 1
#define D_sts58kOscillatorAlarmSeverity_mj 2
#define D_sts58kOscillatorAlarmSeverity_mn 3
#define D_sts58kOscillatorAlarmSeverity_na 4
#define D_sts58kOscillatorAlarmSeverity_nr 5
#define D_sts58kOscillatorAlarmSeverity_cl 6

/* enumerated values for sts58ksPwrAlarmSettingShelf */
#define D_sts58ksPwrAlarmSettingShelf_main 100
#define D_sts58ksPwrAlarmSettingShelf_expansion_1 1
#define D_sts58ksPwrAlarmSettingShelf_expansion_2 2
#define D_sts58ksPwrAlarmSettingShelf_expansion_3 3
#define D_sts58ksPwrAlarmSettingShelf_expansion_4 4

/* enumerated values for sts58kOsPwrAlarmSettingOsPwr */
#define D_sts58kOsPwrAlarmSettingOsPwr_os_oslink_failure 1
#define D_sts58kOsPwrAlarmSettingOsPwr_pwrA_failure 2
#define D_sts58kOsPwrAlarmSettingOsPwr_pwrB_failure 3

/* enumerated values for sts58kOsPwrAlarmSettingSeverity */
#define D_sts58kOsPwrAlarmSettingSeverity_cr 1
#define D_sts58kOsPwrAlarmSettingSeverity_mj 2
#define D_sts58kOsPwrAlarmSettingSeverity_mn 3
#define D_sts58kOsPwrAlarmSettingSeverity_na 4
#define D_sts58kOsPwrAlarmSettingSeverity_nr 5

/* enumerated values for sts58kOsPwrAlarmSeverity */
#define D_sts58kOsPwrAlarmSeverity_cr  1
#define D_sts58kOsPwrAlarmSeverity_mj  2
#define D_sts58kOsPwrAlarmSeverity_mn  3
#define D_sts58kOsPwrAlarmSeverity_na  4
#define D_sts58kOsPwrAlarmSeverity_nr  5
#define D_sts58kOsPwrAlarmSeverity_cl  6

/* enumerated values for sts58kOutputAlarmSettingShelf */
#define D_sts58kOutputAlarmSettingShelf_main 100
#define D_sts58kOutputAlarmSettingShelf_expansion_1 1
#define D_sts58kOutputAlarmSettingShelf_expansion_2 2
#define D_sts58kOutputAlarmSettingShelf_expansion_3 3
#define D_sts58kOutputAlarmSettingShelf_expansion_4 4

/* enumerated values for sts58kOutputAlarmSettingType */
#define D_sts58kOutputAlarmSettingType_lossClock 1
#define D_sts58kOutputAlarmSettingType_tiu_act 2
#define D_sts58kOutputAlarmSettingType_tiu_los 3
#define D_sts58kOutputAlarmSettingType_tiu_t_tie 4
#define D_sts58kOutputAlarmSettingType_tiu_t_mtie 5
#define D_sts58kOutputAlarmSettingType_tiu_aisp 6
#define D_sts58kOutputAlarmSettingType_tiu_lof 7
#define D_sts58kOutputAlarmSettingType_tiu_t_cs 8

/* enumerated values for sts58kOutputAlarmSettingSeverity */
#define D_sts58kOutputAlarmSettingSeverity_cr 1
#define D_sts58kOutputAlarmSettingSeverity_mj 2
#define D_sts58kOutputAlarmSettingSeverity_mn 3
#define D_sts58kOutputAlarmSettingSeverity_na 4
#define D_sts58kOutputAlarmSettingSeverity_nr 5

/* enumerated values for sts58kOutputAlarmSeverity */
#define D_sts58kOutputAlarmSeverity_cr 1
#define D_sts58kOutputAlarmSeverity_mj 2
#define D_sts58kOutputAlarmSeverity_mn 3
#define D_sts58kOutputAlarmSeverity_na 4
#define D_sts58kOutputAlarmSeverity_nr 5
#define D_sts58kOutputAlarmSeverity_cl 6

/* enumerated values for sts58kOutputTiuSettingShelf */
#define D_sts58kOutputTiuSettingShelf_main 100
#define D_sts58kOutputTiuSettingShelf_expansion_1 1
#define D_sts58kOutputTiuSettingShelf_expansion_2 2
#define D_sts58kOutputTiuSettingShelf_expansion_3 3
#define D_sts58kOutputTiuSettingShelf_expansion_4 4

/* enumerated values for sts58kOutputTiuSettingLineCoding */
#define D_sts58kOutputTiuSettingLineCoding_ami 1
#define D_sts58kOutputTiuSettingLineCoding_b8zs 2
#define D_sts58kOutputTiuSettingLineCoding_hdb3 3
#define D_sts58kOutputTiuSettingLineCoding_other 4

/* enumerated values for sts58kOutputTiuSettingFMT */
#define D_sts58kOutputTiuSettingFMT_t1_d4 1
#define D_sts58kOutputTiuSettingFMT_t1_esf 2
#define D_sts58kOutputTiuSettingFMT_j1_d4 3
#define D_sts58kOutputTiuSettingFMT_j1_esf 4

/* enumerated values for sts58kOutputTiuSettingTermination */
#define D_sts58kOutputTiuSettingTermination_ohm_75 1
#define D_sts58kOutputTiuSettingTermination_ohm_100 2
#define D_sts58kOutputTiuSettingTermination_ohm_110 3
#define D_sts58kOutputTiuSettingTermination_ohm_120 4

/* enumerated values for sts58kPerfMonInputCurrentMon */
#define D_sts58kPerfMonInputCurrentMon_mon1 1
#define D_sts58kPerfMonInputCurrentMon_mon2 2
#define D_sts58kPerfMonInputCurrentMon_mon3 3
#define D_sts58kPerfMonInputCurrentMon_mon4 4
#define D_sts58kPerfMonInputCurrentMon_mon5 5

/* enumerated values for sts58kPerfMonInputMonPeriod */
#define D_sts58kPerfMonInputMonPeriod_one_hour 1
#define D_sts58kPerfMonInputMonPeriod_one_day 2
#define D_sts58kPerfMonInputMonPeriod_hundred_Sec 3

/* enumerated values for sts58kPerfMonInputClockType */
#define D_sts58kPerfMonInputClockType_unknown 1
#define D_sts58kPerfMonInputClockType_t1 2
#define D_sts58kPerfMonInputClockType_e1 3
#define D_sts58kPerfMonInputClockType_cc 4
#define D_sts58kPerfMonInputClockType_f2 5
#define D_sts58kPerfMonInputClockType_f5 6
#define D_sts58kPerfMonInputClockType_f10 7

/* enumerated values for sts58kAlarmSource */
#define D_sts58kAlarmSource_clk1       1
#define D_sts58kAlarmSource_clk2       2
#define D_sts58kAlarmSource_pwr        3
#define D_sts58kAlarmSource_os         4
#define D_sts58kAlarmSource_plnk       5
#define D_sts58kAlarmSource_slnk       6
#define D_sts58kAlarmSource_f10        7
#define D_sts58kAlarmSource_mon1       8
#define D_sts58kAlarmSource_mon2       9
#define D_sts58kAlarmSource_mon3       10
#define D_sts58kAlarmSource_mon4       11
#define D_sts58kAlarmSource_mon5       12
#define D_sts58kAlarmSource_esr1       13
#define D_sts58kAlarmSource_esr2       14

/* enumerated values for sts58kAlarmSourceType */
#define D_sts58kAlarmSourceType_eqpt   1
#define D_sts58kAlarmSourceType_link   2
#define D_sts58kAlarmSourceType_com    3

/* enumerated values for sts58kAlarmSeverity */
#define D_sts58kAlarmSeverity_cr       1
#define D_sts58kAlarmSeverity_mj       2
#define D_sts58kAlarmSeverity_mn       3
#define D_sts58kAlarmSeverity_na       4
#define D_sts58kAlarmSeverity_nr       5
#define D_sts58kAlarmSeverity_cl       6

/* enumerated values for sts58kAlarmSrvEff */
#define D_sts58kAlarmSrvEff_sa         1
#define D_sts58kAlarmSrvEff_nsa        2

/* enumerated values for sts58kOutputShelf */
#define D_sts58kOutputShelf_main       100
#define D_sts58kOutputShelf_expansion_1 1
#define D_sts58kOutputShelf_expansion_2 2
#define D_sts58kOutputShelf_expansion_3 3
#define D_sts58kOutputShelf_expansion_4 4

/* enumerated values for sts58kOutputRedState */
#define D_sts58kOutputRedState_active  1
#define D_sts58kOutputRedState_standby 2

/* enumerated values for sts58kOutputRedSwitchState */
#define D_sts58kOutputRedSwitchState_noAction 0
#define D_sts58kOutputRedSwitchState_active 1
#define D_sts58kOutputRedSwitchState_standby 2

/* enumerated values for sts58kOutputCRCCHK */
#define D_sts58kOutputCRCCHK_enable    1
#define D_sts58kOutputCRCCHK_disable   2

/* enumerated values for sts58kOutputCAS */
#define D_sts58kOutputCAS_enable       1
#define D_sts58kOutputCAS_disable      2

/* enumerated values for sts58kOutputSSM */
#define D_sts58kOutputSSM_sa4          1
#define D_sts58kOutputSSM_sa5          2
#define D_sts58kOutputSSM_sa6          3
#define D_sts58kOutputSSM_sa7          4
#define D_sts58kOutputSSM_sa8          5

/* enumerated values for sts58kOutputSSMValue */
#define D_sts58kOutputSSMValue_prs     1
#define D_sts58kOutputSSMValue_stu     2
#define D_sts58kOutputSSMValue_st2     3
#define D_sts58kOutputSSMValue_st3     4
#define D_sts58kOutputSSMValue_sic     5
#define D_sts58kOutputSSMValue_duc     6

/* enumerated values for sts58kEmmShelf */
#define D_sts58kEmmShelf_main          100
#define D_sts58kEmmShelf_expansion_1   1
#define D_sts58kEmmShelf_expansion_2   2
#define D_sts58kEmmShelf_expansion_3   3

/* enumerated values for sts58kEmmSensorType */
#define D_sts58kEmmSensorType_temp_celsius 1
#define D_sts58kEmmSensorType_voltage_mvolt 2

/* enumerated values for sts58kEmmAlarmStatus */
#define D_sts58kEmmAlarmStatus_cr      1
#define D_sts58kEmmAlarmStatus_mj      2
#define D_sts58kEmmAlarmStatus_mn      3
#define D_sts58kEmmAlarmStatus_na      4
#define D_sts58kEmmAlarmStatus_nr      5
#define D_sts58kEmmAlarmStatus_cl      6

/* enumerated values for sts58kAntStatus */
#define D_sts58kAntStatus_active       1
#define D_sts58kAntStatus_standby      2
#define D_sts58kAntStatus_failure      3
#define D_sts58kAntStatus_absent       4

/* enumerated values for sts58kAntSwitchState */
#define D_sts58kAntSwitchState_noAction 0
#define D_sts58kAntSwitchState_active  1
#define D_sts58kAntSwitchState_standby 2

/* enumerated values for sts58kTrapRegState */
#define D_sts58kTrapRegState_enabled   1
#define D_sts58kTrapRegState_disabled  2


#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_LARUS58KDEFS_H */
