/*
 *
 * Copyright (C) 1992-2003 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -o snmp -separate_type_file 
 */

/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_SNMPPROT_H
#define SR_SNMPPROT_H


#ifdef __cplusplus
extern "C" {
#endif

#include "sr_proto.h"

extern int k_initialize
    SR_PROTOTYPE((void));

extern int k_terminate
    SR_PROTOTYPE((void));


/*
 * The system family. 
 */

extern VarBind * system_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern system_t *new_k_system_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  system_t *systemData));

extern system_t *k_system_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator));



/*
 * The sts58kSystem family. 
 */

extern VarBind * sts58kSystem_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kSystem_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kSystem_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kSystem_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kSystem_free
    SR_PROTOTYPE((sts58kSystem_t *data));

extern sts58kSystem_t *new_k_sts58kSystem_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kSystem_t *sts58kSystemData));

extern sts58kSystem_t *k_sts58kSystem_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator));

extern int k_sts58kSystem_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kSystem_set
    SR_PROTOTYPE((sts58kSystem_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kSystem_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kSystem_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kSystem_t *Clone_sts58kSystem
    SR_PROTOTYPE((sts58kSystem_t *data));



/*
 * The sts58kClockInput family. 
 */

extern VarBind * sts58kClockInput_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kClockInput_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kClockInput_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kClockInput_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kClockInput_free
    SR_PROTOTYPE((sts58kClockInput_t *data));

extern sts58kClockInput_t *new_k_sts58kClockInput_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kClockInput_t *sts58kClockInputData));

extern sts58kClockInput_t *k_sts58kClockInput_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator));

extern int k_sts58kClockInput_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kClockInput_set
    SR_PROTOTYPE((sts58kClockInput_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kClockInput_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kClockInput_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kClockInput_t *Clone_sts58kClockInput
    SR_PROTOTYPE((sts58kClockInput_t *data));



/*
 * The sts58kClockInputSSM family. 
 */

extern VarBind * sts58kClockInputSSM_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kClockInputSSM_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kClockInputSSM_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kClockInputSSM_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kClockInputSSM_free
    SR_PROTOTYPE((sts58kClockInputSSM_t *data));

extern sts58kClockInputSSM_t *new_k_sts58kClockInputSSM_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kClockInputSSM_t *sts58kClockInputSSMData));

extern sts58kClockInputSSM_t *k_sts58kClockInputSSM_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator));

extern int k_sts58kClockInputSSM_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kClockInputSSM_set
    SR_PROTOTYPE((sts58kClockInputSSM_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kClockInputSSM_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kClockInputSSM_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kClockInputSSM_t *Clone_sts58kClockInputSSM
    SR_PROTOTYPE((sts58kClockInputSSM_t *data));



/*
 * The sts58kTop family. 
 */

extern VarBind * sts58kTop_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kTop_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kTop_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kTop_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kTop_free
    SR_PROTOTYPE((sts58kTop_t *data));

extern sts58kTop_t *new_k_sts58kTop_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kTop_t *sts58kTopData));

extern sts58kTop_t *k_sts58kTop_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator));

extern int k_sts58kTop_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kTop_set
    SR_PROTOTYPE((sts58kTop_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kTop_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kTop_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kTop_t *Clone_sts58kTop
    SR_PROTOTYPE((sts58kTop_t *data));



/*
 * The sts58kClockInputStatusEntry family. 
 */

extern VarBind * sts58kClockInputStatusEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern sts58kClockInputStatusEntry_t *new_k_sts58kClockInputStatusEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kClockInputStatusEntry_t *sts58kClockInputStatusEntryData));

extern sts58kClockInputStatusEntry_t *k_sts58kClockInputStatusEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kClockInputStatusIndex));



/*
 * The sts58kClockInputSSMEntry family. 
 */

extern VarBind * sts58kClockInputSSMEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern sts58kClockInputSSMEntry_t *new_k_sts58kClockInputSSMEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kClockInputSSMEntry_t *sts58kClockInputSSMEntryData));

extern sts58kClockInputSSMEntry_t *k_sts58kClockInputSSMEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kClockInputSSMIndex,
                  SR_INT32 sts58kClockInputSSMType));



/*
 * The sts58kCardEntry family. 
 */

extern VarBind * sts58kCardEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kCardEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kCardEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kCardEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kCardEntry_free
    SR_PROTOTYPE((sts58kCardEntry_t *data));

extern sts58kCardEntry_t *new_k_sts58kCardEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kCardEntry_t *sts58kCardEntryData));

extern sts58kCardEntry_t *k_sts58kCardEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kCardShelf,
                  SR_INT32 sts58kCardIndex));

extern int k_sts58kCardEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kCardEntry_set
    SR_PROTOTYPE((sts58kCardEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kCardEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kCardEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kCardEntry_t *Clone_sts58kCardEntry
    SR_PROTOTYPE((sts58kCardEntry_t *data));

extern int k_sts58kCardEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kOscillatorEntry family. 
 */

extern VarBind * sts58kOscillatorEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kOscillatorEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOscillatorEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOscillatorEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kOscillatorEntry_free
    SR_PROTOTYPE((sts58kOscillatorEntry_t *data));

extern sts58kOscillatorEntry_t *new_k_sts58kOscillatorEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kOscillatorEntry_t *sts58kOscillatorEntryData));

extern sts58kOscillatorEntry_t *k_sts58kOscillatorEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kOscillatorIndex));

extern int k_sts58kOscillatorEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kOscillatorEntry_set
    SR_PROTOTYPE((sts58kOscillatorEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kOscillatorEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kOscillatorEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kOscillatorEntry_t *Clone_sts58kOscillatorEntry
    SR_PROTOTYPE((sts58kOscillatorEntry_t *data));

extern int k_sts58kOscillatorEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kGpsEntry family. 
 */

extern VarBind * sts58kGpsEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kGpsEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kGpsEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kGpsEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kGpsEntry_free
    SR_PROTOTYPE((sts58kGpsEntry_t *data));

extern sts58kGpsEntry_t *new_k_sts58kGpsEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kGpsEntry_t *sts58kGpsEntryData));

extern sts58kGpsEntry_t *k_sts58kGpsEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kGpsIndex));

extern int k_sts58kGpsEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kGpsEntry_set
    SR_PROTOTYPE((sts58kGpsEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kGpsEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kGpsEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kGpsEntry_t *Clone_sts58kGpsEntry
    SR_PROTOTYPE((sts58kGpsEntry_t *data));

extern int k_sts58kGpsEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kLinkEntry family. 
 */

extern VarBind * sts58kLinkEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kLinkEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kLinkEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kLinkEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kLinkEntry_free
    SR_PROTOTYPE((sts58kLinkEntry_t *data));

extern sts58kLinkEntry_t *new_k_sts58kLinkEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kLinkEntry_t *sts58kLinkEntryData));

extern sts58kLinkEntry_t *k_sts58kLinkEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kLinkIndex));

extern int k_sts58kLinkEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kLinkEntry_set
    SR_PROTOTYPE((sts58kLinkEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kLinkEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kLinkEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kLinkEntry_t *Clone_sts58kLinkEntry
    SR_PROTOTYPE((sts58kLinkEntry_t *data));

extern int k_sts58kLinkEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kShelfEntry family. 
 */

extern VarBind * sts58kShelfEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kShelfEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kShelfEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kShelfEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kShelfEntry_free
    SR_PROTOTYPE((sts58kShelfEntry_t *data));

extern sts58kShelfEntry_t *new_k_sts58kShelfEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kShelfEntry_t *sts58kShelfEntryData));

extern sts58kShelfEntry_t *k_sts58kShelfEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kShelfIndex));

extern int k_sts58kShelfEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kShelfEntry_set
    SR_PROTOTYPE((sts58kShelfEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kShelfEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kShelfEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kShelfEntry_t *Clone_sts58kShelfEntry
    SR_PROTOTYPE((sts58kShelfEntry_t *data));

extern int k_sts58kShelfEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kAlarmThresholdEntry family. 
 */

extern VarBind * sts58kAlarmThresholdEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kAlarmThresholdEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kAlarmThresholdEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kAlarmThresholdEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kAlarmThresholdEntry_free
    SR_PROTOTYPE((sts58kAlarmThresholdEntry_t *data));

extern sts58kAlarmThresholdEntry_t *new_k_sts58kAlarmThresholdEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kAlarmThresholdEntry_t *sts58kAlarmThresholdEntryData));

extern sts58kAlarmThresholdEntry_t *k_sts58kAlarmThresholdEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kAlarmThresholdCurrentMon,
                  SR_INT32 sts58kAlarmThresholdType));

extern int k_sts58kAlarmThresholdEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kAlarmThresholdEntry_set
    SR_PROTOTYPE((sts58kAlarmThresholdEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kAlarmThresholdEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kAlarmThresholdEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kAlarmThresholdEntry_t *Clone_sts58kAlarmThresholdEntry
    SR_PROTOTYPE((sts58kAlarmThresholdEntry_t *data));

extern int k_sts58kAlarmThresholdEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kLinkAlarmEntry family. 
 */

extern VarBind * sts58kLinkAlarmEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kLinkAlarmEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kLinkAlarmEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kLinkAlarmEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kLinkAlarmEntry_free
    SR_PROTOTYPE((sts58kLinkAlarmEntry_t *data));

extern sts58kLinkAlarmEntry_t *new_k_sts58kLinkAlarmEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kLinkAlarmEntry_t *sts58kLinkAlarmEntryData));

extern sts58kLinkAlarmEntry_t *k_sts58kLinkAlarmEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kLinkAlarmSettingLinkType,
                  SR_INT32 sts58kLinkAlarmSettingType));

extern int k_sts58kLinkAlarmEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kLinkAlarmEntry_set
    SR_PROTOTYPE((sts58kLinkAlarmEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kLinkAlarmEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kLinkAlarmEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kLinkAlarmEntry_t *Clone_sts58kLinkAlarmEntry
    SR_PROTOTYPE((sts58kLinkAlarmEntry_t *data));

extern int k_sts58kLinkAlarmEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kOscillatorAlarmEntry family. 
 */

extern VarBind * sts58kOscillatorAlarmEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kOscillatorAlarmEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOscillatorAlarmEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOscillatorAlarmEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kOscillatorAlarmEntry_free
    SR_PROTOTYPE((sts58kOscillatorAlarmEntry_t *data));

extern sts58kOscillatorAlarmEntry_t *new_k_sts58kOscillatorAlarmEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kOscillatorAlarmEntry_t *sts58kOscillatorAlarmEntryData));

extern sts58kOscillatorAlarmEntry_t *k_sts58kOscillatorAlarmEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kOscillatorAlarmSettingClock,
                  SR_INT32 sts58kOscillatorAlarmSettingType));

extern int k_sts58kOscillatorAlarmEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kOscillatorAlarmEntry_set
    SR_PROTOTYPE((sts58kOscillatorAlarmEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kOscillatorAlarmEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kOscillatorAlarmEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kOscillatorAlarmEntry_t *Clone_sts58kOscillatorAlarmEntry
    SR_PROTOTYPE((sts58kOscillatorAlarmEntry_t *data));

extern int k_sts58kOscillatorAlarmEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kOsPwrAlarmEntry family. 
 */

extern VarBind * sts58kOsPwrAlarmEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kOsPwrAlarmEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOsPwrAlarmEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOsPwrAlarmEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kOsPwrAlarmEntry_free
    SR_PROTOTYPE((sts58kOsPwrAlarmEntry_t *data));

extern sts58kOsPwrAlarmEntry_t *new_k_sts58kOsPwrAlarmEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kOsPwrAlarmEntry_t *sts58kOsPwrAlarmEntryData));

extern sts58kOsPwrAlarmEntry_t *k_sts58kOsPwrAlarmEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58ksPwrAlarmSettingShelf,
                  SR_INT32 sts58kOsPwrAlarmSettingOsPwr));

extern int k_sts58kOsPwrAlarmEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kOsPwrAlarmEntry_set
    SR_PROTOTYPE((sts58kOsPwrAlarmEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kOsPwrAlarmEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kOsPwrAlarmEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kOsPwrAlarmEntry_t *Clone_sts58kOsPwrAlarmEntry
    SR_PROTOTYPE((sts58kOsPwrAlarmEntry_t *data));

extern int k_sts58kOsPwrAlarmEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kOutputAlarmEntry family. 
 */

extern VarBind * sts58kOutputAlarmEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kOutputAlarmEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOutputAlarmEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOutputAlarmEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kOutputAlarmEntry_free
    SR_PROTOTYPE((sts58kOutputAlarmEntry_t *data));

extern sts58kOutputAlarmEntry_t *new_k_sts58kOutputAlarmEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kOutputAlarmEntry_t *sts58kOutputAlarmEntryData));

extern sts58kOutputAlarmEntry_t *k_sts58kOutputAlarmEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kOutputAlarmSettingShelf,
                  SR_INT32 sts58kOutputAlarmSettingSlot,
                  SR_INT32 sts58kOutputAlarmSettingPort,
                  SR_INT32 sts58kOutputAlarmSettingType));

extern int k_sts58kOutputAlarmEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kOutputAlarmEntry_set
    SR_PROTOTYPE((sts58kOutputAlarmEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kOutputAlarmEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kOutputAlarmEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kOutputAlarmEntry_t *Clone_sts58kOutputAlarmEntry
    SR_PROTOTYPE((sts58kOutputAlarmEntry_t *data));

extern int k_sts58kOutputAlarmEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kOutputTiuSettingEntry family. 
 */

extern VarBind * sts58kOutputTiuSettingEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kOutputTiuSettingEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOutputTiuSettingEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOutputTiuSettingEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kOutputTiuSettingEntry_free
    SR_PROTOTYPE((sts58kOutputTiuSettingEntry_t *data));

extern sts58kOutputTiuSettingEntry_t *new_k_sts58kOutputTiuSettingEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kOutputTiuSettingEntry_t *sts58kOutputTiuSettingEntryData));

extern sts58kOutputTiuSettingEntry_t *k_sts58kOutputTiuSettingEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kOutputTiuSettingShelf,
                  SR_INT32 sts58kOutputTiuSettingSlot,
                  SR_INT32 sts58kOutputTiuSettingPort));

extern int k_sts58kOutputTiuSettingEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kOutputTiuSettingEntry_set
    SR_PROTOTYPE((sts58kOutputTiuSettingEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kOutputTiuSettingEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kOutputTiuSettingEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kOutputTiuSettingEntry_t *Clone_sts58kOutputTiuSettingEntry
    SR_PROTOTYPE((sts58kOutputTiuSettingEntry_t *data));

extern int k_sts58kOutputTiuSettingEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kPerfMonEntry family. 
 */

extern VarBind * sts58kPerfMonEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern sts58kPerfMonEntry_t *new_k_sts58kPerfMonEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kPerfMonEntry_t *sts58kPerfMonEntryData));

extern sts58kPerfMonEntry_t *k_sts58kPerfMonEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kPerfMonInputCurrentMon,
                  SR_INT32 sts58kPerfMonInputMonPeriod,
                  SR_INT32 sts58kPerfMonInputMonBucket));



/*
 * The sts58kAlarmStatusEntry family. 
 */

extern VarBind * sts58kAlarmStatusEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern sts58kAlarmStatusEntry_t *new_k_sts58kAlarmStatusEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kAlarmStatusEntry_t *sts58kAlarmStatusEntryData));

extern sts58kAlarmStatusEntry_t *k_sts58kAlarmStatusEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kAlarmSource));



/*
 * The sts58kOutputCardEntry family. 
 */

extern VarBind * sts58kOutputCardEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kOutputCardEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOutputCardEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kOutputCardEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kOutputCardEntry_free
    SR_PROTOTYPE((sts58kOutputCardEntry_t *data));

extern sts58kOutputCardEntry_t *new_k_sts58kOutputCardEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kOutputCardEntry_t *sts58kOutputCardEntryData));

extern sts58kOutputCardEntry_t *k_sts58kOutputCardEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kOutputShelf,
                  SR_INT32 sts58kOutputSlot));

extern int k_sts58kOutputCardEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kOutputCardEntry_set
    SR_PROTOTYPE((sts58kOutputCardEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kOutputCardEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kOutputCardEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kOutputCardEntry_t *Clone_sts58kOutputCardEntry
    SR_PROTOTYPE((sts58kOutputCardEntry_t *data));

extern int k_sts58kOutputCardEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kEmmStatusEntry family. 
 */

extern VarBind * sts58kEmmStatusEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kEmmStatusEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kEmmStatusEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kEmmStatusEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kEmmStatusEntry_free
    SR_PROTOTYPE((sts58kEmmStatusEntry_t *data));

extern sts58kEmmStatusEntry_t *new_k_sts58kEmmStatusEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kEmmStatusEntry_t *sts58kEmmStatusEntryData));

extern sts58kEmmStatusEntry_t *k_sts58kEmmStatusEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kEmmShelf,
                  SR_INT32 sts58kEmmUnitId));

extern int k_sts58kEmmStatusEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kEmmStatusEntry_set
    SR_PROTOTYPE((sts58kEmmStatusEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kEmmStatusEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kEmmStatusEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kEmmStatusEntry_t *Clone_sts58kEmmStatusEntry
    SR_PROTOTYPE((sts58kEmmStatusEntry_t *data));

extern int k_sts58kEmmStatusEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kAntEntry family. 
 */

extern VarBind * sts58kAntEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kAntEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kAntEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kAntEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kAntEntry_free
    SR_PROTOTYPE((sts58kAntEntry_t *data));

extern sts58kAntEntry_t *new_k_sts58kAntEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kAntEntry_t *sts58kAntEntryData));

extern sts58kAntEntry_t *k_sts58kAntEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kAntIndex));

extern int k_sts58kAntEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kAntEntry_set
    SR_PROTOTYPE((sts58kAntEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kAntEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kAntEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kAntEntry_t *Clone_sts58kAntEntry
    SR_PROTOTYPE((sts58kAntEntry_t *data));

extern int k_sts58kAntEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kTopDestEntry family. 
 */

extern VarBind * sts58kTopDestEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kTopDestEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kTopDestEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kTopDestEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kTopDestEntry_free
    SR_PROTOTYPE((sts58kTopDestEntry_t *data));

extern sts58kTopDestEntry_t *new_k_sts58kTopDestEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kTopDestEntry_t *sts58kTopDestEntryData));

extern sts58kTopDestEntry_t *k_sts58kTopDestEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kTopDestNumber));

extern int k_sts58kTopDestEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kTopDestEntry_set
    SR_PROTOTYPE((sts58kTopDestEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kTopDestEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kTopDestEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kTopDestEntry_t *Clone_sts58kTopDestEntry
    SR_PROTOTYPE((sts58kTopDestEntry_t *data));

extern int k_sts58kTopDestEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



/*
 * The sts58kTrapRegEntry family. 
 */

extern VarBind * sts58kTrapRegEntry_get
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  int searchType,
                  ContextInfo *contextInfo,
                  int serialNum));

extern int sts58kTrapRegEntry_test
    SR_PROTOTYPE((OID *incoming,
                  ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kTrapRegEntry_ready
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern int sts58kTrapRegEntry_set
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern void sts58kTrapRegEntry_free
    SR_PROTOTYPE((sts58kTrapRegEntry_t *data));

extern sts58kTrapRegEntry_t *new_k_sts58kTrapRegEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  sts58kTrapRegEntry_t *sts58kTrapRegEntryData));

extern sts58kTrapRegEntry_t *k_sts58kTrapRegEntry_get
    SR_PROTOTYPE((int serialNum,
                  ContextInfo *contextInfo,
                  int nominator,
                  int searchType,
                  SR_INT32 sts58kTrapRegMgrNumber));

extern int k_sts58kTrapRegEntry_test
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *dp,
                  ContextInfo *contextInfo));

extern int k_sts58kTrapRegEntry_set
    SR_PROTOTYPE((sts58kTrapRegEntry_t *data,
                  ContextInfo *contextInfo,
                  int function));

extern int k_sts58kTrapRegEntry_ready
    SR_PROTOTYPE((ObjectInfo *object,
                  ObjectSyntax *value,
                  doList_t *doHead,
                  doList_t *dp));

extern int sts58kTrapRegEntry_undo
    SR_PROTOTYPE((doList_t *doHead,
                  doList_t *doCur,
                  ContextInfo *contextInfo));

extern sts58kTrapRegEntry_t *Clone_sts58kTrapRegEntry
    SR_PROTOTYPE((sts58kTrapRegEntry_t *data));

extern int k_sts58kTrapRegEntry_set_defaults
    SR_PROTOTYPE((doList_t *dp));



#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_SNMPPROT_H */
