/*
 *
 * Copyright (C) 1992-2003 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -o snmp -separate_type_file 
 */

/*
 * If your implementation does NOT support a MIB variable, add a line in
 * the undefs.h file containing #undef I_that-variable-name.  For example,
 * if you do not support the sysDescr variable in the system family
 * add a line:
 *
 * #undef I_sysDescr
 *
 *
 */


/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_SNMPSUPP_H
#define SR_SNMPSUPP_H


#ifdef __cplusplus
extern "C" {
#endif

#define I_sysDescr                                          0
#define I_sysObjectID                                       1
#define I_system_max                                        1

#define I_sts58kSystemId                                    0
#define I_sts58kSystemMgmtIpOption                          1
#define I_sts58kSystemMgmtIpAddress                         2
#define I_sts58kSystemMgmtIpSubnetMask                      3
#define I_sts58kSystemMgmtIpGatewayAddress                  4
#define I_sts58kSystemSntpIpOption                          5
#define I_sts58kSystemSntpIpAddress                         6
#define I_sts58kSystemSntpIpSubnetMask                      7
#define I_sts58kSystemSntpIpGatewayAddress                  8
#define I_sts58kSystemTime                                  9
#define I_sts58kSystemTimeZone                              10
#define I_sts58kSystemIntegratedAlarm                       11
#define I_sts58kSystemAlarmAcoMode                          12
#define I_sts58kSystemAlarmAcoLed                           13
#define I_sts58kSystemAlarmAcoCutOff                        14
#define I_sts58kSystemAlarmEscalatingTime                   15
#define I_sts58kSystemMinorLED                              16
#define I_sts58kSystemMajorLED                              17
#define I_sts58kSystemCriticalLED                           18
#define I_sts58kSystemUpgradeSWAction                       19
#define I_sts58kSystemCurrentSWVersion                      20
#define I_sts58kSystemServiceState                          21
#define I_sts58kSystemWarmReset                             22
#define I_sts58kSystemColdReset                             23
#define I_sts58kSystemConfigReset                           24
#define I_sts58kSystem_max                                  24

#define I_sts58kClockInputManualSelect                      0
#define I_sts58kClockInputOperMode                          1
#define I_sts58kClockInputProtectedPri                      2
#define I_sts58kClockInputSetSlip                           3
#define I_sts58kClockInputType                              4
#define I_sts58kClockInput_max                              4

#define I_sts58kClockInputSSMSelect                         0
#define I_sts58kClockInputSSM_max                           0

#define I_sts58kTopSourceIpOption                           0
#define I_sts58kTopSourceIpAddress                          1
#define I_sts58kTopSourceIpSubnetMask                       2
#define I_sts58kTopSourceIpGatewayAddress                   3
#define I_sts58kTopPacketRate                               4
#define I_sts58kTopInputSelect                              5
#define I_sts58kTopTxPackets                                6
#define I_sts58kTopTxBytes                                  7
#define I_sts58kTop_max                                     7

#define I_sts58kClockInputStatusIndex                       0
#define I_sts58kClockInputState                             1
#define I_sts58kClockInputStatusEntry_max                   1

#define I_sts58kClockInputSSMIndex                          0
#define I_sts58kClockInputSSMType                           1
#define I_sts58kClockInputSSMValue                          2
#define I_sts58kClockInputSSMEntry_max                      2

#define I_sts58kCardShelf                                   0
#define I_sts58kCardIndex                                   1
#define I_sts58kCardType                                    2
#define I_sts58kCardDescr                                   3
#define I_sts58kCardSerial                                  4
#define I_sts58kCardHwVersion                               5
#define I_sts58kCardCLEICode                                6
#define I_sts58kCardOperStatus                              7
#define I_sts58kCardReset                                   8
#define I_sts58kCardEntry_max                               8

#define I_sts58kOscillatorIndex                             0
#define I_sts58kOscillatorModuleType                        1
#define I_sts58kOscillatorEFER                              2
#define I_sts58kOscillatorESSD                              3
#define I_sts58kOscillatorESSN                              4
#define I_sts58kOscillatorFAGE                              5
#define I_sts58kOscillatorTIMD                              6
#define I_sts58kOscillatorSetActive                         7
#define I_sts58kOscillatorStatus                            8
#define I_sts58kOscillatorEntry_max                         8

#define I_sts58kGpsIndex                                    0
#define I_sts58kGpsStatus                                   1
#define I_sts58kGpsANTD                                     2
#define I_sts58kGpsAZEL                                     3
#define I_sts58kGpsRSTG                                     4
#define I_sts58kGpsBITS                                     5
#define I_sts58kGpsPAVG                                     6
#define I_sts58kGpsSIGQ                                     7
#define I_sts58kGpsSPOS                                     8
#define I_sts58kGpsTRMO                                     9
#define I_sts58kGpsUTCT                                     10
#define I_sts58kGpsVERS                                     11
#define I_sts58kGpsDETF                                     12
#define I_sts58kGpsEFER                                     13
#define I_sts58kGpsESSD                                     14
#define I_sts58kGpsESSN                                     15
#define I_sts58kGpsFAGE                                     16
#define I_sts58kGpsTIMD                                     17
#define I_sts58kGpsReset                                    18
#define I_sts58kGpsEntry_max                                18

#define I_sts58kLinkIndex                                   0
#define I_sts58kLinkType                                    1
#define I_sts58kLinkEnable                                  2
#define I_sts58kLinkLineCode                                3
#define I_sts58kLinkFMT                                     4
#define I_sts58kLinkTermination                             5
#define I_sts58kLinkMFCHK                                   6
#define I_sts58kLinkId                                      7
#define I_sts58kLinkEntry_max                               7

#define I_sts58kShelfIndex                                  0
#define I_sts58kShelfSerial                                 1
#define I_sts58kShelfCLEICode                               2
#define I_sts58kShelfReset                                  3
#define I_sts58kShelfEntry_max                              3

#define I_sts58kAlarmThresholdCurrentMon                    0
#define I_sts58kAlarmThresholdType                          1
#define I_sts58kAlarmThresholdValue                         2
#define I_sts58kAlarmThresholdTimeInterval                  3
#define I_sts58kAlarmThresholdEntry_max                     3

#define I_sts58kLinkAlarmSettingLinkType                    0
#define I_sts58kLinkAlarmSettingType                        1
#define I_sts58kLinkAlarmSettingSevirity                    2
#define I_sts58kLinkAlarmSevirity                           3
#define I_sts58kLinkAlarmEntry_max                          3

#define I_sts58kOscillatorAlarmSettingClock                 0
#define I_sts58kOscillatorAlarmSettingType                  1
#define I_sts58kOscillatorAlarmSettingSeverity              2
#define I_sts58kOscillatorAlarmSeverity                     3
#define I_sts58kOscillatorAlarmEntry_max                    3

#define I_sts58ksPwrAlarmSettingShelf                       0
#define I_sts58kOsPwrAlarmSettingOsPwr                      1
#define I_sts58kOsPwrAlarmSettingSeverity                   2
#define I_sts58kOsPwrAlarmSeverity                          3
#define I_sts58kOsPwrAlarmEntry_max                         3

#define I_sts58kOutputAlarmSettingShelf                     0
#define I_sts58kOutputAlarmSettingSlot                      1
#define I_sts58kOutputAlarmSettingPort                      2
#define I_sts58kOutputAlarmSettingType                      3
#define I_sts58kOutputAlarmSettingSeverity                  4
#define I_sts58kOutputAlarmSeverity                         5
#define I_sts58kOutputAlarmEntry_max                        5

#define I_sts58kOutputTiuSettingShelf                       0
#define I_sts58kOutputTiuSettingSlot                        1
#define I_sts58kOutputTiuSettingPort                        2
#define I_sts58kOutputTiuSettingLineCoding                  3
#define I_sts58kOutputTiuSettingFMT                         4
#define I_sts58kOutputTiuSettingTermination                 5
#define I_sts58kOutputTiuSettingEntry_max                   5

#define I_sts58kPerfMonInputCurrentMon                      0
#define I_sts58kPerfMonInputMonPeriod                       1
#define I_sts58kPerfMonInputMonBucket                       2
#define I_sts58kPerfMonInputClockType                       3
#define I_sts58kPerfMonPerfCVL                              4
#define I_sts58kPerfMonPerfCVP                              5
#define I_sts58kPerfMonPerfCS                               6
#define I_sts58kPerfMonPerfESP                              7
#define I_sts58kPerfMonPerfJitter                           8
#define I_sts58kPerfMonPerfPhaseData                        9
#define I_sts58kPerfMonPerfSESP                             10
#define I_sts58kPerfMonPerfTIE                              11
#define I_sts58kPerfMonPerfMTIE                             12
#define I_sts58kPerfMonPerfWDR5M                            13
#define I_sts58kPerfMonPerfWDR24H                           14
#define I_sts58kPerfMonEntry_max                            14

#define I_sts58kAlarmSource                                 0
#define I_sts58kAlarmSourceType                             1
#define I_sts58kAlarmSeverity                               2
#define I_sts58kAlarmSrvEff                                 3
#define I_sts58kAlarmStatusEntry_max                        3

#define I_sts58kOutputShelf                                 0
#define I_sts58kOutputSlot                                  1
#define I_sts58kOutputRedState                              2
#define I_sts58kOutputRedSwitchState                        3
#define I_sts58kOutputCRCCHK                                4
#define I_sts58kOutputCAS                                   5
#define I_sts58kOutputSSM                                   6
#define I_sts58kOutputSSMValue                              7
#define I_sts58kOutputTimingFormat                          8
#define I_sts58kOutputCardEntry_max                         8

#define I_sts58kEmmShelf                                    0
#define I_sts58kEmmUnitId                                   1
#define I_sts58kEmmSensorType                               2
#define I_sts58kEmmAlarmStatus                              3
#define I_sts58kEmmSensorReading                            4
#define I_sts58kEmmMajorAlmHiThresh                         5
#define I_sts58kEmmMajorAlmLoThresh                         6
#define I_sts58kEmmMinorAlmHiThresh                         7
#define I_sts58kEmmMinorAlmLoThresh                         8
#define I_sts58kEmmStatusEntry_max                          8

#define I_sts58kAntIndex                                    0
#define I_sts58kAntStatus                                   1
#define I_sts58kAntSwitchState                              2
#define I_sts58kAntEntry_max                                2

#define I_sts58kTopDestNumber                               0
#define I_sts58kTopDestIp                                   1
#define I_sts58kTopDestUdpPort                              2
#define I_sts58kTopDestVlanId                               3
#define I_sts58kTopDestEntry_max                            3

#define I_sts58kTrapRegMgrNumber                            0
#define I_sts58kTrapRegMgrIp                                1
#define I_sts58kTrapRegMgrUdpPort                           2
#define I_sts58kTrapRegCommunityStr                         3
#define I_sts58kTrapRegState                                4
#define I_sts58kTrapRegEntry_max                            4

#include "undefs.h"


#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_SNMPSUPP_H */
