/*
 *
 * Copyright (C) 1992-2003 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -o snmp -separate_type_file 
 */

/*
 * automatically generated by the mib compiler -- do not edit
 */

/* this macro defines the oid value within the structure, including a comma */
#define OIDvalue(name, value) { name , (SR_UINT32 *) value },
/* this macro includes a name string if LIGHT is not defined */
#ifndef LIGHT
#define OIDincludeST(name) (char *) name ,
#else	/* LIGHT */
#ifdef EMANATE
#define OIDincludeST(name) NULL,
#else	/* EMANATE*/
#define OIDincludeST(name)
#endif	/* EMANATE */
#endif	/* LIGHT */
/* this macro includes the access routines in the OID structure */
#ifdef SETS
#define OIDaccess(getr, testr) (GetMethod)getr, (TestMethod)testr
#else /* SETS */
#define OIDaccess(getr, testr) (GetMethod)getr, (TestMethod)readOnly_test
#endif /* SETS */

/* define the oid call table */
#if defined(I_sysDescr)
{
    OIDvalue(LNsysDescr, IDsysDescr)
    OIDincludeST(STsysDescr)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_sysDescr, 32,
    OIDaccess(system_get, readOnly_test)
},
#endif	/* defined(I_sysDescr) */

#if defined(I_sysObjectID)
{
    OIDvalue(LNsysObjectID, IDsysObjectID)
    OIDincludeST(STsysObjectID)
    OBJECT_ID_TYPE, SR_READ_ONLY, I_sysObjectID, 32,
    OIDaccess(system_get, readOnly_test)
},
#endif	/* defined(I_sysObjectID) */

#if defined(I_stsSystemId)
{
    OIDvalue(LNstsSystemId, IDstsSystemId)
    OIDincludeST(STstsSystemId)
    OCTET_PRIM_TYPE, SR_READ_WRITE, I_stsSystemId, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemId) */

#if defined(I_stsSystemMgmtIpOption)
{
    OIDvalue(LNstsSystemMgmtIpOption, IDstsSystemMgmtIpOption)
    OIDincludeST(STstsSystemMgmtIpOption)
    INTEGER_TYPE, SR_READ_WRITE, I_stsSystemMgmtIpOption, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemMgmtIpOption) */

#if defined(I_stsSystemMgmtIpAddress)
{
    OIDvalue(LNstsSystemMgmtIpAddress, IDstsSystemMgmtIpAddress)
    OIDincludeST(STstsSystemMgmtIpAddress)
    IP_ADDR_PRIM_TYPE, SR_READ_WRITE, I_stsSystemMgmtIpAddress, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemMgmtIpAddress) */

#if defined(I_stsSystemMgmtIpSubnetMask)
{
    OIDvalue(LNstsSystemMgmtIpSubnetMask, IDstsSystemMgmtIpSubnetMask)
    OIDincludeST(STstsSystemMgmtIpSubnetMask)
    IP_ADDR_PRIM_TYPE, SR_READ_WRITE, I_stsSystemMgmtIpSubnetMask, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemMgmtIpSubnetMask) */

#if defined(I_stsSystemMgmtIpGatewayAddress)
{
    OIDvalue(LNstsSystemMgmtIpGatewayAddress, IDstsSystemMgmtIpGatewayAddress)
    OIDincludeST(STstsSystemMgmtIpGatewayAddress)
    IP_ADDR_PRIM_TYPE, SR_READ_WRITE, I_stsSystemMgmtIpGatewayAddress, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemMgmtIpGatewayAddress) */

#if defined(I_stsSystemNtpIpOption)
{
    OIDvalue(LNstsSystemNtpIpOption, IDstsSystemNtpIpOption)
    OIDincludeST(STstsSystemNtpIpOption)
    INTEGER_TYPE, SR_READ_WRITE, I_stsSystemNtpIpOption, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemNtpIpOption) */

#if defined(I_stsSystemNtpIpAddress)
{
    OIDvalue(LNstsSystemNtpIpAddress, IDstsSystemNtpIpAddress)
    OIDincludeST(STstsSystemNtpIpAddress)
    IP_ADDR_PRIM_TYPE, SR_READ_WRITE, I_stsSystemNtpIpAddress, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemNtpIpAddress) */

#if defined(I_stsSystemNtpIpSubnetMask)
{
    OIDvalue(LNstsSystemNtpIpSubnetMask, IDstsSystemNtpIpSubnetMask)
    OIDincludeST(STstsSystemNtpIpSubnetMask)
    IP_ADDR_PRIM_TYPE, SR_READ_WRITE, I_stsSystemNtpIpSubnetMask, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemNtpIpSubnetMask) */

#if defined(I_stsSystemNtpIpGatewayAddress)
{
    OIDvalue(LNstsSystemNtpIpGatewayAddress, IDstsSystemNtpIpGatewayAddress)
    OIDincludeST(STstsSystemNtpIpGatewayAddress)
    IP_ADDR_PRIM_TYPE, SR_READ_WRITE, I_stsSystemNtpIpGatewayAddress, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemNtpIpGatewayAddress) */

#if defined(I_stsSystemDate)
{
    OIDvalue(LNstsSystemDate, IDstsSystemDate)
    OIDincludeST(STstsSystemDate)
    OCTET_PRIM_TYPE, SR_READ_WRITE, I_stsSystemDate, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemDate) */

#if defined(I_stsSystemTime)
{
    OIDvalue(LNstsSystemTime, IDstsSystemTime)
    OIDincludeST(STstsSystemTime)
    OCTET_PRIM_TYPE, SR_READ_WRITE, I_stsSystemTime, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemTime) */

#if defined(I_stsSystemTimeZone)
{
    OIDvalue(LNstsSystemTimeZone, IDstsSystemTimeZone)
    OIDincludeST(STstsSystemTimeZone)
    INTEGER_TYPE, SR_READ_WRITE, I_stsSystemTimeZone, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemTimeZone) */

#if defined(I_stsSystemIntegratedAlarm)
{
    OIDvalue(LNstsSystemIntegratedAlarm, IDstsSystemIntegratedAlarm)
    OIDincludeST(STstsSystemIntegratedAlarm)
    INTEGER_TYPE, SR_READ_ONLY, I_stsSystemIntegratedAlarm, 32,
    OIDaccess(stsSystem_get, readOnly_test)
},
#endif	/* defined(I_stsSystemIntegratedAlarm) */

#if defined(I_stsSystemAlarmAcoMode)
{
    OIDvalue(LNstsSystemAlarmAcoMode, IDstsSystemAlarmAcoMode)
    OIDincludeST(STstsSystemAlarmAcoMode)
    INTEGER_TYPE, SR_READ_WRITE, I_stsSystemAlarmAcoMode, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemAlarmAcoMode) */

#if defined(I_stsSystemAlarmAcoLed)
{
    OIDvalue(LNstsSystemAlarmAcoLed, IDstsSystemAlarmAcoLed)
    OIDincludeST(STstsSystemAlarmAcoLed)
    INTEGER_TYPE, SR_READ_ONLY, I_stsSystemAlarmAcoLed, 32,
    OIDaccess(stsSystem_get, readOnly_test)
},
#endif	/* defined(I_stsSystemAlarmAcoLed) */

#if defined(I_stsSystemAlarmAcoCutOff)
{
    OIDvalue(LNstsSystemAlarmAcoCutOff, IDstsSystemAlarmAcoCutOff)
    OIDincludeST(STstsSystemAlarmAcoCutOff)
    INTEGER_TYPE, SR_READ_WRITE, I_stsSystemAlarmAcoCutOff, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemAlarmAcoCutOff) */

#if defined(I_stsSystemAlarmEscalatingTime)
{
    OIDvalue(LNstsSystemAlarmEscalatingTime, IDstsSystemAlarmEscalatingTime)
    OIDincludeST(STstsSystemAlarmEscalatingTime)
    INTEGER_TYPE, SR_READ_WRITE, I_stsSystemAlarmEscalatingTime, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemAlarmEscalatingTime) */

#if defined(I_stsSystemMinorLED)
{
    OIDvalue(LNstsSystemMinorLED, IDstsSystemMinorLED)
    OIDincludeST(STstsSystemMinorLED)
    INTEGER_TYPE, SR_READ_ONLY, I_stsSystemMinorLED, 32,
    OIDaccess(stsSystem_get, readOnly_test)
},
#endif	/* defined(I_stsSystemMinorLED) */

#if defined(I_stsSystemMajorLED)
{
    OIDvalue(LNstsSystemMajorLED, IDstsSystemMajorLED)
    OIDincludeST(STstsSystemMajorLED)
    INTEGER_TYPE, SR_READ_ONLY, I_stsSystemMajorLED, 32,
    OIDaccess(stsSystem_get, readOnly_test)
},
#endif	/* defined(I_stsSystemMajorLED) */

#if defined(I_stsSystemCriticalLED)
{
    OIDvalue(LNstsSystemCriticalLED, IDstsSystemCriticalLED)
    OIDincludeST(STstsSystemCriticalLED)
    INTEGER_TYPE, SR_READ_ONLY, I_stsSystemCriticalLED, 32,
    OIDaccess(stsSystem_get, readOnly_test)
},
#endif	/* defined(I_stsSystemCriticalLED) */

#if defined(I_stsSystemUpgradeSWAction)
{
    OIDvalue(LNstsSystemUpgradeSWAction, IDstsSystemUpgradeSWAction)
    OIDincludeST(STstsSystemUpgradeSWAction)
    INTEGER_TYPE, SR_READ_WRITE, I_stsSystemUpgradeSWAction, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemUpgradeSWAction) */

#if defined(I_stsSystemCurrentSWVersion)
{
    OIDvalue(LNstsSystemCurrentSWVersion, IDstsSystemCurrentSWVersion)
    OIDincludeST(STstsSystemCurrentSWVersion)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsSystemCurrentSWVersion, 32,
    OIDaccess(stsSystem_get, readOnly_test)
},
#endif	/* defined(I_stsSystemCurrentSWVersion) */

#if defined(I_stsSystemServiceState)
{
    OIDvalue(LNstsSystemServiceState, IDstsSystemServiceState)
    OIDincludeST(STstsSystemServiceState)
    INTEGER_TYPE, SR_READ_ONLY, I_stsSystemServiceState, 32,
    OIDaccess(stsSystem_get, readOnly_test)
},
#endif	/* defined(I_stsSystemServiceState) */

#if defined(I_stsSystemReset)
{
    OIDvalue(LNstsSystemReset, IDstsSystemReset)
    OIDincludeST(STstsSystemReset)
    INTEGER_TYPE, SR_READ_WRITE, I_stsSystemReset, 32,
    OIDaccess(stsSystem_get, stsSystem_test)
},
#endif	/* defined(I_stsSystemReset) */

#if defined(I_stsClockInputManualSelect)
{
    OIDvalue(LNstsClockInputManualSelect, IDstsClockInputManualSelect)
    OIDincludeST(STstsClockInputManualSelect)
    INTEGER_TYPE, SR_READ_WRITE, I_stsClockInputManualSelect, 32,
    OIDaccess(stsClockInput_get, stsClockInput_test)
},
#endif	/* defined(I_stsClockInputManualSelect) */

#if defined(I_stsClockInputOperMode)
{
    OIDvalue(LNstsClockInputOperMode, IDstsClockInputOperMode)
    OIDincludeST(STstsClockInputOperMode)
    INTEGER_TYPE, SR_READ_WRITE, I_stsClockInputOperMode, 32,
    OIDaccess(stsClockInput_get, stsClockInput_test)
},
#endif	/* defined(I_stsClockInputOperMode) */

#if defined(I_stsClockInputSetSlip)
{
    OIDvalue(LNstsClockInputSetSlip, IDstsClockInputSetSlip)
    OIDincludeST(STstsClockInputSetSlip)
    INTEGER_TYPE, SR_READ_WRITE, I_stsClockInputSetSlip, 32,
    OIDaccess(stsClockInput_get, stsClockInput_test)
},
#endif	/* defined(I_stsClockInputSetSlip) */

#if defined(I_stsClockInputSlipState)
{
    OIDvalue(LNstsClockInputSlipState, IDstsClockInputSlipState)
    OIDincludeST(STstsClockInputSlipState)
    INTEGER_TYPE, SR_READ_ONLY, I_stsClockInputSlipState, 32,
    OIDaccess(stsClockInput_get, readOnly_test)
},
#endif	/* defined(I_stsClockInputSlipState) */

#if defined(I_stsClockInputSlipAlarmSetting)
{
    OIDvalue(LNstsClockInputSlipAlarmSetting, IDstsClockInputSlipAlarmSetting)
    OIDincludeST(STstsClockInputSlipAlarmSetting)
    INTEGER_TYPE, SR_READ_WRITE, I_stsClockInputSlipAlarmSetting, 32,
    OIDaccess(stsClockInput_get, stsClockInput_test)
},
#endif	/* defined(I_stsClockInputSlipAlarmSetting) */

#if defined(I_stsClockInputSlipAlarmSeverity)
{
    OIDvalue(LNstsClockInputSlipAlarmSeverity, IDstsClockInputSlipAlarmSeverity)
    OIDincludeST(STstsClockInputSlipAlarmSeverity)
    INTEGER_TYPE, SR_READ_ONLY, I_stsClockInputSlipAlarmSeverity, 32,
    OIDaccess(stsClockInput_get, readOnly_test)
},
#endif	/* defined(I_stsClockInputSlipAlarmSeverity) */

#if defined(I_stsClockInputValue)
{
    OIDvalue(LNstsClockInputValue, IDstsClockInputValue)
    OIDincludeST(STstsClockInputValue)
    INTEGER_TYPE, SR_READ_ONLY, I_stsClockInputValue, 32,
    OIDaccess(stsClockInput_get, readOnly_test)
},
#endif	/* defined(I_stsClockInputValue) */

#if defined(I_stsClockInputSSMSelect)
{
    OIDvalue(LNstsClockInputSSMSelect, IDstsClockInputSSMSelect)
    OIDincludeST(STstsClockInputSSMSelect)
    INTEGER_TYPE, SR_READ_WRITE, I_stsClockInputSSMSelect, 32,
    OIDaccess(stsClockInputSSM_get, stsClockInputSSM_test)
},
#endif	/* defined(I_stsClockInputSSMSelect) */

#if defined(I_stsTopSourceIpOption)
{
    OIDvalue(LNstsTopSourceIpOption, IDstsTopSourceIpOption)
    OIDincludeST(STstsTopSourceIpOption)
    INTEGER_TYPE, SR_READ_WRITE, I_stsTopSourceIpOption, 32,
    OIDaccess(stsTop_get, stsTop_test)
},
#endif	/* defined(I_stsTopSourceIpOption) */

#if defined(I_stsTopSourceIpAddress)
{
    OIDvalue(LNstsTopSourceIpAddress, IDstsTopSourceIpAddress)
    OIDincludeST(STstsTopSourceIpAddress)
    IP_ADDR_PRIM_TYPE, SR_READ_WRITE, I_stsTopSourceIpAddress, 32,
    OIDaccess(stsTop_get, stsTop_test)
},
#endif	/* defined(I_stsTopSourceIpAddress) */

#if defined(I_stsTopSourceIpSubnetMask)
{
    OIDvalue(LNstsTopSourceIpSubnetMask, IDstsTopSourceIpSubnetMask)
    OIDincludeST(STstsTopSourceIpSubnetMask)
    IP_ADDR_PRIM_TYPE, SR_READ_WRITE, I_stsTopSourceIpSubnetMask, 32,
    OIDaccess(stsTop_get, stsTop_test)
},
#endif	/* defined(I_stsTopSourceIpSubnetMask) */

#if defined(I_stsTopSourceIpGatewayAddress)
{
    OIDvalue(LNstsTopSourceIpGatewayAddress, IDstsTopSourceIpGatewayAddress)
    OIDincludeST(STstsTopSourceIpGatewayAddress)
    IP_ADDR_PRIM_TYPE, SR_READ_WRITE, I_stsTopSourceIpGatewayAddress, 32,
    OIDaccess(stsTop_get, stsTop_test)
},
#endif	/* defined(I_stsTopSourceIpGatewayAddress) */

#if defined(I_stsTopPacketRate)
{
    OIDvalue(LNstsTopPacketRate, IDstsTopPacketRate)
    OIDincludeST(STstsTopPacketRate)
    INTEGER_TYPE, SR_READ_WRITE, I_stsTopPacketRate, 32,
    OIDaccess(stsTop_get, stsTop_test)
},
#endif	/* defined(I_stsTopPacketRate) */

#if defined(I_stsTopInputSelect)
{
    OIDvalue(LNstsTopInputSelect, IDstsTopInputSelect)
    OIDincludeST(STstsTopInputSelect)
    INTEGER_TYPE, SR_READ_WRITE, I_stsTopInputSelect, 32,
    OIDaccess(stsTop_get, stsTop_test)
},
#endif	/* defined(I_stsTopInputSelect) */

#if defined(I_stsTopTxPackets)
{
    OIDvalue(LNstsTopTxPackets, IDstsTopTxPackets)
    OIDincludeST(STstsTopTxPackets)
    INTEGER_TYPE, SR_READ_ONLY, I_stsTopTxPackets, 32,
    OIDaccess(stsTop_get, readOnly_test)
},
#endif	/* defined(I_stsTopTxPackets) */

#if defined(I_stsTopTxBytes)
{
    OIDvalue(LNstsTopTxBytes, IDstsTopTxBytes)
    OIDincludeST(STstsTopTxBytes)
    INTEGER_TYPE, SR_READ_ONLY, I_stsTopTxBytes, 32,
    OIDaccess(stsTop_get, readOnly_test)
},
#endif	/* defined(I_stsTopTxBytes) */

#if defined(I_stsPerfMonManualInputSelect)
{
    OIDvalue(LNstsPerfMonManualInputSelect, IDstsPerfMonManualInputSelect)
    OIDincludeST(STstsPerfMonManualInputSelect)
    BITS_TYPE, SR_READ_WRITE, I_stsPerfMonManualInputSelect, 32,
    OIDaccess(stsPerfMonManual_get, stsPerfMonManual_test)
},
#endif	/* defined(I_stsPerfMonManualInputSelect) */

#if defined(I_stsPerfMonManualInputScanInterval)
{
    OIDvalue(LNstsPerfMonManualInputScanInterval, IDstsPerfMonManualInputScanInterval)
    OIDincludeST(STstsPerfMonManualInputScanInterval)
    INTEGER_TYPE, SR_READ_WRITE, I_stsPerfMonManualInputScanInterval, 32,
    OIDaccess(stsPerfMonManual_get, stsPerfMonManual_test)
},
#endif	/* defined(I_stsPerfMonManualInputScanInterval) */

#if defined(I_stsPerfMonManualInputNumReport)
{
    OIDvalue(LNstsPerfMonManualInputNumReport, IDstsPerfMonManualInputNumReport)
    OIDincludeST(STstsPerfMonManualInputNumReport)
    INTEGER_TYPE, SR_READ_WRITE, I_stsPerfMonManualInputNumReport, 32,
    OIDaccess(stsPerfMonManual_get, stsPerfMonManual_test)
},
#endif	/* defined(I_stsPerfMonManualInputNumReport) */

#if defined(I_stsPerfMonManualInputNumObservation)
{
    OIDvalue(LNstsPerfMonManualInputNumObservation, IDstsPerfMonManualInputNumObservation)
    OIDincludeST(STstsPerfMonManualInputNumObservation)
    INTEGER_TYPE, SR_READ_WRITE, I_stsPerfMonManualInputNumObservation, 32,
    OIDaccess(stsPerfMonManual_get, stsPerfMonManual_test)
},
#endif	/* defined(I_stsPerfMonManualInputNumObservation) */

#if defined(I_stsPerfMonManualInputAbortTest)
{
    OIDvalue(LNstsPerfMonManualInputAbortTest, IDstsPerfMonManualInputAbortTest)
    OIDincludeST(STstsPerfMonManualInputAbortTest)
    INTEGER_TYPE, SR_READ_WRITE, I_stsPerfMonManualInputAbortTest, 32,
    OIDaccess(stsPerfMonManual_get, stsPerfMonManual_test)
},
#endif	/* defined(I_stsPerfMonManualInputAbortTest) */

#if defined(I_stsReadOnlyCommStr)
{
    OIDvalue(LNstsReadOnlyCommStr, IDstsReadOnlyCommStr)
    OIDincludeST(STstsReadOnlyCommStr)
    OCTET_PRIM_TYPE, SR_READ_WRITE, I_stsReadOnlyCommStr, 32,
    OIDaccess(stsCommStr_get, stsCommStr_test)
},
#endif	/* defined(I_stsReadOnlyCommStr) */

#if defined(I_stsReadWriteCommStr)
{
    OIDvalue(LNstsReadWriteCommStr, IDstsReadWriteCommStr)
    OIDincludeST(STstsReadWriteCommStr)
    OCTET_PRIM_TYPE, SR_READ_WRITE, I_stsReadWriteCommStr, 32,
    OIDaccess(stsCommStr_get, stsCommStr_test)
},
#endif	/* defined(I_stsReadWriteCommStr) */

#if defined(I_stsClockInputStatusIndex)
{
    OIDvalue(LNstsClockInputStatusIndex, IDstsClockInputStatusIndex)
    OIDincludeST(STstsClockInputStatusIndex)
    INTEGER_TYPE, SR_READ_ONLY, I_stsClockInputStatusIndex, 32,
    OIDaccess(stsClockInputStatusEntry_get, readOnly_test)
},
#endif	/* defined(I_stsClockInputStatusIndex) */

#if defined(I_stsClockInputState)
{
    OIDvalue(LNstsClockInputState, IDstsClockInputState)
    OIDincludeST(STstsClockInputState)
    INTEGER_TYPE, SR_READ_ONLY, I_stsClockInputState, 32,
    OIDaccess(stsClockInputStatusEntry_get, readOnly_test)
},
#endif	/* defined(I_stsClockInputState) */

#if defined(I_stsClockInputSSMIndex)
{
    OIDvalue(LNstsClockInputSSMIndex, IDstsClockInputSSMIndex)
    OIDincludeST(STstsClockInputSSMIndex)
    INTEGER_TYPE, SR_READ_ONLY, I_stsClockInputSSMIndex, 32,
    OIDaccess(stsClockInputSSMEntry_get, readOnly_test)
},
#endif	/* defined(I_stsClockInputSSMIndex) */

#if defined(I_stsClockInputSSMInputSelect)
{
    OIDvalue(LNstsClockInputSSMInputSelect, IDstsClockInputSSMInputSelect)
    OIDincludeST(STstsClockInputSSMInputSelect)
    INTEGER_TYPE, SR_READ_ONLY, I_stsClockInputSSMInputSelect, 32,
    OIDaccess(stsClockInputSSMEntry_get, readOnly_test)
},
#endif	/* defined(I_stsClockInputSSMInputSelect) */

#if defined(I_stsClockInputSSMValue)
{
    OIDvalue(LNstsClockInputSSMValue, IDstsClockInputSSMValue)
    OIDincludeST(STstsClockInputSSMValue)
    INTEGER_TYPE, SR_READ_ONLY, I_stsClockInputSSMValue, 32,
    OIDaccess(stsClockInputSSMEntry_get, readOnly_test)
},
#endif	/* defined(I_stsClockInputSSMValue) */

#if defined(I_stsCardShelf)
{
    OIDvalue(LNstsCardShelf, IDstsCardShelf)
    OIDincludeST(STstsCardShelf)
    INTEGER_TYPE, SR_READ_ONLY, I_stsCardShelf, 32,
    OIDaccess(stsCardEntry_get, readOnly_test)
},
#endif	/* defined(I_stsCardShelf) */

#if defined(I_stsCardIndex)
{
    OIDvalue(LNstsCardIndex, IDstsCardIndex)
    OIDincludeST(STstsCardIndex)
    INTEGER_TYPE, SR_READ_ONLY, I_stsCardIndex, 32,
    OIDaccess(stsCardEntry_get, readOnly_test)
},
#endif	/* defined(I_stsCardIndex) */

#if defined(I_stsCardType)
{
    OIDvalue(LNstsCardType, IDstsCardType)
    OIDincludeST(STstsCardType)
    INTEGER_TYPE, SR_READ_ONLY, I_stsCardType, 32,
    OIDaccess(stsCardEntry_get, readOnly_test)
},
#endif	/* defined(I_stsCardType) */

#if defined(I_stsCardDescr)
{
    OIDvalue(LNstsCardDescr, IDstsCardDescr)
    OIDincludeST(STstsCardDescr)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsCardDescr, 32,
    OIDaccess(stsCardEntry_get, readOnly_test)
},
#endif	/* defined(I_stsCardDescr) */

#if defined(I_stsCardSerial)
{
    OIDvalue(LNstsCardSerial, IDstsCardSerial)
    OIDincludeST(STstsCardSerial)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsCardSerial, 32,
    OIDaccess(stsCardEntry_get, readOnly_test)
},
#endif	/* defined(I_stsCardSerial) */

#if defined(I_stsCardHwVersion)
{
    OIDvalue(LNstsCardHwVersion, IDstsCardHwVersion)
    OIDincludeST(STstsCardHwVersion)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsCardHwVersion, 32,
    OIDaccess(stsCardEntry_get, readOnly_test)
},
#endif	/* defined(I_stsCardHwVersion) */

#if defined(I_stsCardCLEICode)
{
    OIDvalue(LNstsCardCLEICode, IDstsCardCLEICode)
    OIDincludeST(STstsCardCLEICode)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsCardCLEICode, 32,
    OIDaccess(stsCardEntry_get, readOnly_test)
},
#endif	/* defined(I_stsCardCLEICode) */

#if defined(I_stsCardOperStatus)
{
    OIDvalue(LNstsCardOperStatus, IDstsCardOperStatus)
    OIDincludeST(STstsCardOperStatus)
    INTEGER_TYPE, SR_READ_ONLY, I_stsCardOperStatus, 32,
    OIDaccess(stsCardEntry_get, readOnly_test)
},
#endif	/* defined(I_stsCardOperStatus) */

#if defined(I_stsCardReset)
{
    OIDvalue(LNstsCardReset, IDstsCardReset)
    OIDincludeST(STstsCardReset)
    INTEGER_TYPE, SR_READ_WRITE, I_stsCardReset, 32,
    OIDaccess(stsCardEntry_get, stsCardEntry_test)
},
#endif	/* defined(I_stsCardReset) */

#if defined(I_stsOscillatorIndex)
{
    OIDvalue(LNstsOscillatorIndex, IDstsOscillatorIndex)
    OIDincludeST(STstsOscillatorIndex)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOscillatorIndex, 32,
    OIDaccess(stsOscillatorEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorIndex) */

#if defined(I_stsOscillatorModuleType)
{
    OIDvalue(LNstsOscillatorModuleType, IDstsOscillatorModuleType)
    OIDincludeST(STstsOscillatorModuleType)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOscillatorModuleType, 32,
    OIDaccess(stsOscillatorEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorModuleType) */

#if defined(I_stsOscillatorEFER)
{
    OIDvalue(LNstsOscillatorEFER, IDstsOscillatorEFER)
    OIDincludeST(STstsOscillatorEFER)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsOscillatorEFER, 32,
    OIDaccess(stsOscillatorEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorEFER) */

#if defined(I_stsOscillatorESSD)
{
    OIDvalue(LNstsOscillatorESSD, IDstsOscillatorESSD)
    OIDincludeST(STstsOscillatorESSD)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsOscillatorESSD, 32,
    OIDaccess(stsOscillatorEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorESSD) */

#if defined(I_stsOscillatorESSN)
{
    OIDvalue(LNstsOscillatorESSN, IDstsOscillatorESSN)
    OIDincludeST(STstsOscillatorESSN)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsOscillatorESSN, 32,
    OIDaccess(stsOscillatorEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorESSN) */

#if defined(I_stsOscillatorFAGE)
{
    OIDvalue(LNstsOscillatorFAGE, IDstsOscillatorFAGE)
    OIDincludeST(STstsOscillatorFAGE)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsOscillatorFAGE, 32,
    OIDaccess(stsOscillatorEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorFAGE) */

#if defined(I_stsOscillatorTIMD)
{
    OIDvalue(LNstsOscillatorTIMD, IDstsOscillatorTIMD)
    OIDincludeST(STstsOscillatorTIMD)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsOscillatorTIMD, 32,
    OIDaccess(stsOscillatorEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorTIMD) */

#if defined(I_stsOscillatorSwitchState)
{
    OIDvalue(LNstsOscillatorSwitchState, IDstsOscillatorSwitchState)
    OIDincludeST(STstsOscillatorSwitchState)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOscillatorSwitchState, 32,
    OIDaccess(stsOscillatorEntry_get, stsOscillatorEntry_test)
},
#endif	/* defined(I_stsOscillatorSwitchState) */

#if defined(I_stsOscillatorStatus)
{
    OIDvalue(LNstsOscillatorStatus, IDstsOscillatorStatus)
    OIDincludeST(STstsOscillatorStatus)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOscillatorStatus, 32,
    OIDaccess(stsOscillatorEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorStatus) */

#if defined(I_stsOscillatorRedStatus)
{
    OIDvalue(LNstsOscillatorRedStatus, IDstsOscillatorRedStatus)
    OIDincludeST(STstsOscillatorRedStatus)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOscillatorRedStatus, 32,
    OIDaccess(stsOscillatorEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorRedStatus) */

#if defined(I_stsGpsIndex)
{
    OIDvalue(LNstsGpsIndex, IDstsGpsIndex)
    OIDincludeST(STstsGpsIndex)
    INTEGER_TYPE, SR_READ_ONLY, I_stsGpsIndex, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsIndex) */

#if defined(I_stsGpsStatus)
{
    OIDvalue(LNstsGpsStatus, IDstsGpsStatus)
    OIDincludeST(STstsGpsStatus)
    INTEGER_TYPE, SR_READ_ONLY, I_stsGpsStatus, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsStatus) */

#if defined(I_stsGpsState)
{
    OIDvalue(LNstsGpsState, IDstsGpsState)
    OIDincludeST(STstsGpsState)
    INTEGER_TYPE, SR_READ_ONLY, I_stsGpsState, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsState) */

#if defined(I_stsGpsANTD)
{
    OIDvalue(LNstsGpsANTD, IDstsGpsANTD)
    OIDincludeST(STstsGpsANTD)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsANTD, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsANTD) */

#if defined(I_stsGpsAZEL)
{
    OIDvalue(LNstsGpsAZEL, IDstsGpsAZEL)
    OIDincludeST(STstsGpsAZEL)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsAZEL, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsAZEL) */

#if defined(I_stsGpsRSTG)
{
    OIDvalue(LNstsGpsRSTG, IDstsGpsRSTG)
    OIDincludeST(STstsGpsRSTG)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsRSTG, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsRSTG) */

#if defined(I_stsGpsBITS)
{
    OIDvalue(LNstsGpsBITS, IDstsGpsBITS)
    OIDincludeST(STstsGpsBITS)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsBITS, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsBITS) */

#if defined(I_stsGpsPAVG)
{
    OIDvalue(LNstsGpsPAVG, IDstsGpsPAVG)
    OIDincludeST(STstsGpsPAVG)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsPAVG, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsPAVG) */

#if defined(I_stsGpsSIGQ)
{
    OIDvalue(LNstsGpsSIGQ, IDstsGpsSIGQ)
    OIDincludeST(STstsGpsSIGQ)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsSIGQ, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsSIGQ) */

#if defined(I_stsGpsSPOS)
{
    OIDvalue(LNstsGpsSPOS, IDstsGpsSPOS)
    OIDincludeST(STstsGpsSPOS)
    OCTET_PRIM_TYPE, SR_READ_WRITE, I_stsGpsSPOS, 32,
    OIDaccess(stsGpsEntry_get, stsGpsEntry_test)
},
#endif	/* defined(I_stsGpsSPOS) */

#if defined(I_stsGpsTRMO)
{
    OIDvalue(LNstsGpsTRMO, IDstsGpsTRMO)
    OIDincludeST(STstsGpsTRMO)
    OCTET_PRIM_TYPE, SR_READ_WRITE, I_stsGpsTRMO, 32,
    OIDaccess(stsGpsEntry_get, stsGpsEntry_test)
},
#endif	/* defined(I_stsGpsTRMO) */

#if defined(I_stsGpsUTCT)
{
    OIDvalue(LNstsGpsUTCT, IDstsGpsUTCT)
    OIDincludeST(STstsGpsUTCT)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsUTCT, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsUTCT) */

#if defined(I_stsGpsVERS)
{
    OIDvalue(LNstsGpsVERS, IDstsGpsVERS)
    OIDincludeST(STstsGpsVERS)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsVERS, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsVERS) */

#if defined(I_stsGpsDETF)
{
    OIDvalue(LNstsGpsDETF, IDstsGpsDETF)
    OIDincludeST(STstsGpsDETF)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsDETF, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsDETF) */

#if defined(I_stsGpsEFER)
{
    OIDvalue(LNstsGpsEFER, IDstsGpsEFER)
    OIDincludeST(STstsGpsEFER)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsEFER, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsEFER) */

#if defined(I_stsGpsESSD)
{
    OIDvalue(LNstsGpsESSD, IDstsGpsESSD)
    OIDincludeST(STstsGpsESSD)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsESSD, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsESSD) */

#if defined(I_stsGpsESSN)
{
    OIDvalue(LNstsGpsESSN, IDstsGpsESSN)
    OIDincludeST(STstsGpsESSN)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsESSN, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsESSN) */

#if defined(I_stsGpsFAGE)
{
    OIDvalue(LNstsGpsFAGE, IDstsGpsFAGE)
    OIDincludeST(STstsGpsFAGE)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsFAGE, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsFAGE) */

#if defined(I_stsGpsTIMD)
{
    OIDvalue(LNstsGpsTIMD, IDstsGpsTIMD)
    OIDincludeST(STstsGpsTIMD)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsGpsTIMD, 32,
    OIDaccess(stsGpsEntry_get, readOnly_test)
},
#endif	/* defined(I_stsGpsTIMD) */

#if defined(I_stsGpsReset)
{
    OIDvalue(LNstsGpsReset, IDstsGpsReset)
    OIDincludeST(STstsGpsReset)
    INTEGER_TYPE, SR_READ_WRITE, I_stsGpsReset, 32,
    OIDaccess(stsGpsEntry_get, stsGpsEntry_test)
},
#endif	/* defined(I_stsGpsReset) */

#if defined(I_stsLinkIndex)
{
    OIDvalue(LNstsLinkIndex, IDstsLinkIndex)
    OIDincludeST(STstsLinkIndex)
    INTEGER_TYPE, SR_READ_ONLY, I_stsLinkIndex, 32,
    OIDaccess(stsLinkEntry_get, readOnly_test)
},
#endif	/* defined(I_stsLinkIndex) */

#if defined(I_stsLinkType)
{
    OIDvalue(LNstsLinkType, IDstsLinkType)
    OIDincludeST(STstsLinkType)
    INTEGER_TYPE, SR_READ_WRITE, I_stsLinkType, 32,
    OIDaccess(stsLinkEntry_get, stsLinkEntry_test)
},
#endif	/* defined(I_stsLinkType) */

#if defined(I_stsLinkEnable)
{
    OIDvalue(LNstsLinkEnable, IDstsLinkEnable)
    OIDincludeST(STstsLinkEnable)
    INTEGER_TYPE, SR_READ_WRITE, I_stsLinkEnable, 32,
    OIDaccess(stsLinkEntry_get, stsLinkEntry_test)
},
#endif	/* defined(I_stsLinkEnable) */

#if defined(I_stsLinkLineCode)
{
    OIDvalue(LNstsLinkLineCode, IDstsLinkLineCode)
    OIDincludeST(STstsLinkLineCode)
    INTEGER_TYPE, SR_READ_WRITE, I_stsLinkLineCode, 32,
    OIDaccess(stsLinkEntry_get, stsLinkEntry_test)
},
#endif	/* defined(I_stsLinkLineCode) */

#if defined(I_stsLinkFMT)
{
    OIDvalue(LNstsLinkFMT, IDstsLinkFMT)
    OIDincludeST(STstsLinkFMT)
    INTEGER_TYPE, SR_READ_WRITE, I_stsLinkFMT, 32,
    OIDaccess(stsLinkEntry_get, stsLinkEntry_test)
},
#endif	/* defined(I_stsLinkFMT) */

#if defined(I_stsLinkTermination)
{
    OIDvalue(LNstsLinkTermination, IDstsLinkTermination)
    OIDincludeST(STstsLinkTermination)
    INTEGER_TYPE, SR_READ_WRITE, I_stsLinkTermination, 32,
    OIDaccess(stsLinkEntry_get, stsLinkEntry_test)
},
#endif	/* defined(I_stsLinkTermination) */

#if defined(I_stsLinkMFCHK)
{
    OIDvalue(LNstsLinkMFCHK, IDstsLinkMFCHK)
    OIDincludeST(STstsLinkMFCHK)
    INTEGER_TYPE, SR_READ_WRITE, I_stsLinkMFCHK, 32,
    OIDaccess(stsLinkEntry_get, stsLinkEntry_test)
},
#endif	/* defined(I_stsLinkMFCHK) */

#if defined(I_stsLinkId)
{
    OIDvalue(LNstsLinkId, IDstsLinkId)
    OIDincludeST(STstsLinkId)
    OCTET_PRIM_TYPE, SR_READ_WRITE, I_stsLinkId, 32,
    OIDaccess(stsLinkEntry_get, stsLinkEntry_test)
},
#endif	/* defined(I_stsLinkId) */

#if defined(I_stsShelfIndex)
{
    OIDvalue(LNstsShelfIndex, IDstsShelfIndex)
    OIDincludeST(STstsShelfIndex)
    INTEGER_TYPE, SR_READ_ONLY, I_stsShelfIndex, 32,
    OIDaccess(stsShelfEntry_get, readOnly_test)
},
#endif	/* defined(I_stsShelfIndex) */

#if defined(I_stsShelfSerial)
{
    OIDvalue(LNstsShelfSerial, IDstsShelfSerial)
    OIDincludeST(STstsShelfSerial)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsShelfSerial, 32,
    OIDaccess(stsShelfEntry_get, readOnly_test)
},
#endif	/* defined(I_stsShelfSerial) */

#if defined(I_stsShelfCLEICode)
{
    OIDvalue(LNstsShelfCLEICode, IDstsShelfCLEICode)
    OIDincludeST(STstsShelfCLEICode)
    OCTET_PRIM_TYPE, SR_READ_ONLY, I_stsShelfCLEICode, 32,
    OIDaccess(stsShelfEntry_get, readOnly_test)
},
#endif	/* defined(I_stsShelfCLEICode) */

#if defined(I_stsShelfReset)
{
    OIDvalue(LNstsShelfReset, IDstsShelfReset)
    OIDincludeST(STstsShelfReset)
    INTEGER_TYPE, SR_READ_WRITE, I_stsShelfReset, 32,
    OIDaccess(stsShelfEntry_get, stsShelfEntry_test)
},
#endif	/* defined(I_stsShelfReset) */

#if defined(I_stsAlarmThresholdCurrentMon)
{
    OIDvalue(LNstsAlarmThresholdCurrentMon, IDstsAlarmThresholdCurrentMon)
    OIDincludeST(STstsAlarmThresholdCurrentMon)
    INTEGER_TYPE, SR_READ_ONLY, I_stsAlarmThresholdCurrentMon, 32,
    OIDaccess(stsAlarmThresholdEntry_get, readOnly_test)
},
#endif	/* defined(I_stsAlarmThresholdCurrentMon) */

#if defined(I_stsAlarmThresholdType)
{
    OIDvalue(LNstsAlarmThresholdType, IDstsAlarmThresholdType)
    OIDincludeST(STstsAlarmThresholdType)
    INTEGER_TYPE, SR_READ_ONLY, I_stsAlarmThresholdType, 32,
    OIDaccess(stsAlarmThresholdEntry_get, readOnly_test)
},
#endif	/* defined(I_stsAlarmThresholdType) */

#if defined(I_stsAlarmThresholdValue)
{
    OIDvalue(LNstsAlarmThresholdValue, IDstsAlarmThresholdValue)
    OIDincludeST(STstsAlarmThresholdValue)
    INTEGER_TYPE, SR_READ_WRITE, I_stsAlarmThresholdValue, 32,
    OIDaccess(stsAlarmThresholdEntry_get, stsAlarmThresholdEntry_test)
},
#endif	/* defined(I_stsAlarmThresholdValue) */

#if defined(I_stsAlarmThresholdTimeInterval)
{
    OIDvalue(LNstsAlarmThresholdTimeInterval, IDstsAlarmThresholdTimeInterval)
    OIDincludeST(STstsAlarmThresholdTimeInterval)
    INTEGER_TYPE, SR_READ_WRITE, I_stsAlarmThresholdTimeInterval, 32,
    OIDaccess(stsAlarmThresholdEntry_get, stsAlarmThresholdEntry_test)
},
#endif	/* defined(I_stsAlarmThresholdTimeInterval) */

#if defined(I_stsLinkAlarmSettingLinkType)
{
    OIDvalue(LNstsLinkAlarmSettingLinkType, IDstsLinkAlarmSettingLinkType)
    OIDincludeST(STstsLinkAlarmSettingLinkType)
    INTEGER_TYPE, SR_READ_ONLY, I_stsLinkAlarmSettingLinkType, 32,
    OIDaccess(stsLinkAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsLinkAlarmSettingLinkType) */

#if defined(I_stsLinkAlarmSettingType)
{
    OIDvalue(LNstsLinkAlarmSettingType, IDstsLinkAlarmSettingType)
    OIDincludeST(STstsLinkAlarmSettingType)
    INTEGER_TYPE, SR_READ_ONLY, I_stsLinkAlarmSettingType, 32,
    OIDaccess(stsLinkAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsLinkAlarmSettingType) */

#if defined(I_stsLinkAlarmSettingSevirity)
{
    OIDvalue(LNstsLinkAlarmSettingSevirity, IDstsLinkAlarmSettingSevirity)
    OIDincludeST(STstsLinkAlarmSettingSevirity)
    INTEGER_TYPE, SR_READ_WRITE, I_stsLinkAlarmSettingSevirity, 32,
    OIDaccess(stsLinkAlarmEntry_get, stsLinkAlarmEntry_test)
},
#endif	/* defined(I_stsLinkAlarmSettingSevirity) */

#if defined(I_stsLinkAlarmSevirity)
{
    OIDvalue(LNstsLinkAlarmSevirity, IDstsLinkAlarmSevirity)
    OIDincludeST(STstsLinkAlarmSevirity)
    INTEGER_TYPE, SR_READ_ONLY, I_stsLinkAlarmSevirity, 32,
    OIDaccess(stsLinkAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsLinkAlarmSevirity) */

#if defined(I_stsOscillatorAlarmSettingClock)
{
    OIDvalue(LNstsOscillatorAlarmSettingClock, IDstsOscillatorAlarmSettingClock)
    OIDincludeST(STstsOscillatorAlarmSettingClock)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOscillatorAlarmSettingClock, 32,
    OIDaccess(stsOscillatorAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorAlarmSettingClock) */

#if defined(I_stsOscillatorAlarmSettingType)
{
    OIDvalue(LNstsOscillatorAlarmSettingType, IDstsOscillatorAlarmSettingType)
    OIDincludeST(STstsOscillatorAlarmSettingType)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOscillatorAlarmSettingType, 32,
    OIDaccess(stsOscillatorAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorAlarmSettingType) */

#if defined(I_stsOscillatorAlarmSettingSeverity)
{
    OIDvalue(LNstsOscillatorAlarmSettingSeverity, IDstsOscillatorAlarmSettingSeverity)
    OIDincludeST(STstsOscillatorAlarmSettingSeverity)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOscillatorAlarmSettingSeverity, 32,
    OIDaccess(stsOscillatorAlarmEntry_get, stsOscillatorAlarmEntry_test)
},
#endif	/* defined(I_stsOscillatorAlarmSettingSeverity) */

#if defined(I_stsOscillatorAlarmSeverity)
{
    OIDvalue(LNstsOscillatorAlarmSeverity, IDstsOscillatorAlarmSeverity)
    OIDincludeST(STstsOscillatorAlarmSeverity)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOscillatorAlarmSeverity, 32,
    OIDaccess(stsOscillatorAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOscillatorAlarmSeverity) */

#if defined(I_stssPwrAlarmSettingShelf)
{
    OIDvalue(LNstssPwrAlarmSettingShelf, IDstssPwrAlarmSettingShelf)
    OIDincludeST(STstssPwrAlarmSettingShelf)
    INTEGER_TYPE, SR_READ_ONLY, I_stssPwrAlarmSettingShelf, 32,
    OIDaccess(stsOsPwrAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stssPwrAlarmSettingShelf) */

#if defined(I_stsOsPwrAlarmSettingOsPwr)
{
    OIDvalue(LNstsOsPwrAlarmSettingOsPwr, IDstsOsPwrAlarmSettingOsPwr)
    OIDincludeST(STstsOsPwrAlarmSettingOsPwr)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOsPwrAlarmSettingOsPwr, 32,
    OIDaccess(stsOsPwrAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOsPwrAlarmSettingOsPwr) */

#if defined(I_stsOsPwrAlarmSettingSeverity)
{
    OIDvalue(LNstsOsPwrAlarmSettingSeverity, IDstsOsPwrAlarmSettingSeverity)
    OIDincludeST(STstsOsPwrAlarmSettingSeverity)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOsPwrAlarmSettingSeverity, 32,
    OIDaccess(stsOsPwrAlarmEntry_get, stsOsPwrAlarmEntry_test)
},
#endif	/* defined(I_stsOsPwrAlarmSettingSeverity) */

#if defined(I_stsOsPwrAlarmSeverity)
{
    OIDvalue(LNstsOsPwrAlarmSeverity, IDstsOsPwrAlarmSeverity)
    OIDincludeST(STstsOsPwrAlarmSeverity)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOsPwrAlarmSeverity, 32,
    OIDaccess(stsOsPwrAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOsPwrAlarmSeverity) */

#if defined(I_stsOutputAlarmSettingShelf)
{
    OIDvalue(LNstsOutputAlarmSettingShelf, IDstsOutputAlarmSettingShelf)
    OIDincludeST(STstsOutputAlarmSettingShelf)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputAlarmSettingShelf, 32,
    OIDaccess(stsOutputAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputAlarmSettingShelf) */

#if defined(I_stsOutputAlarmSettingSlot)
{
    OIDvalue(LNstsOutputAlarmSettingSlot, IDstsOutputAlarmSettingSlot)
    OIDincludeST(STstsOutputAlarmSettingSlot)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputAlarmSettingSlot, 32,
    OIDaccess(stsOutputAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputAlarmSettingSlot) */

#if defined(I_stsOutputAlarmSettingPort)
{
    OIDvalue(LNstsOutputAlarmSettingPort, IDstsOutputAlarmSettingPort)
    OIDincludeST(STstsOutputAlarmSettingPort)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputAlarmSettingPort, 32,
    OIDaccess(stsOutputAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputAlarmSettingPort) */

#if defined(I_stsOutputAlarmSettingType)
{
    OIDvalue(LNstsOutputAlarmSettingType, IDstsOutputAlarmSettingType)
    OIDincludeST(STstsOutputAlarmSettingType)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputAlarmSettingType, 32,
    OIDaccess(stsOutputAlarmEntry_get, stsOutputAlarmEntry_test)
},
#endif	/* defined(I_stsOutputAlarmSettingType) */

#if defined(I_stsOutputAlarmSettingSeverity)
{
    OIDvalue(LNstsOutputAlarmSettingSeverity, IDstsOutputAlarmSettingSeverity)
    OIDincludeST(STstsOutputAlarmSettingSeverity)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputAlarmSettingSeverity, 32,
    OIDaccess(stsOutputAlarmEntry_get, stsOutputAlarmEntry_test)
},
#endif	/* defined(I_stsOutputAlarmSettingSeverity) */

#if defined(I_stsOutputAlarmSeverity)
{
    OIDvalue(LNstsOutputAlarmSeverity, IDstsOutputAlarmSeverity)
    OIDincludeST(STstsOutputAlarmSeverity)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputAlarmSeverity, 32,
    OIDaccess(stsOutputAlarmEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputAlarmSeverity) */

#if defined(I_stsOutputPortSettingShelf)
{
    OIDvalue(LNstsOutputPortSettingShelf, IDstsOutputPortSettingShelf)
    OIDincludeST(STstsOutputPortSettingShelf)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputPortSettingShelf, 32,
    OIDaccess(stsOutputPortSettingEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputPortSettingShelf) */

#if defined(I_stsOutputPortSettingSlot)
{
    OIDvalue(LNstsOutputPortSettingSlot, IDstsOutputPortSettingSlot)
    OIDincludeST(STstsOutputPortSettingSlot)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputPortSettingSlot, 32,
    OIDaccess(stsOutputPortSettingEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputPortSettingSlot) */

#if defined(I_stsOutputPortSettingPort)
{
    OIDvalue(LNstsOutputPortSettingPort, IDstsOutputPortSettingPort)
    OIDincludeST(STstsOutputPortSettingPort)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputPortSettingPort, 32,
    OIDaccess(stsOutputPortSettingEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputPortSettingPort) */

#if defined(I_stsOutputPortSettingType)
{
    OIDvalue(LNstsOutputPortSettingType, IDstsOutputPortSettingType)
    OIDincludeST(STstsOutputPortSettingType)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputPortSettingType, 32,
    OIDaccess(stsOutputPortSettingEntry_get, stsOutputPortSettingEntry_test)
},
#endif	/* defined(I_stsOutputPortSettingType) */

#if defined(I_stsOutputPortSettingName)
{
    OIDvalue(LNstsOutputPortSettingName, IDstsOutputPortSettingName)
    OIDincludeST(STstsOutputPortSettingName)
    OCTET_PRIM_TYPE, SR_READ_WRITE, I_stsOutputPortSettingName, 32,
    OIDaccess(stsOutputPortSettingEntry_get, stsOutputPortSettingEntry_test)
},
#endif	/* defined(I_stsOutputPortSettingName) */

#if defined(I_stsOutputTiuSettingShelf)
{
    OIDvalue(LNstsOutputTiuSettingShelf, IDstsOutputTiuSettingShelf)
    OIDincludeST(STstsOutputTiuSettingShelf)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputTiuSettingShelf, 32,
    OIDaccess(stsOutputTiuSettingEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputTiuSettingShelf) */

#if defined(I_stsOutputTiuSettingSlot)
{
    OIDvalue(LNstsOutputTiuSettingSlot, IDstsOutputTiuSettingSlot)
    OIDincludeST(STstsOutputTiuSettingSlot)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputTiuSettingSlot, 32,
    OIDaccess(stsOutputTiuSettingEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputTiuSettingSlot) */

#if defined(I_stsOutputTiuSettingPort)
{
    OIDvalue(LNstsOutputTiuSettingPort, IDstsOutputTiuSettingPort)
    OIDincludeST(STstsOutputTiuSettingPort)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputTiuSettingPort, 32,
    OIDaccess(stsOutputTiuSettingEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputTiuSettingPort) */

#if defined(I_stsOutputTiuSettingLineCoding)
{
    OIDvalue(LNstsOutputTiuSettingLineCoding, IDstsOutputTiuSettingLineCoding)
    OIDincludeST(STstsOutputTiuSettingLineCoding)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputTiuSettingLineCoding, 32,
    OIDaccess(stsOutputTiuSettingEntry_get, stsOutputTiuSettingEntry_test)
},
#endif	/* defined(I_stsOutputTiuSettingLineCoding) */

#if defined(I_stsOutputTiuSettingFMT)
{
    OIDvalue(LNstsOutputTiuSettingFMT, IDstsOutputTiuSettingFMT)
    OIDincludeST(STstsOutputTiuSettingFMT)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputTiuSettingFMT, 32,
    OIDaccess(stsOutputTiuSettingEntry_get, stsOutputTiuSettingEntry_test)
},
#endif	/* defined(I_stsOutputTiuSettingFMT) */

#if defined(I_stsOutputTiuSettingTermination)
{
    OIDvalue(LNstsOutputTiuSettingTermination, IDstsOutputTiuSettingTermination)
    OIDincludeST(STstsOutputTiuSettingTermination)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputTiuSettingTermination, 32,
    OIDaccess(stsOutputTiuSettingEntry_get, stsOutputTiuSettingEntry_test)
},
#endif	/* defined(I_stsOutputTiuSettingTermination) */

#if defined(I_stsPerfMonInputCurrentMon)
{
    OIDvalue(LNstsPerfMonInputCurrentMon, IDstsPerfMonInputCurrentMon)
    OIDincludeST(STstsPerfMonInputCurrentMon)
    INTEGER_TYPE, SR_READ_ONLY, I_stsPerfMonInputCurrentMon, 32,
    OIDaccess(stsPerfMonEntry_get, readOnly_test)
},
#endif	/* defined(I_stsPerfMonInputCurrentMon) */

#if defined(I_stsPerfMonInputMonPeriod)
{
    OIDvalue(LNstsPerfMonInputMonPeriod, IDstsPerfMonInputMonPeriod)
    OIDincludeST(STstsPerfMonInputMonPeriod)
    INTEGER_TYPE, SR_READ_ONLY, I_stsPerfMonInputMonPeriod, 32,
    OIDaccess(stsPerfMonEntry_get, readOnly_test)
},
#endif	/* defined(I_stsPerfMonInputMonPeriod) */

#if defined(I_stsPerfMonInputMonBucket)
{
    OIDvalue(LNstsPerfMonInputMonBucket, IDstsPerfMonInputMonBucket)
    OIDincludeST(STstsPerfMonInputMonBucket)
    INTEGER_TYPE, SR_READ_ONLY, I_stsPerfMonInputMonBucket, 32,
    OIDaccess(stsPerfMonEntry_get, readOnly_test)
},
#endif	/* defined(I_stsPerfMonInputMonBucket) */

#if defined(I_stsPerfMonInputMonType)
{
    OIDvalue(LNstsPerfMonInputMonType, IDstsPerfMonInputMonType)
    OIDincludeST(STstsPerfMonInputMonType)
    INTEGER_TYPE, SR_READ_ONLY, I_stsPerfMonInputMonType, 32,
    OIDaccess(stsPerfMonEntry_get, readOnly_test)
},
#endif	/* defined(I_stsPerfMonInputMonType) */

#if defined(I_stsPerfMonInputMonValue)
{
    OIDvalue(LNstsPerfMonInputMonValue, IDstsPerfMonInputMonValue)
    OIDincludeST(STstsPerfMonInputMonValue)
    INTEGER_TYPE, SR_READ_ONLY, I_stsPerfMonInputMonValue, 32,
    OIDaccess(stsPerfMonEntry_get, readOnly_test)
},
#endif	/* defined(I_stsPerfMonInputMonValue) */

#if defined(I_stsPerfMonInputClockType)
{
    OIDvalue(LNstsPerfMonInputClockType, IDstsPerfMonInputClockType)
    OIDincludeST(STstsPerfMonInputClockType)
    INTEGER_TYPE, SR_READ_ONLY, I_stsPerfMonInputClockType, 32,
    OIDaccess(stsPerfMonEntry_get, readOnly_test)
},
#endif	/* defined(I_stsPerfMonInputClockType) */

#if defined(I_stsTerminalIndex)
{
    OIDvalue(LNstsTerminalIndex, IDstsTerminalIndex)
    OIDincludeST(STstsTerminalIndex)
    INTEGER_TYPE, SR_READ_ONLY, I_stsTerminalIndex, 32,
    OIDaccess(stsTerminalEntry_get, readOnly_test)
},
#endif	/* defined(I_stsTerminalIndex) */

#if defined(I_stsTerminalBaudrate)
{
    OIDvalue(LNstsTerminalBaudrate, IDstsTerminalBaudrate)
    OIDincludeST(STstsTerminalBaudrate)
    INTEGER_TYPE, SR_READ_WRITE, I_stsTerminalBaudrate, 32,
    OIDaccess(stsTerminalEntry_get, stsTerminalEntry_test)
},
#endif	/* defined(I_stsTerminalBaudrate) */

#if defined(I_stsTerminalDataBits)
{
    OIDvalue(LNstsTerminalDataBits, IDstsTerminalDataBits)
    OIDincludeST(STstsTerminalDataBits)
    INTEGER_TYPE, SR_READ_WRITE, I_stsTerminalDataBits, 32,
    OIDaccess(stsTerminalEntry_get, stsTerminalEntry_test)
},
#endif	/* defined(I_stsTerminalDataBits) */

#if defined(I_stsTerminalParity)
{
    OIDvalue(LNstsTerminalParity, IDstsTerminalParity)
    OIDincludeST(STstsTerminalParity)
    INTEGER_TYPE, SR_READ_WRITE, I_stsTerminalParity, 32,
    OIDaccess(stsTerminalEntry_get, stsTerminalEntry_test)
},
#endif	/* defined(I_stsTerminalParity) */

#if defined(I_stsTerminalStopBits)
{
    OIDvalue(LNstsTerminalStopBits, IDstsTerminalStopBits)
    OIDincludeST(STstsTerminalStopBits)
    INTEGER_TYPE, SR_READ_WRITE, I_stsTerminalStopBits, 32,
    OIDaccess(stsTerminalEntry_get, stsTerminalEntry_test)
},
#endif	/* defined(I_stsTerminalStopBits) */

#if defined(I_stsAlarmSource)
{
    OIDvalue(LNstsAlarmSource, IDstsAlarmSource)
    OIDincludeST(STstsAlarmSource)
    INTEGER_TYPE, SR_READ_ONLY, I_stsAlarmSource, 32,
    OIDaccess(stsAlarmStatusEntry_get, readOnly_test)
},
#endif	/* defined(I_stsAlarmSource) */

#if defined(I_stsAlarmSourceType)
{
    OIDvalue(LNstsAlarmSourceType, IDstsAlarmSourceType)
    OIDincludeST(STstsAlarmSourceType)
    INTEGER_TYPE, SR_READ_ONLY, I_stsAlarmSourceType, 32,
    OIDaccess(stsAlarmStatusEntry_get, readOnly_test)
},
#endif	/* defined(I_stsAlarmSourceType) */

#if defined(I_stsAlarmSeverity)
{
    OIDvalue(LNstsAlarmSeverity, IDstsAlarmSeverity)
    OIDincludeST(STstsAlarmSeverity)
    INTEGER_TYPE, SR_READ_ONLY, I_stsAlarmSeverity, 32,
    OIDaccess(stsAlarmStatusEntry_get, readOnly_test)
},
#endif	/* defined(I_stsAlarmSeverity) */

#if defined(I_stsAlarmSrvEff)
{
    OIDvalue(LNstsAlarmSrvEff, IDstsAlarmSrvEff)
    OIDincludeST(STstsAlarmSrvEff)
    INTEGER_TYPE, SR_READ_ONLY, I_stsAlarmSrvEff, 32,
    OIDaccess(stsAlarmStatusEntry_get, readOnly_test)
},
#endif	/* defined(I_stsAlarmSrvEff) */

#if defined(I_stsOutputShelf)
{
    OIDvalue(LNstsOutputShelf, IDstsOutputShelf)
    OIDincludeST(STstsOutputShelf)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputShelf, 32,
    OIDaccess(stsOutputCardEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputShelf) */

#if defined(I_stsOutputSlot)
{
    OIDvalue(LNstsOutputSlot, IDstsOutputSlot)
    OIDincludeST(STstsOutputSlot)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputSlot, 32,
    OIDaccess(stsOutputCardEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputSlot) */

#if defined(I_stsOutputRedState)
{
    OIDvalue(LNstsOutputRedState, IDstsOutputRedState)
    OIDincludeST(STstsOutputRedState)
    INTEGER_TYPE, SR_READ_ONLY, I_stsOutputRedState, 32,
    OIDaccess(stsOutputCardEntry_get, readOnly_test)
},
#endif	/* defined(I_stsOutputRedState) */

#if defined(I_stsOutputRedEnableState)
{
    OIDvalue(LNstsOutputRedEnableState, IDstsOutputRedEnableState)
    OIDincludeST(STstsOutputRedEnableState)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputRedEnableState, 32,
    OIDaccess(stsOutputCardEntry_get, stsOutputCardEntry_test)
},
#endif	/* defined(I_stsOutputRedEnableState) */

#if defined(I_stsOutputRedSwitchState)
{
    OIDvalue(LNstsOutputRedSwitchState, IDstsOutputRedSwitchState)
    OIDincludeST(STstsOutputRedSwitchState)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputRedSwitchState, 32,
    OIDaccess(stsOutputCardEntry_get, stsOutputCardEntry_test)
},
#endif	/* defined(I_stsOutputRedSwitchState) */

#if defined(I_stsOutputCRCCHK)
{
    OIDvalue(LNstsOutputCRCCHK, IDstsOutputCRCCHK)
    OIDincludeST(STstsOutputCRCCHK)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputCRCCHK, 32,
    OIDaccess(stsOutputCardEntry_get, stsOutputCardEntry_test)
},
#endif	/* defined(I_stsOutputCRCCHK) */

#if defined(I_stsOutputCAS)
{
    OIDvalue(LNstsOutputCAS, IDstsOutputCAS)
    OIDincludeST(STstsOutputCAS)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputCAS, 32,
    OIDaccess(stsOutputCardEntry_get, stsOutputCardEntry_test)
},
#endif	/* defined(I_stsOutputCAS) */

#if defined(I_stsOutputSSM)
{
    OIDvalue(LNstsOutputSSM, IDstsOutputSSM)
    OIDincludeST(STstsOutputSSM)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputSSM, 32,
    OIDaccess(stsOutputCardEntry_get, stsOutputCardEntry_test)
},
#endif	/* defined(I_stsOutputSSM) */

#if defined(I_stsOutputSSMValue)
{
    OIDvalue(LNstsOutputSSMValue, IDstsOutputSSMValue)
    OIDincludeST(STstsOutputSSMValue)
    INTEGER_TYPE, SR_READ_WRITE, I_stsOutputSSMValue, 32,
    OIDaccess(stsOutputCardEntry_get, stsOutputCardEntry_test)
},
#endif	/* defined(I_stsOutputSSMValue) */

#if defined(I_stsOutputTimingFormat)
{
    OIDvalue(LNstsOutputTimingFormat, IDstsOutputTimingFormat)
    OIDincludeST(STstsOutputTimingFormat)
    OCTET_PRIM_TYPE, SR_READ_WRITE, I_stsOutputTimingFormat, 32,
    OIDaccess(stsOutputCardEntry_get, stsOutputCardEntry_test)
},
#endif	/* defined(I_stsOutputTimingFormat) */

#if defined(I_stsEmmShelf)
{
    OIDvalue(LNstsEmmShelf, IDstsEmmShelf)
    OIDincludeST(STstsEmmShelf)
    INTEGER_TYPE, SR_READ_ONLY, I_stsEmmShelf, 32,
    OIDaccess(stsEmmStatusEntry_get, readOnly_test)
},
#endif	/* defined(I_stsEmmShelf) */

#if defined(I_stsEmmSensorType)
{
    OIDvalue(LNstsEmmSensorType, IDstsEmmSensorType)
    OIDincludeST(STstsEmmSensorType)
    INTEGER_TYPE, SR_READ_ONLY, I_stsEmmSensorType, 32,
    OIDaccess(stsEmmStatusEntry_get, readOnly_test)
},
#endif	/* defined(I_stsEmmSensorType) */

#if defined(I_stsEmmAlarmStatus)
{
    OIDvalue(LNstsEmmAlarmStatus, IDstsEmmAlarmStatus)
    OIDincludeST(STstsEmmAlarmStatus)
    INTEGER_TYPE, SR_READ_ONLY, I_stsEmmAlarmStatus, 32,
    OIDaccess(stsEmmStatusEntry_get, readOnly_test)
},
#endif	/* defined(I_stsEmmAlarmStatus) */

#if defined(I_stsEmmSensorReading)
{
    OIDvalue(LNstsEmmSensorReading, IDstsEmmSensorReading)
    OIDincludeST(STstsEmmSensorReading)
    INTEGER_TYPE, SR_READ_ONLY, I_stsEmmSensorReading, 32,
    OIDaccess(stsEmmStatusEntry_get, readOnly_test)
},
#endif	/* defined(I_stsEmmSensorReading) */

#if defined(I_stsEmmMajorAlmHiThresh)
{
    OIDvalue(LNstsEmmMajorAlmHiThresh, IDstsEmmMajorAlmHiThresh)
    OIDincludeST(STstsEmmMajorAlmHiThresh)
    INTEGER_TYPE, SR_READ_WRITE, I_stsEmmMajorAlmHiThresh, 32,
    OIDaccess(stsEmmStatusEntry_get, stsEmmStatusEntry_test)
},
#endif	/* defined(I_stsEmmMajorAlmHiThresh) */

#if defined(I_stsEmmMajorAlmLoThresh)
{
    OIDvalue(LNstsEmmMajorAlmLoThresh, IDstsEmmMajorAlmLoThresh)
    OIDincludeST(STstsEmmMajorAlmLoThresh)
    INTEGER_TYPE, SR_READ_WRITE, I_stsEmmMajorAlmLoThresh, 32,
    OIDaccess(stsEmmStatusEntry_get, stsEmmStatusEntry_test)
},
#endif	/* defined(I_stsEmmMajorAlmLoThresh) */

#if defined(I_stsEmmMinorAlmHiThresh)
{
    OIDvalue(LNstsEmmMinorAlmHiThresh, IDstsEmmMinorAlmHiThresh)
    OIDincludeST(STstsEmmMinorAlmHiThresh)
    INTEGER_TYPE, SR_READ_WRITE, I_stsEmmMinorAlmHiThresh, 32,
    OIDaccess(stsEmmStatusEntry_get, stsEmmStatusEntry_test)
},
#endif	/* defined(I_stsEmmMinorAlmHiThresh) */

#if defined(I_stsEmmMinorAlmLoThresh)
{
    OIDvalue(LNstsEmmMinorAlmLoThresh, IDstsEmmMinorAlmLoThresh)
    OIDincludeST(STstsEmmMinorAlmLoThresh)
    INTEGER_TYPE, SR_READ_WRITE, I_stsEmmMinorAlmLoThresh, 32,
    OIDaccess(stsEmmStatusEntry_get, stsEmmStatusEntry_test)
},
#endif	/* defined(I_stsEmmMinorAlmLoThresh) */

#if defined(I_stsAntIndex)
{
    OIDvalue(LNstsAntIndex, IDstsAntIndex)
    OIDincludeST(STstsAntIndex)
    INTEGER_TYPE, SR_READ_ONLY, I_stsAntIndex, 32,
    OIDaccess(stsAntEntry_get, readOnly_test)
},
#endif	/* defined(I_stsAntIndex) */

#if defined(I_stsAntStatus)
{
    OIDvalue(LNstsAntStatus, IDstsAntStatus)
    OIDincludeST(STstsAntStatus)
    INTEGER_TYPE, SR_READ_ONLY, I_stsAntStatus, 32,
    OIDaccess(stsAntEntry_get, readOnly_test)
},
#endif	/* defined(I_stsAntStatus) */

#if defined(I_stsAntSwitchState)
{
    OIDvalue(LNstsAntSwitchState, IDstsAntSwitchState)
    OIDincludeST(STstsAntSwitchState)
    INTEGER_TYPE, SR_READ_WRITE, I_stsAntSwitchState, 32,
    OIDaccess(stsAntEntry_get, stsAntEntry_test)
},
#endif	/* defined(I_stsAntSwitchState) */

#if defined(I_stsTopDestNumber)
{
    OIDvalue(LNstsTopDestNumber, IDstsTopDestNumber)
    OIDincludeST(STstsTopDestNumber)
    INTEGER_TYPE, SR_READ_ONLY, I_stsTopDestNumber, 32,
    OIDaccess(stsTopDestEntry_get, readOnly_test)
},
#endif	/* defined(I_stsTopDestNumber) */

#if defined(I_stsTopDestIp)
{
    OIDvalue(LNstsTopDestIp, IDstsTopDestIp)
    OIDincludeST(STstsTopDestIp)
    IP_ADDR_PRIM_TYPE, SR_READ_WRITE, I_stsTopDestIp, 32,
    OIDaccess(stsTopDestEntry_get, stsTopDestEntry_test)
},
#endif	/* defined(I_stsTopDestIp) */

#if defined(I_stsTopDestUdpPort)
{
    OIDvalue(LNstsTopDestUdpPort, IDstsTopDestUdpPort)
    OIDincludeST(STstsTopDestUdpPort)
    INTEGER_TYPE, SR_READ_WRITE, I_stsTopDestUdpPort, 32,
    OIDaccess(stsTopDestEntry_get, stsTopDestEntry_test)
},
#endif	/* defined(I_stsTopDestUdpPort) */

#if defined(I_stsTopDestVlanId)
{
    OIDvalue(LNstsTopDestVlanId, IDstsTopDestVlanId)
    OIDincludeST(STstsTopDestVlanId)
    INTEGER_TYPE, SR_READ_WRITE, I_stsTopDestVlanId, 32,
    OIDaccess(stsTopDestEntry_get, stsTopDestEntry_test)
},
#endif	/* defined(I_stsTopDestVlanId) */

#if defined(I_stsTrapRegMgrNumber)
{
    OIDvalue(LNstsTrapRegMgrNumber, IDstsTrapRegMgrNumber)
    OIDincludeST(STstsTrapRegMgrNumber)
    INTEGER_TYPE, SR_READ_ONLY, I_stsTrapRegMgrNumber, 32,
    OIDaccess(stsTrapRegEntry_get, readOnly_test)
},
#endif	/* defined(I_stsTrapRegMgrNumber) */

#if defined(I_stsTrapRegMgrIp)
{
    OIDvalue(LNstsTrapRegMgrIp, IDstsTrapRegMgrIp)
    OIDincludeST(STstsTrapRegMgrIp)
    IP_ADDR_PRIM_TYPE, SR_READ_WRITE, I_stsTrapRegMgrIp, 32,
    OIDaccess(stsTrapRegEntry_get, stsTrapRegEntry_test)
},
#endif	/* defined(I_stsTrapRegMgrIp) */

#if defined(I_stsTrapRegMgrUdpPort)
{
    OIDvalue(LNstsTrapRegMgrUdpPort, IDstsTrapRegMgrUdpPort)
    OIDincludeST(STstsTrapRegMgrUdpPort)
    INTEGER_TYPE, SR_READ_WRITE, I_stsTrapRegMgrUdpPort, 32,
    OIDaccess(stsTrapRegEntry_get, stsTrapRegEntry_test)
},
#endif	/* defined(I_stsTrapRegMgrUdpPort) */

#if defined(I_stsTrapRegCommunityStr)
{
    OIDvalue(LNstsTrapRegCommunityStr, IDstsTrapRegCommunityStr)
    OIDincludeST(STstsTrapRegCommunityStr)
    OCTET_PRIM_TYPE, SR_READ_WRITE, I_stsTrapRegCommunityStr, 32,
    OIDaccess(stsTrapRegEntry_get, stsTrapRegEntry_test)
},
#endif	/* defined(I_stsTrapRegCommunityStr) */

#if defined(I_stsTrapRegState)
{
    OIDvalue(LNstsTrapRegState, IDstsTrapRegState)
    OIDincludeST(STstsTrapRegState)
    INTEGER_TYPE, SR_READ_WRITE, I_stsTrapRegState, 32,
    OIDaccess(stsTrapRegEntry_get, stsTrapRegEntry_test)
},
#endif	/* defined(I_stsTrapRegState) */

#if defined(I_stsClockPriIndex)
{
    OIDvalue(LNstsClockPriIndex, IDstsClockPriIndex)
    OIDincludeST(STstsClockPriIndex)
    INTEGER_TYPE, SR_READ_ONLY, I_stsClockPriIndex, 32,
    OIDaccess(stsClockPriEntry_get, readOnly_test)
},
#endif	/* defined(I_stsClockPriIndex) */

#if defined(I_stsClockPriSetting)
{
    OIDvalue(LNstsClockPriSetting, IDstsClockPriSetting)
    OIDincludeST(STstsClockPriSetting)
    INTEGER_TYPE, SR_READ_WRITE, I_stsClockPriSetting, 32,
    OIDaccess(stsClockPriEntry_get, stsClockPriEntry_test)
},
#endif	/* defined(I_stsClockPriSetting) */

