/*
 *
 * Copyright (C) 1992-2003 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -c LarusSts larusMib 
 */

/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_LARUSSTSMIB_H
#define SR_LARUSSTSMIB_H


#ifdef __cplusplus
extern "C" {
#endif

#ifdef SR_MIB_TABLE_HASHING
#define HASHNEXT(x) x, NULL
#else /* SR_MIB_TABLE_HASHING */
#define HASHNEXT(x) x
#endif /* SR_MIB_TABLE_HASHING */

/* SNMP-MIB translation table.  Subitem on left gets
 * translated into subitem on right.
 */

#ifndef LIGHT
static struct MIB_OID orig_mib_oid_table[] =
{
    { "larusMgmt",                       HASHNEXT("1.3.6.1.4.1.24628.2") },
    { "larusMib",                        HASHNEXT("1.3.6.1.4.1.24628.2.2") },
    { "stsSystem",                       HASHNEXT("1.3.6.1.4.1.24628.2.2.1") },
    { "stsSystemId",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.1.1") },
    { "stsSystemMgmtIpOption",           HASHNEXT("1.3.6.1.4.1.24628.2.2.1.2") },
    { "stsSystemMgmtIpAddress",          HASHNEXT("1.3.6.1.4.1.24628.2.2.1.3") },
    { "stsSystemMgmtIpSubnetMask",       HASHNEXT("1.3.6.1.4.1.24628.2.2.1.4") },
    { "stsSystemMgmtIpGatewayAddress",   HASHNEXT("1.3.6.1.4.1.24628.2.2.1.5") },
    { "stsSystemSntpIpOption",           HASHNEXT("1.3.6.1.4.1.24628.2.2.1.6") },
    { "stsSystemSntpIpAddress",          HASHNEXT("1.3.6.1.4.1.24628.2.2.1.7") },
    { "stsSystemSntpIpSubnetMask",       HASHNEXT("1.3.6.1.4.1.24628.2.2.1.8") },
    { "stsSystemSntpIpGatewayAddress",   HASHNEXT("1.3.6.1.4.1.24628.2.2.1.9") },
    { "stsSystemTime",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.1.10") },
    { "stsSystemTimeZone",               HASHNEXT("1.3.6.1.4.1.24628.2.2.1.11") },
    { "stsSystemIntegratedAlarm",        HASHNEXT("1.3.6.1.4.1.24628.2.2.1.12") },
    { "stsSystemAlarmAcoMode",           HASHNEXT("1.3.6.1.4.1.24628.2.2.1.13") },
    { "stsSystemAlarmAcoLed",            HASHNEXT("1.3.6.1.4.1.24628.2.2.1.14") },
    { "stsSystemAlarmAcoCutOff",         HASHNEXT("1.3.6.1.4.1.24628.2.2.1.15") },
    { "stsSystemAlarmEscalatingTime",    HASHNEXT("1.3.6.1.4.1.24628.2.2.1.16") },
    { "stsSystemMinorLED",               HASHNEXT("1.3.6.1.4.1.24628.2.2.1.17") },
    { "stsSystemMajorLED",               HASHNEXT("1.3.6.1.4.1.24628.2.2.1.18") },
    { "stsSystemCriticalLED",            HASHNEXT("1.3.6.1.4.1.24628.2.2.1.19") },
    { "stsSystemUpgradeSWAction",        HASHNEXT("1.3.6.1.4.1.24628.2.2.1.20") },
    { "stsSystemCurrentSWVersion",       HASHNEXT("1.3.6.1.4.1.24628.2.2.1.21") },
    { "stsSystemServiceState",           HASHNEXT("1.3.6.1.4.1.24628.2.2.1.22") },
    { "stsSystemWarmReset",              HASHNEXT("1.3.6.1.4.1.24628.2.2.1.23") },
    { "stsSystemColdReset",              HASHNEXT("1.3.6.1.4.1.24628.2.2.1.24") },
    { "stsSystemConfigReset",            HASHNEXT("1.3.6.1.4.1.24628.2.2.1.25") },
    { "stsClockInput",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.2") },
    { "stsClockInputManualSelect",       HASHNEXT("1.3.6.1.4.1.24628.2.2.2.1") },
    { "stsClockInputOperMode",           HASHNEXT("1.3.6.1.4.1.24628.2.2.2.2") },
    { "stsClockInputProtectedPri",       HASHNEXT("1.3.6.1.4.1.24628.2.2.2.3") },
    { "stsClockInputSetSlip",            HASHNEXT("1.3.6.1.4.1.24628.2.2.2.4") },
    { "stsClockInputType",               HASHNEXT("1.3.6.1.4.1.24628.2.2.2.5") },
    { "stsClockInputSSM",                HASHNEXT("1.3.6.1.4.1.24628.2.2.3") },
    { "stsClockInputSSMSelect",          HASHNEXT("1.3.6.1.4.1.24628.2.2.3.1") },
    { "stsTop",                          HASHNEXT("1.3.6.1.4.1.24628.2.2.4") },
    { "stsTopSourceIpOption",            HASHNEXT("1.3.6.1.4.1.24628.2.2.4.1") },
    { "stsTopSourceIpAddress",           HASHNEXT("1.3.6.1.4.1.24628.2.2.4.2") },
    { "stsTopSourceIpSubnetMask",        HASHNEXT("1.3.6.1.4.1.24628.2.2.4.3") },
    { "stsTopSourceIpGatewayAddress",    HASHNEXT("1.3.6.1.4.1.24628.2.2.4.4") },
    { "stsTopPacketRate",                HASHNEXT("1.3.6.1.4.1.24628.2.2.4.5") },
    { "stsTopInputSelect",               HASHNEXT("1.3.6.1.4.1.24628.2.2.4.6") },
    { "stsTopTxPackets",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.4.7") },
    { "stsTopTxBytes",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.4.8") },
    { "stsClockInputStatus",             HASHNEXT("1.3.6.1.4.1.24628.2.2.5") },
    { "stsClockInputStatusTable",        HASHNEXT("1.3.6.1.4.1.24628.2.2.5.1") },
    { "stsClockInputStatusEntry",        HASHNEXT("1.3.6.1.4.1.24628.2.2.5.1.1") },
    { "stsClockInputStatusIndex",        HASHNEXT("1.3.6.1.4.1.24628.2.2.5.1.1.1") },
    { "stsClockInputState",              HASHNEXT("1.3.6.1.4.1.24628.2.2.5.1.1.2") },
    { "stsClockInputSSMStatus",          HASHNEXT("1.3.6.1.4.1.24628.2.2.6") },
    { "stsClockInputSSMTable",           HASHNEXT("1.3.6.1.4.1.24628.2.2.6.1") },
    { "stsClockInputSSMEntry",           HASHNEXT("1.3.6.1.4.1.24628.2.2.6.1.1") },
    { "stsClockInputSSMIndex",           HASHNEXT("1.3.6.1.4.1.24628.2.2.6.1.1.1") },
    { "stsClockInputSSMType",            HASHNEXT("1.3.6.1.4.1.24628.2.2.6.1.1.2") },
    { "stsClockInputSSMValue",           HASHNEXT("1.3.6.1.4.1.24628.2.2.6.1.1.3") },
    { "stsCard",                         HASHNEXT("1.3.6.1.4.1.24628.2.2.7") },
    { "stsCardTable",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1") },
    { "stsCardEntry",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1") },
    { "stsCardShelf",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.1") },
    { "stsCardIndex",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.2") },
    { "stsCardType",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.3") },
    { "stsCardDescr",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.4") },
    { "stsCardSerial",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.5") },
    { "stsCardHwVersion",                HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.6") },
    { "stsCardCLEICode",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.7") },
    { "stsCardOperStatus",               HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.8") },
    { "stsCardReset",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.7.1.1.9") },
    { "stsOscillator",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.8") },
    { "stsOscillatorTable",              HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1") },
    { "stsOscillatorEntry",              HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1") },
    { "stsOscillatorIndex",              HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.1") },
    { "stsOscillatorModuleType",         HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.2") },
    { "stsOscillatorEFER",               HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.3") },
    { "stsOscillatorESSD",               HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.4") },
    { "stsOscillatorESSN",               HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.5") },
    { "stsOscillatorFAGE",               HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.6") },
    { "stsOscillatorTIMD",               HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.7") },
    { "stsOscillatorSetActive",          HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.8") },
    { "stsOscillatorStatus",             HASHNEXT("1.3.6.1.4.1.24628.2.2.8.1.1.9") },
    { "stsGPS",                          HASHNEXT("1.3.6.1.4.1.24628.2.2.9") },
    { "stsGpsTable",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1") },
    { "stsGpsEntry",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1") },
    { "stsGpsIndex",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.1") },
    { "stsGpsStatus",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.2") },
    { "stsGpsANTD",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.3") },
    { "stsGpsAZEL",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.4") },
    { "stsGpsRSTG",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.5") },
    { "stsGpsBITS",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.6") },
    { "stsGpsPAVG",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.7") },
    { "stsGpsSIGQ",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.8") },
    { "stsGpsSPOS",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.9") },
    { "stsGpsTRMO",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.10") },
    { "stsGpsUTCT",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.11") },
    { "stsGpsVERS",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.12") },
    { "stsGpsDETF",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.13") },
    { "stsGpsEFER",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.14") },
    { "stsGpsESSD",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.15") },
    { "stsGpsESSN",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.16") },
    { "stsGpsFAGE",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.17") },
    { "stsGpsTIMD",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.18") },
    { "stsGpsReset",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.9.1.1.19") },
    { "stsLink",                         HASHNEXT("1.3.6.1.4.1.24628.2.2.10") },
    { "stsLinkTable",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1") },
    { "stsLinkEntry",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1") },
    { "stsLinkIndex",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.1") },
    { "stsLinkType",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.2") },
    { "stsLinkEnable",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.3") },
    { "stsLinkLineCode",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.4") },
    { "stsLinkFMT",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.5") },
    { "stsLinkTermination",              HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.6") },
    { "stsLinkMFCHK",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.7") },
    { "stsLinkId",                       HASHNEXT("1.3.6.1.4.1.24628.2.2.10.1.1.8") },
    { "stsShelf",                        HASHNEXT("1.3.6.1.4.1.24628.2.2.11") },
    { "stsShelfTable",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1") },
    { "stsShelfEntry",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1.1") },
    { "stsShelfIndex",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1.1.1") },
    { "stsShelfSerial",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1.1.2") },
    { "stsShelfCLEICode",                HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1.1.3") },
    { "stsShelfReset",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.11.1.1.4") },
    { "stsAlarmThreshold",               HASHNEXT("1.3.6.1.4.1.24628.2.2.12") },
    { "stsAlarmThresholdTable",          HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1") },
    { "stsAlarmThresholdEntry",          HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1.1") },
    { "stsAlarmThresholdCurrentMon",     HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1.1.1") },
    { "stsAlarmThresholdType",           HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1.1.2") },
    { "stsAlarmThresholdValue",          HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1.1.3") },
    { "stsAlarmThresholdTimeInterval",   HASHNEXT("1.3.6.1.4.1.24628.2.2.12.1.1.4") },
    { "stsLinkAlarmSetting",             HASHNEXT("1.3.6.1.4.1.24628.2.2.13") },
    { "stsLinkAlarmTable",               HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1") },
    { "stsLinkAlarmEntry",               HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1.1") },
    { "stsLinkAlarmSettingLinkType",     HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1.1.1") },
    { "stsLinkAlarmSettingType",         HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1.1.2") },
    { "stsLinkAlarmSettingSevirity",     HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1.1.3") },
    { "stsLinkAlarmSevirity",            HASHNEXT("1.3.6.1.4.1.24628.2.2.13.1.1.4") },
    { "stsOscillatorAlarmSetting",       HASHNEXT("1.3.6.1.4.1.24628.2.2.14") },
    { "stsOscillatorAlarmTable",         HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1") },
    { "stsOscillatorAlarmEntry",         HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1.1") },
    { "stsOscillatorAlarmSettingClock",  HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1.1.1") },
    { "stsOscillatorAlarmSettingType",   HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1.1.2") },
    { "stsOscillatorAlarmSettingSeverity", HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1.1.3") },
    { "stsOscillatorAlarmSeverity",      HASHNEXT("1.3.6.1.4.1.24628.2.2.14.1.1.4") },
    { "stsOsPwrAlarmSetting",            HASHNEXT("1.3.6.1.4.1.24628.2.2.15") },
    { "stsOsPwrAlarmTable",              HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1") },
    { "stsOsPwrAlarmEntry",              HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1.1") },
    { "stssPwrAlarmSettingShelf",        HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1.1.1") },
    { "stsOsPwrAlarmSettingOsPwr",       HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1.1.2") },
    { "stsOsPwrAlarmSettingSeverity",    HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1.1.3") },
    { "stsOsPwrAlarmSeverity",           HASHNEXT("1.3.6.1.4.1.24628.2.2.15.1.1.4") },
    { "stsOutputAlarmSetting",           HASHNEXT("1.3.6.1.4.1.24628.2.2.16") },
    { "stsOutputAlarmTable",             HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1") },
    { "stsOutputAlarmEntry",             HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1") },
    { "stsOutputAlarmSettingShelf",      HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.1") },
    { "stsOutputAlarmSettingSlot",       HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.2") },
    { "stsOutputAlarmSettingPort",       HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.3") },
    { "stsOutputAlarmSettingType",       HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.4") },
    { "stsOutputAlarmSettingSeverity",   HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.5") },
    { "stsOutputAlarmSeverity",          HASHNEXT("1.3.6.1.4.1.24628.2.2.16.1.1.6") },
    { "stsOutputTiuSetting",             HASHNEXT("1.3.6.1.4.1.24628.2.2.17") },
    { "stsOutputTiuSettingTable",        HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1") },
    { "stsOutputTiuSettingEntry",        HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1") },
    { "stsOutputTiuSettingShelf",        HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.1") },
    { "stsOutputTiuSettingSlot",         HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.2") },
    { "stsOutputTiuSettingPort",         HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.3") },
    { "stsOutputTiuSettingLineCoding",   HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.4") },
    { "stsOutputTiuSettingFMT",          HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.5") },
    { "stsOutputTiuSettingTermination",  HASHNEXT("1.3.6.1.4.1.24628.2.2.17.1.1.6") },
    { "stsPerfMon",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.18") },
    { "stsPerfMonTable",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1") },
    { "stsPerfMonEntry",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1") },
    { "stsPerfMonInputCurrentMon",       HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.1") },
    { "stsPerfMonInputMonPeriod",        HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.2") },
    { "stsPerfMonInputMonBucket",        HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.3") },
    { "stsPerfMonInputClockType",        HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.4") },
    { "stsPerfMonPerfCVL",               HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.5") },
    { "stsPerfMonPerfCVP",               HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.6") },
    { "stsPerfMonPerfCS",                HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.7") },
    { "stsPerfMonPerfESP",               HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.8") },
    { "stsPerfMonPerfJitter",            HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.9") },
    { "stsPerfMonPerfPhaseData",         HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.10") },
    { "stsPerfMonPerfSESP",              HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.11") },
    { "stsPerfMonPerfTIE",               HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.12") },
    { "stsPerfMonPerfMTIE",              HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.13") },
    { "stsPerfMonPerfWDR5M",             HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.14") },
    { "stsPerfMonPerfWDR24H",            HASHNEXT("1.3.6.1.4.1.24628.2.2.18.1.1.15") },
    { "stsAlarmStatus",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.19") },
    { "stsAlarmStatusTable",             HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1") },
    { "stsAlarmStatusEntry",             HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1.1") },
    { "stsAlarmSource",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1.1.1") },
    { "stsAlarmSourceType",              HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1.1.2") },
    { "stsAlarmSeverity",                HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1.1.3") },
    { "stsAlarmSrvEff",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.19.1.1.4") },
    { "stsOutputCard",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.20") },
    { "stsOutputCardTable",              HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1") },
    { "stsOutputCardEntry",              HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1") },
    { "stsOutputShelf",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.1") },
    { "stsOutputSlot",                   HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.2") },
    { "stsOutputRedState",               HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.3") },
    { "stsOutputRedSwitchState",         HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.4") },
    { "stsOutputCRCCHK",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.5") },
    { "stsOutputCAS",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.6") },
    { "stsOutputSSM",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.7") },
    { "stsOutputSSMValue",               HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.8") },
    { "stsOutputTimingFormat",           HASHNEXT("1.3.6.1.4.1.24628.2.2.20.1.1.9") },
    { "stsEmmStatus",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.21") },
    { "stsEmmStatusTable",               HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1") },
    { "stsEmmStatusEntry",               HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1") },
    { "stsEmmShelf",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.1") },
    { "stsEmmUnitId",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.2") },
    { "stsEmmSensorType",                HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.3") },
    { "stsEmmAlarmStatus",               HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.4") },
    { "stsEmmSensorReading",             HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.5") },
    { "stsEmmMajorAlmHiThresh",          HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.6") },
    { "stsEmmMajorAlmLoThresh",          HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.7") },
    { "stsEmmMinorAlmHiThresh",          HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.8") },
    { "stsEmmMinorAlmLoThresh",          HASHNEXT("1.3.6.1.4.1.24628.2.2.21.1.1.9") },
    { "stsAnt",                          HASHNEXT("1.3.6.1.4.1.24628.2.2.22") },
    { "stsAntTable",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.22.1") },
    { "stsAntEntry",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.22.1.1") },
    { "stsAntIndex",                     HASHNEXT("1.3.6.1.4.1.24628.2.2.22.1.1.1") },
    { "stsAntStatus",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.22.1.1.2") },
    { "stsAntSwitchState",               HASHNEXT("1.3.6.1.4.1.24628.2.2.22.1.1.3") },
    { "stsTopDest",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.23") },
    { "stsTopDestTable",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1") },
    { "stsTopDestEntry",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1.1") },
    { "stsTopDestNumber",                HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1.1.1") },
    { "stsTopDestIp",                    HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1.1.2") },
    { "stsTopDestUdpPort",               HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1.1.3") },
    { "stsTopDestVlanId",                HASHNEXT("1.3.6.1.4.1.24628.2.2.23.1.1.4") },
    { "stsTrapReg",                      HASHNEXT("1.3.6.1.4.1.24628.2.2.24") },
    { "stsTrapRegTable",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1") },
    { "stsTrapRegEntry",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1") },
    { "stsTrapRegMgrNumber",             HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1.1") },
    { "stsTrapRegMgrIp",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1.2") },
    { "stsTrapRegMgrUdpPort",            HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1.3") },
    { "stsTrapRegCommunityStr",          HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1.4") },
    { "stsTrapRegState",                 HASHNEXT("1.3.6.1.4.1.24628.2.2.24.1.1.5") },
    { "stsTrap",                         HASHNEXT("1.3.6.1.4.1.24628.2.2.101") },
    { "stsSystemIpConfigChange",         HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1001") },
    { "stsSystemConfigChange",           HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1002") },
    { "stsSystemReset",                  HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1003") },
    { "stsSystemAlarmStatusChange",      HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1004") },
    { "stsSystemSWVersionChange",        HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1005") },
    { "stsClockInputChange",             HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1101") },
    { "stsClockInputStatusChange",       HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1102") },
    { "stsClockInputSSMConfigChange",    HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1103") },
    { "stsTopConfigChange",              HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1104") },
    { "stsTopDestConfigChange",          HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1105") },
    { "stsCardStatusChange",             HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1201") },
    { "stsOscillatorStatusChange",       HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1301") },
    { "stsGpsStatusChange",              HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1401") },
    { "stsLinkConfigChange",             HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1501") },
    { "stsAlarmThresholdConfigChange",   HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1601") },
    { "stsLinkAlarmSettingConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1701") },
    { "stsLinkAlarmStatusChange",        HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1702") },
    { "stsOscillatorAlarmSettingConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1801") },
    { "stsOscillatorAlarmStatusChange",  HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1802") },
    { "stsOsPwrAlarmSettingConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1901") },
    { "stsOsPwrAlarmStatusChange",       HASHNEXT("1.3.6.1.4.1.24628.2.2.101.1902") },
    { "stsOutputAlarmSettingConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2001") },
    { "stsOutputAlarmStatusChange",      HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2002") },
    { "stsOutputTiuSettingConfigChange", HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2003") },
    { "stsAlarmStatusChange",            HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2101") },
    { "stsOutputCardConfigChange",       HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2201") },
    { "stsEMMAlarmStatusChange",         HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2301") },
    { "stsEMMAlarmThresholdChange",      HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2302") },
    { "stsAntStatusChange",              HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2401") },
    { "stsTrapRegMgrConfigChange",       HASHNEXT("1.3.6.1.4.1.24628.2.2.101.2501") },
    { (char *) 0, HASHNEXT((char *) 0) }
};
#else /* LIGHT */
static struct MIB_OID orig_mib_oid_table[] =
{
    { "snmpResearch",                    HASHNEXT("1.3.6.1.4.1.99") },
    { (char *) 0, HASHNEXT((char *) 0) }
};
#endif /* LIGHT */



/* Don't put anything after this #endif */ 

#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_LARUSSTSMIB_H */
