/*
 *
 * Copyright (C) 1992-2003 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -search_table (implies -row_status) -c LarusSts larusMib -agent -per_file_init 
 * 
 */

/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_LARUSSTSDEFS_H
#define SR_LARUSSTSDEFS_H


#ifdef __cplusplus
extern "C" {
#endif

/* enumerated values for stsSystemMgmtIpOption */
#define D_stsSystemMgmtIpOption_static 1
#define D_stsSystemMgmtIpOption_dhcp   2

/* enumerated values for stsSystemSntpIpOption */
#define D_stsSystemSntpIpOption_static 1
#define D_stsSystemSntpIpOption_dhcp   2

/* enumerated values for stsSystemTimeZone */
#define D_stsSystemTimeZone_gmtplus12  1
#define D_stsSystemTimeZone_gmtplus11  2
#define D_stsSystemTimeZone_gmtplus10  3
#define D_stsSystemTimeZone_gmtplus09  4
#define D_stsSystemTimeZone_gmtplus08  5
#define D_stsSystemTimeZone_gmtplus07  6
#define D_stsSystemTimeZone_gmtplus06  7
#define D_stsSystemTimeZone_gmtplus05  8
#define D_stsSystemTimeZone_gmtplus04  9
#define D_stsSystemTimeZone_gmtplus03  10
#define D_stsSystemTimeZone_gmtplus02  11
#define D_stsSystemTimeZone_gmtplus01  12
#define D_stsSystemTimeZone_gmt        13
#define D_stsSystemTimeZone_gmtminus01 14
#define D_stsSystemTimeZone_gmtminus02 15
#define D_stsSystemTimeZone_gmtminus03 16
#define D_stsSystemTimeZone_gmtminus04 17
#define D_stsSystemTimeZone_gmtminus05 18
#define D_stsSystemTimeZone_gmtminus06 19
#define D_stsSystemTimeZone_gmtminus07 20
#define D_stsSystemTimeZone_gmtminus08 21
#define D_stsSystemTimeZone_gmtminus09 22
#define D_stsSystemTimeZone_gmtminus10 23
#define D_stsSystemTimeZone_gmtminus11 24
#define D_stsSystemTimeZone_gmtminus12 25

/* enumerated values for stsSystemIntegratedAlarm */
#define D_stsSystemIntegratedAlarm_clear 1
#define D_stsSystemIntegratedAlarm_minor 2
#define D_stsSystemIntegratedAlarm_major 3
#define D_stsSystemIntegratedAlarm_critical 4

/* enumerated values for stsSystemAlarmAcoMode */
#define D_stsSystemAlarmAcoMode_manual 1
#define D_stsSystemAlarmAcoMode_auto   2

/* enumerated values for stsSystemAlarmAcoLed */
#define D_stsSystemAlarmAcoLed_on      1
#define D_stsSystemAlarmAcoLed_off     2

/* enumerated values for stsSystemAlarmAcoCutOff */
#define D_stsSystemAlarmAcoCutOff_no_change 1
#define D_stsSystemAlarmAcoCutOff_cutoff 2

/* enumerated values for stsSystemMinorLED */
#define D_stsSystemMinorLED_off        1
#define D_stsSystemMinorLED_on         2

/* enumerated values for stsSystemMajorLED */
#define D_stsSystemMajorLED_off        1
#define D_stsSystemMajorLED_on         2

/* enumerated values for stsSystemCriticalLED */
#define D_stsSystemCriticalLED_off     1
#define D_stsSystemCriticalLED_on      2

/* enumerated values for stsSystemUpgradeSWAction */
#define D_stsSystemUpgradeSWAction_no_action 1
#define D_stsSystemUpgradeSWAction_upgrade 2

/* enumerated values for stsSystemServiceState */
#define D_stsSystemServiceState_init   1
#define D_stsSystemServiceState_inService 2
#define D_stsSystemServiceState_outOfService 3

/* enumerated values for stsSystemWarmReset */
#define D_stsSystemWarmReset_noAction  1
#define D_stsSystemWarmReset_reset     2

/* enumerated values for stsSystemColdReset */
#define D_stsSystemColdReset_noAction  1
#define D_stsSystemColdReset_reset     2

/* enumerated values for stsSystemConfigReset */
#define D_stsSystemConfigReset_noAction 1
#define D_stsSystemConfigReset_reset   2

/* enumerated values for stsClockInputManualSelect */
#define D_stsClockInputManualSelect_esr1 1
#define D_stsClockInputManualSelect_esr2 2
#define D_stsClockInputManualSelect_prs 3
#define D_stsClockInputManualSelect_input1 4
#define D_stsClockInputManualSelect_input2 5

/* enumerated values for stsClockInputOperMode */
#define D_stsClockInputOperMode_protected 1
#define D_stsClockInputOperMode_manual 2

/* enumerated values for stsClockInputProtectedPri */
#define D_stsClockInputProtectedPri_esr 1
#define D_stsClockInputProtectedPri_input 2
#define D_stsClockInputProtectedPri_prs 3

/* enumerated values for stsClockInputSetSlip */
#define D_stsClockInputSetSlip_betweenTwoClockModule 1
#define D_stsClockInputSetSlip_active_input1 2
#define D_stsClockInputSetSlip_active_input2 3
#define D_stsClockInputSetSlip_active_input3 4
#define D_stsClockInputSetSlip_active_input4 5
#define D_stsClockInputSetSlip_active_input5 6

/* enumerated values for stsClockInputType */
#define D_stsClockInputType_stratum1   1
#define D_stsClockInputType_stratum2   2
#define D_stsClockInputType_stratum3   3

/* enumerated values for stsClockInputSSMSelect */
#define D_stsClockInputSSMSelect_e1_sa4_ssm 1
#define D_stsClockInputSSMSelect_e1_sa5_ssm 2
#define D_stsClockInputSSMSelect_e1_sa6_ssm 3
#define D_stsClockInputSSMSelect_e1_sa7_ssm 4
#define D_stsClockInputSSMSelect_e1_sa8_ssm 5
#define D_stsClockInputSSMSelect_t1_ssm 6

/* enumerated values for stsTopSourceIpOption */
#define D_stsTopSourceIpOption_static  1
#define D_stsTopSourceIpOption_dhcp    2

/* enumerated values for stsTopInputSelect */
#define D_stsTopInputSelect_e1         1
#define D_stsTopInputSelect_t1         2
#define D_stsTopInputSelect_cc         3

/* enumerated values for stsClockInputStatusIndex */
#define D_stsClockInputStatusIndex_esr1 1
#define D_stsClockInputStatusIndex_esr2 2
#define D_stsClockInputStatusIndex_prs 3
#define D_stsClockInputStatusIndex_input1 4
#define D_stsClockInputStatusIndex_input2 5

/* enumerated values for stsClockInputState */
#define D_stsClockInputState_active    1
#define D_stsClockInputState_standby   2
#define D_stsClockInputState_down      3
#define D_stsClockInputState_recovering 4

/* enumerated values for stsClockInputSSMIndex */
#define D_stsClockInputSSMIndex_input1 1
#define D_stsClockInputSSMIndex_input2 2

/* enumerated values for stsClockInputSSMType */
#define D_stsClockInputSSMType_e1_sa4_ssm 1
#define D_stsClockInputSSMType_e1_sa5_ssm 2
#define D_stsClockInputSSMType_e1_sa6_ssm 3
#define D_stsClockInputSSMType_e1_sa7_ssm 4
#define D_stsClockInputSSMType_e1_sa8_ssm 5
#define D_stsClockInputSSMType_t1_ssm  6

/* enumerated values for stsClockInputSSMValue */
#define D_stsClockInputSSMValue_prs    1
#define D_stsClockInputSSMValue_stu    2
#define D_stsClockInputSSMValue_st2    3
#define D_stsClockInputSSMValue_st3    4
#define D_stsClockInputSSMValue_sic    5
#define D_stsClockInputSSMValue_duc    6

/* enumerated values for stsCardShelf */
#define D_stsCardShelf_main            100
#define D_stsCardShelf_expansion_1     1
#define D_stsCardShelf_expansion_2     2
#define D_stsCardShelf_expansion_3     3
#define D_stsCardShelf_expansion_4     4

/* enumerated values for stsCardIndex */
#define D_stsCardIndex_output1         1
#define D_stsCardIndex_output2         2
#define D_stsCardIndex_output3         3
#define D_stsCardIndex_output4         4
#define D_stsCardIndex_output5         5
#define D_stsCardIndex_output6         6
#define D_stsCardIndex_output7         7
#define D_stsCardIndex_output8         8
#define D_stsCardIndex_output9         9
#define D_stsCardIndex_output10        10
#define D_stsCardIndex_output11        11
#define D_stsCardIndex_output12        12
#define D_stsCardIndex_output13        13
#define D_stsCardIndex_output14        14
#define D_stsCardIndex_output15        15
#define D_stsCardIndex_output16        16
#define D_stsCardIndex_esr1            17
#define D_stsCardIndex_esr2            18
#define D_stsCardIndex_smu             19
#define D_stsCardIndex_oscillator1     20
#define D_stsCardIndex_oscillator2     21
#define D_stsCardIndex_top             22
#define D_stsCardIndex_imu             23

/* enumerated values for stsCardType */
#define D_stsCardType_cardTypeSmu      1
#define D_stsCardType_cardTypeOutputFrequency 2
#define D_stsCardType_cardTypeOutputIrig_B 3
#define D_stsCardType_cardTypeOutputTiming 4
#define D_stsCardType_cardTypeOutputTiu 5
#define D_stsCardType_cardTypeOutputF5F10 6
#define D_stsCardType_cardTypeOutputTop 7
#define D_stsCardType_cardTypeGpsCdma  8
#define D_stsCardType_cardTypeGpsFrequency 9
#define D_stsCardType_cardTypeGpsUmts  10
#define D_stsCardType_cardTypeGpsGsm   11
#define D_stsCardType_cardTypeClkRb    12
#define D_stsCardType_cardTypeClkCrystalSt2 13
#define D_stsCardType_cardTypeClkCrystalSt3 14
#define D_stsCardType_cardTypeClkCrystal 15
#define D_stsCardType_cardTypeImu      16

/* enumerated values for stsCardOperStatus */
#define D_stsCardOperStatus_active     1
#define D_stsCardOperStatus_standby    2
#define D_stsCardOperStatus_failed     3
#define D_stsCardOperStatus_notPresent 4
#define D_stsCardOperStatus_misMatch   5

/* enumerated values for stsCardReset */
#define D_stsCardReset_noAction        1
#define D_stsCardReset_reset           2

/* enumerated values for stsOscillatorIndex */
#define D_stsOscillatorIndex_oscillator1 1
#define D_stsOscillatorIndex_oscillator2 2

/* enumerated values for stsOscillatorModuleType */
#define D_stsOscillatorModuleType_rb   1
#define D_stsOscillatorModuleType_crystalSt2 2
#define D_stsOscillatorModuleType_crystalSt3 3
#define D_stsOscillatorModuleType_crystal 4

/* enumerated values for stsOscillatorSetActive */
#define D_stsOscillatorSetActive_noAction 1
#define D_stsOscillatorSetActive_active 2

/* enumerated values for stsOscillatorStatus */
#define D_stsOscillatorStatus_active   1
#define D_stsOscillatorStatus_standby  2
#define D_stsOscillatorStatus_holdoversync 3
#define D_stsOscillatorStatus_aqrsync  4
#define D_stsOscillatorStatus_frngsync 5
#define D_stsOscillatorStatus_lkdsync  6
#define D_stsOscillatorStatus_absent   7

/* enumerated values for stsGpsIndex */
#define D_stsGpsIndex_esr1             1
#define D_stsGpsIndex_esr2             2

/* enumerated values for stsGpsStatus */
#define D_stsGpsStatus_active          1
#define D_stsGpsStatus_standby         2

/* enumerated values for stsGpsReset */
#define D_stsGpsReset_noAction         0
#define D_stsGpsReset_reset            1

/* enumerated values for stsLinkIndex */
#define D_stsLinkIndex_mon1            1
#define D_stsLinkIndex_mon2            2
#define D_stsLinkIndex_mon3            3
#define D_stsLinkIndex_mon4            4
#define D_stsLinkIndex_mon5            5

/* enumerated values for stsLinkType */
#define D_stsLinkType_e1               1
#define D_stsLinkType_t1               2
#define D_stsLinkType_cc               3
#define D_stsLinkType_f2               4
#define D_stsLinkType_j1               5

/* enumerated values for stsLinkEnable */
#define D_stsLinkEnable_yes            1
#define D_stsLinkEnable_no             2

/* enumerated values for stsLinkLineCode */
#define D_stsLinkLineCode_ami          1
#define D_stsLinkLineCode_b8zs         2
#define D_stsLinkLineCode_hdb3         3
#define D_stsLinkLineCode_zbtsi        4
#define D_stsLinkLineCode_jbzs         5
#define D_stsLinkLineCode_other        6

/* enumerated values for stsLinkFMT */
#define D_stsLinkFMT_t1_d4             1
#define D_stsLinkFMT_t1_esf            2
#define D_stsLinkFMT_j1_d4             3
#define D_stsLinkFMT_j1_esf            4
#define D_stsLinkFMT_e1                5
#define D_stsLinkFMT_e1_crc            6
#define D_stsLinkFMT_e1_mf             7
#define D_stsLinkFMT_e1_crc_mf         8
#define D_stsLinkFMT_f2                9
#define D_stsLinkFMT_cc                10
#define D_stsLinkFMT_cc_400            11

/* enumerated values for stsLinkTermination */
#define D_stsLinkTermination_ohm_75    1
#define D_stsLinkTermination_ohm_100   2
#define D_stsLinkTermination_ohm_110   3
#define D_stsLinkTermination_ohm_120   4

/* enumerated values for stsLinkMFCHK */
#define D_stsLinkMFCHK_enable          1
#define D_stsLinkMFCHK_disable         2

/* enumerated values for stsShelfIndex */
#define D_stsShelfIndex_main           100
#define D_stsShelfIndex_expansion_1    1
#define D_stsShelfIndex_expansion_2    2
#define D_stsShelfIndex_expansion_3    3
#define D_stsShelfIndex_expansion_4    4

/* enumerated values for stsShelfReset */
#define D_stsShelfReset_noAction       1
#define D_stsShelfReset_reset          2

/* enumerated values for stsAlarmThresholdCurrentMon */
#define D_stsAlarmThresholdCurrentMon_mon1 1
#define D_stsAlarmThresholdCurrentMon_mon2 2
#define D_stsAlarmThresholdCurrentMon_mon3 3
#define D_stsAlarmThresholdCurrentMon_mon4 4
#define D_stsAlarmThresholdCurrentMon_mon5 5

/* enumerated values for stsAlarmThresholdType */
#define D_stsAlarmThresholdType_cvl    1
#define D_stsAlarmThresholdType_cvp    2
#define D_stsAlarmThresholdType_cs     3
#define D_stsAlarmThresholdType_jitter 4
#define D_stsAlarmThresholdType_tie    5
#define D_stsAlarmThresholdType_mtie   6
#define D_stsAlarmThresholdType_wander 7

/* enumerated values for stsAlarmThresholdTimeInterval */
#define D_stsAlarmThresholdTimeInterval_one_Sec 1
#define D_stsAlarmThresholdTimeInterval_ten_Sec 2
#define D_stsAlarmThresholdTimeInterval_hundred_Sec 3
#define D_stsAlarmThresholdTimeInterval_thousand_Sec 4
#define D_stsAlarmThresholdTimeInterval_tenThousand_Sec 5
#define D_stsAlarmThresholdTimeInterval_hundredThousand_Sec 6
#define D_stsAlarmThresholdTimeInterval_one_Hour 7
#define D_stsAlarmThresholdTimeInterval_one_Day 8

/* enumerated values for stsLinkAlarmSettingLinkType */
#define D_stsLinkAlarmSettingLinkType_mon1 1
#define D_stsLinkAlarmSettingLinkType_mon2 2
#define D_stsLinkAlarmSettingLinkType_mon3 3
#define D_stsLinkAlarmSettingLinkType_mon4 4
#define D_stsLinkAlarmSettingLinkType_mon5 5
#define D_stsLinkAlarmSettingLinkType_f5F10 6
#define D_stsLinkAlarmSettingLinkType_plnk 7
#define D_stsLinkAlarmSettingLinkType_slnk 8

/* enumerated values for stsLinkAlarmSettingType */
#define D_stsLinkAlarmSettingType_act  1
#define D_stsLinkAlarmSettingType_los  2
#define D_stsLinkAlarmSettingType_aisp 3
#define D_stsLinkAlarmSettingType_lof  4
#define D_stsLinkAlarmSettingType_cvl  5
#define D_stsLinkAlarmSettingType_cvp  6
#define D_stsLinkAlarmSettingType_cs   7
#define D_stsLinkAlarmSettingType_jitter 8
#define D_stsLinkAlarmSettingType_tie  9
#define D_stsLinkAlarmSettingType_mtie 10

/* enumerated values for stsLinkAlarmSettingSevirity */
#define D_stsLinkAlarmSettingSevirity_cr 1
#define D_stsLinkAlarmSettingSevirity_mj 2
#define D_stsLinkAlarmSettingSevirity_mn 3
#define D_stsLinkAlarmSettingSevirity_na 4
#define D_stsLinkAlarmSettingSevirity_nr 5

/* enumerated values for stsLinkAlarmSevirity */
#define D_stsLinkAlarmSevirity_cr      1
#define D_stsLinkAlarmSevirity_mj      2
#define D_stsLinkAlarmSevirity_mn      3
#define D_stsLinkAlarmSevirity_na      4
#define D_stsLinkAlarmSevirity_nr      5
#define D_stsLinkAlarmSevirity_cl      6

/* enumerated values for stsOscillatorAlarmSettingClock */
#define D_stsOscillatorAlarmSettingClock_oscillator1 1
#define D_stsOscillatorAlarmSettingClock_oscillator2 2
#define D_stsOscillatorAlarmSettingClock_all 3

/* enumerated values for stsOscillatorAlarmSettingType */
#define D_stsOscillatorAlarmSettingType_aqrsync 1
#define D_stsOscillatorAlarmSettingType_frngsync 2
#define D_stsOscillatorAlarmSettingType_hldovrsync 3
#define D_stsOscillatorAlarmSettingType_lkdsync 4
#define D_stsOscillatorAlarmSettingType_act 5

/* enumerated values for stsOscillatorAlarmSettingSeverity */
#define D_stsOscillatorAlarmSettingSeverity_cr 1
#define D_stsOscillatorAlarmSettingSeverity_mj 2
#define D_stsOscillatorAlarmSettingSeverity_mn 3
#define D_stsOscillatorAlarmSettingSeverity_na 4
#define D_stsOscillatorAlarmSettingSeverity_nr 5

/* enumerated values for stsOscillatorAlarmSeverity */
#define D_stsOscillatorAlarmSeverity_cr 1
#define D_stsOscillatorAlarmSeverity_mj 2
#define D_stsOscillatorAlarmSeverity_mn 3
#define D_stsOscillatorAlarmSeverity_na 4
#define D_stsOscillatorAlarmSeverity_nr 5
#define D_stsOscillatorAlarmSeverity_cl 6

/* enumerated values for stssPwrAlarmSettingShelf */
#define D_stssPwrAlarmSettingShelf_main 100
#define D_stssPwrAlarmSettingShelf_expansion_1 1
#define D_stssPwrAlarmSettingShelf_expansion_2 2
#define D_stssPwrAlarmSettingShelf_expansion_3 3
#define D_stssPwrAlarmSettingShelf_expansion_4 4

/* enumerated values for stsOsPwrAlarmSettingOsPwr */
#define D_stsOsPwrAlarmSettingOsPwr_os_oslink_failure 1
#define D_stsOsPwrAlarmSettingOsPwr_pwrA_failure 2
#define D_stsOsPwrAlarmSettingOsPwr_pwrB_failure 3

/* enumerated values for stsOsPwrAlarmSettingSeverity */
#define D_stsOsPwrAlarmSettingSeverity_cr 1
#define D_stsOsPwrAlarmSettingSeverity_mj 2
#define D_stsOsPwrAlarmSettingSeverity_mn 3
#define D_stsOsPwrAlarmSettingSeverity_na 4
#define D_stsOsPwrAlarmSettingSeverity_nr 5

/* enumerated values for stsOsPwrAlarmSeverity */
#define D_stsOsPwrAlarmSeverity_cr     1
#define D_stsOsPwrAlarmSeverity_mj     2
#define D_stsOsPwrAlarmSeverity_mn     3
#define D_stsOsPwrAlarmSeverity_na     4
#define D_stsOsPwrAlarmSeverity_nr     5
#define D_stsOsPwrAlarmSeverity_cl     6

/* enumerated values for stsOutputAlarmSettingShelf */
#define D_stsOutputAlarmSettingShelf_main 100
#define D_stsOutputAlarmSettingShelf_expansion_1 1
#define D_stsOutputAlarmSettingShelf_expansion_2 2
#define D_stsOutputAlarmSettingShelf_expansion_3 3
#define D_stsOutputAlarmSettingShelf_expansion_4 4

/* enumerated values for stsOutputAlarmSettingType */
#define D_stsOutputAlarmSettingType_lossClock 1
#define D_stsOutputAlarmSettingType_tiu_act 2
#define D_stsOutputAlarmSettingType_tiu_los 3
#define D_stsOutputAlarmSettingType_tiu_t_tie 4
#define D_stsOutputAlarmSettingType_tiu_t_mtie 5
#define D_stsOutputAlarmSettingType_tiu_aisp 6
#define D_stsOutputAlarmSettingType_tiu_lof 7
#define D_stsOutputAlarmSettingType_tiu_t_cs 8

/* enumerated values for stsOutputAlarmSettingSeverity */
#define D_stsOutputAlarmSettingSeverity_cr 1
#define D_stsOutputAlarmSettingSeverity_mj 2
#define D_stsOutputAlarmSettingSeverity_mn 3
#define D_stsOutputAlarmSettingSeverity_na 4
#define D_stsOutputAlarmSettingSeverity_nr 5

/* enumerated values for stsOutputAlarmSeverity */
#define D_stsOutputAlarmSeverity_cr    1
#define D_stsOutputAlarmSeverity_mj    2
#define D_stsOutputAlarmSeverity_mn    3
#define D_stsOutputAlarmSeverity_na    4
#define D_stsOutputAlarmSeverity_nr    5
#define D_stsOutputAlarmSeverity_cl    6

/* enumerated values for stsOutputTiuSettingShelf */
#define D_stsOutputTiuSettingShelf_main 100
#define D_stsOutputTiuSettingShelf_expansion_1 1
#define D_stsOutputTiuSettingShelf_expansion_2 2
#define D_stsOutputTiuSettingShelf_expansion_3 3
#define D_stsOutputTiuSettingShelf_expansion_4 4

/* enumerated values for stsOutputTiuSettingLineCoding */
#define D_stsOutputTiuSettingLineCoding_ami 1
#define D_stsOutputTiuSettingLineCoding_b8zs 2
#define D_stsOutputTiuSettingLineCoding_hdb3 3
#define D_stsOutputTiuSettingLineCoding_other 4

/* enumerated values for stsOutputTiuSettingFMT */
#define D_stsOutputTiuSettingFMT_t1_d4 1
#define D_stsOutputTiuSettingFMT_t1_esf 2
#define D_stsOutputTiuSettingFMT_j1_d4 3
#define D_stsOutputTiuSettingFMT_j1_esf 4

/* enumerated values for stsOutputTiuSettingTermination */
#define D_stsOutputTiuSettingTermination_ohm_75 1
#define D_stsOutputTiuSettingTermination_ohm_100 2
#define D_stsOutputTiuSettingTermination_ohm_110 3
#define D_stsOutputTiuSettingTermination_ohm_120 4

/* enumerated values for stsPerfMonInputCurrentMon */
#define D_stsPerfMonInputCurrentMon_mon1 1
#define D_stsPerfMonInputCurrentMon_mon2 2
#define D_stsPerfMonInputCurrentMon_mon3 3
#define D_stsPerfMonInputCurrentMon_mon4 4
#define D_stsPerfMonInputCurrentMon_mon5 5

/* enumerated values for stsPerfMonInputMonPeriod */
#define D_stsPerfMonInputMonPeriod_one_hour 1
#define D_stsPerfMonInputMonPeriod_one_day 2
#define D_stsPerfMonInputMonPeriod_hundred_Sec 3

/* enumerated values for stsPerfMonInputClockType */
#define D_stsPerfMonInputClockType_unknown 1
#define D_stsPerfMonInputClockType_t1  2
#define D_stsPerfMonInputClockType_e1  3
#define D_stsPerfMonInputClockType_cc  4
#define D_stsPerfMonInputClockType_f2  5
#define D_stsPerfMonInputClockType_f5  6
#define D_stsPerfMonInputClockType_f10 7

/* enumerated values for stsAlarmSource */
#define D_stsAlarmSource_clk1          1
#define D_stsAlarmSource_clk2          2
#define D_stsAlarmSource_pwr           3
#define D_stsAlarmSource_os            4
#define D_stsAlarmSource_plnk          5
#define D_stsAlarmSource_slnk          6
#define D_stsAlarmSource_f10           7
#define D_stsAlarmSource_mon1          8
#define D_stsAlarmSource_mon2          9
#define D_stsAlarmSource_mon3          10
#define D_stsAlarmSource_mon4          11
#define D_stsAlarmSource_mon5          12
#define D_stsAlarmSource_esr1          13
#define D_stsAlarmSource_esr2          14

/* enumerated values for stsAlarmSourceType */
#define D_stsAlarmSourceType_eqpt      1
#define D_stsAlarmSourceType_link      2
#define D_stsAlarmSourceType_com       3

/* enumerated values for stsAlarmSeverity */
#define D_stsAlarmSeverity_cr          1
#define D_stsAlarmSeverity_mj          2
#define D_stsAlarmSeverity_mn          3
#define D_stsAlarmSeverity_na          4
#define D_stsAlarmSeverity_nr          5
#define D_stsAlarmSeverity_cl          6

/* enumerated values for stsAlarmSrvEff */
#define D_stsAlarmSrvEff_sa            1
#define D_stsAlarmSrvEff_nsa           2

/* enumerated values for stsOutputShelf */
#define D_stsOutputShelf_main          100
#define D_stsOutputShelf_expansion_1   1
#define D_stsOutputShelf_expansion_2   2
#define D_stsOutputShelf_expansion_3   3
#define D_stsOutputShelf_expansion_4   4

/* enumerated values for stsOutputRedState */
#define D_stsOutputRedState_active     1
#define D_stsOutputRedState_standby    2

/* enumerated values for stsOutputRedSwitchState */
#define D_stsOutputRedSwitchState_noAction 0
#define D_stsOutputRedSwitchState_active 1
#define D_stsOutputRedSwitchState_standby 2

/* enumerated values for stsOutputCRCCHK */
#define D_stsOutputCRCCHK_enable       1
#define D_stsOutputCRCCHK_disable      2

/* enumerated values for stsOutputCAS */
#define D_stsOutputCAS_enable          1
#define D_stsOutputCAS_disable         2

/* enumerated values for stsOutputSSM */
#define D_stsOutputSSM_sa4             1
#define D_stsOutputSSM_sa5             2
#define D_stsOutputSSM_sa6             3
#define D_stsOutputSSM_sa7             4
#define D_stsOutputSSM_sa8             5

/* enumerated values for stsOutputSSMValue */
#define D_stsOutputSSMValue_prs        1
#define D_stsOutputSSMValue_stu        2
#define D_stsOutputSSMValue_st2        3
#define D_stsOutputSSMValue_st3        4
#define D_stsOutputSSMValue_sic        5
#define D_stsOutputSSMValue_duc        6

/* enumerated values for stsEmmShelf */
#define D_stsEmmShelf_main             100
#define D_stsEmmShelf_expansion_1      1
#define D_stsEmmShelf_expansion_2      2
#define D_stsEmmShelf_expansion_3      3

/* enumerated values for stsEmmSensorType */
#define D_stsEmmSensorType_temp_celsius 1
#define D_stsEmmSensorType_voltage_mvolt 2

/* enumerated values for stsEmmAlarmStatus */
#define D_stsEmmAlarmStatus_cr         1
#define D_stsEmmAlarmStatus_mj         2
#define D_stsEmmAlarmStatus_mn         3
#define D_stsEmmAlarmStatus_na         4
#define D_stsEmmAlarmStatus_nr         5
#define D_stsEmmAlarmStatus_cl         6

/* enumerated values for stsAntStatus */
#define D_stsAntStatus_active          1
#define D_stsAntStatus_standby         2
#define D_stsAntStatus_failure         3
#define D_stsAntStatus_absent          4

/* enumerated values for stsAntSwitchState */
#define D_stsAntSwitchState_noAction   0
#define D_stsAntSwitchState_active     1
#define D_stsAntSwitchState_standby    2

/* enumerated values for stsTrapRegState */
#define D_stsTrapRegState_enabled      1
#define D_stsTrapRegState_disabled     2


#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_LARUSSTSDEFS_H */
