/*
 *
 * Copyright (C) 1992-2003 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -o snmp -separate_type_file 
 */

/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_SNMPPART_H
#define SR_SNMPPART_H


#ifdef __cplusplus
extern "C" {
#endif

/* only define name strings if we are not compiling LIGHT */
#ifndef LIGHT
#define STdeclare(name, value) static const char name [] = value;
#else	/* LIGHT */
#define STdeclare(name, value)
#endif	/* LIGHT */

/* define the OID components of the OID call table */

#if defined(N_iso)
#ifdef SNMPPART_DECL
const SR_UINT32 IDiso[] = { 1 };
#else
extern const SR_UINT32 IDiso[];
#endif	/* SNMPPART_DECL */
#define LNiso 1
#endif	/* defined(N_iso) */


#if defined(N_org)
#ifdef SNMPPART_DECL
const SR_UINT32 IDorg[] = { 1, 3 };
#else
extern const SR_UINT32 IDorg[];
#endif	/* SNMPPART_DECL */
#define LNorg 2
#endif	/* defined(N_org) */


#if defined(N_dod)
#ifdef SNMPPART_DECL
const SR_UINT32 IDdod[] = { 1, 3, 6 };
#else
extern const SR_UINT32 IDdod[];
#endif	/* SNMPPART_DECL */
#define LNdod 3
#endif	/* defined(N_dod) */


#if defined(N_internet)
#ifdef SNMPPART_DECL
const SR_UINT32 IDinternet[] = { 1, 3, 6, 1 };
#else
extern const SR_UINT32 IDinternet[];
#endif	/* SNMPPART_DECL */
#define LNinternet 4
#endif	/* defined(N_internet) */


#if defined(N_directory)
#ifdef SNMPPART_DECL
const SR_UINT32 IDdirectory[] = { 1, 3, 6, 1, 1 };
#else
extern const SR_UINT32 IDdirectory[];
#endif	/* SNMPPART_DECL */
#define LNdirectory 5
#endif	/* defined(N_directory) */


#if defined(N_mgmt)
#ifdef SNMPPART_DECL
const SR_UINT32 IDmgmt[] = { 1, 3, 6, 1, 2 };
#else
extern const SR_UINT32 IDmgmt[];
#endif	/* SNMPPART_DECL */
#define LNmgmt 5
#endif	/* defined(N_mgmt) */


#if defined(N_mib_2)
#ifdef SNMPPART_DECL
const SR_UINT32 IDmib_2[] = { 1, 3, 6, 1, 2, 1 };
#else
extern const SR_UINT32 IDmib_2[];
#endif	/* SNMPPART_DECL */
#define LNmib_2 6
#endif	/* defined(N_mib_2) */


#if defined(N_system)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsystem[] = { 1, 3, 6, 1, 2, 1, 1 };
#else
extern const SR_UINT32 IDsystem[];
#endif	/* SNMPPART_DECL */
#define LNsystem 7
#endif	/* defined(N_system) */


#if defined(I_sysDescr)
#ifdef SNMPPART_DECL
STdeclare(STsysDescr, "sysDescr")
const SR_UINT32 IDsysDescr[] = { 1, 3, 6, 1, 2, 1, 1, 1 };
#else
extern const SR_UINT32 IDsysDescr[];
#endif	/* SNMPPART_DECL */
#define LNsysDescr 8
#endif	/* defined(I_sysDescr) */


#if defined(I_sysObjectID)
#ifdef SNMPPART_DECL
STdeclare(STsysObjectID, "sysObjectID")
const SR_UINT32 IDsysObjectID[] = { 1, 3, 6, 1, 2, 1, 1, 2 };
#else
extern const SR_UINT32 IDsysObjectID[];
#endif	/* SNMPPART_DECL */
#define LNsysObjectID 8
#endif	/* defined(I_sysObjectID) */


#if defined(N_interfaces)
#ifdef SNMPPART_DECL
const SR_UINT32 IDinterfaces[] = { 1, 3, 6, 1, 2, 1, 2 };
#else
extern const SR_UINT32 IDinterfaces[];
#endif	/* SNMPPART_DECL */
#define LNinterfaces 7
#endif	/* defined(N_interfaces) */


#if defined(N_at)
#ifdef SNMPPART_DECL
const SR_UINT32 IDat[] = { 1, 3, 6, 1, 2, 1, 3 };
#else
extern const SR_UINT32 IDat[];
#endif	/* SNMPPART_DECL */
#define LNat 7
#endif	/* defined(N_at) */


#if defined(N_ip)
#ifdef SNMPPART_DECL
const SR_UINT32 IDip[] = { 1, 3, 6, 1, 2, 1, 4 };
#else
extern const SR_UINT32 IDip[];
#endif	/* SNMPPART_DECL */
#define LNip 7
#endif	/* defined(N_ip) */


#if defined(N_icmp)
#ifdef SNMPPART_DECL
const SR_UINT32 IDicmp[] = { 1, 3, 6, 1, 2, 1, 5 };
#else
extern const SR_UINT32 IDicmp[];
#endif	/* SNMPPART_DECL */
#define LNicmp 7
#endif	/* defined(N_icmp) */


#if defined(N_tcp)
#ifdef SNMPPART_DECL
const SR_UINT32 IDtcp[] = { 1, 3, 6, 1, 2, 1, 6 };
#else
extern const SR_UINT32 IDtcp[];
#endif	/* SNMPPART_DECL */
#define LNtcp 7
#endif	/* defined(N_tcp) */


#if defined(N_udp)
#ifdef SNMPPART_DECL
const SR_UINT32 IDudp[] = { 1, 3, 6, 1, 2, 1, 7 };
#else
extern const SR_UINT32 IDudp[];
#endif	/* SNMPPART_DECL */
#define LNudp 7
#endif	/* defined(N_udp) */


#if defined(N_egp)
#ifdef SNMPPART_DECL
const SR_UINT32 IDegp[] = { 1, 3, 6, 1, 2, 1, 8 };
#else
extern const SR_UINT32 IDegp[];
#endif	/* SNMPPART_DECL */
#define LNegp 7
#endif	/* defined(N_egp) */


#if defined(N_transmission)
#ifdef SNMPPART_DECL
const SR_UINT32 IDtransmission[] = { 1, 3, 6, 1, 2, 1, 10 };
#else
extern const SR_UINT32 IDtransmission[];
#endif	/* SNMPPART_DECL */
#define LNtransmission 7
#endif	/* defined(N_transmission) */


#if defined(N_snmp)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsnmp[] = { 1, 3, 6, 1, 2, 1, 11 };
#else
extern const SR_UINT32 IDsnmp[];
#endif	/* SNMPPART_DECL */
#define LNsnmp 7
#endif	/* defined(N_snmp) */


#if defined(N_experimental)
#ifdef SNMPPART_DECL
const SR_UINT32 IDexperimental[] = { 1, 3, 6, 1, 3 };
#else
extern const SR_UINT32 IDexperimental[];
#endif	/* SNMPPART_DECL */
#define LNexperimental 5
#endif	/* defined(N_experimental) */


#if defined(N_private)
#ifdef SNMPPART_DECL
const SR_UINT32 IDprivate[] = { 1, 3, 6, 1, 4 };
#else
extern const SR_UINT32 IDprivate[];
#endif	/* SNMPPART_DECL */
#define LNprivate 5
#endif	/* defined(N_private) */


#if defined(N_enterprises)
#ifdef SNMPPART_DECL
const SR_UINT32 IDenterprises[] = { 1, 3, 6, 1, 4, 1 };
#else
extern const SR_UINT32 IDenterprises[];
#endif	/* SNMPPART_DECL */
#define LNenterprises 6
#endif	/* defined(N_enterprises) */


#if defined(N_snmpResearch)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsnmpResearch[] = { 1, 3, 6, 1, 4, 1, 99 };
#else
extern const SR_UINT32 IDsnmpResearch[];
#endif	/* SNMPPART_DECL */
#define LNsnmpResearch 7
#endif	/* defined(N_snmpResearch) */


#if defined(N_snmpResearchMIBs)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsnmpResearchMIBs[] = { 1, 3, 6, 1, 4, 1, 99, 12 };
#else
extern const SR_UINT32 IDsnmpResearchMIBs[];
#endif	/* SNMPPART_DECL */
#define LNsnmpResearchMIBs 8
#endif	/* defined(N_snmpResearchMIBs) */


#if defined(N_larus)
#ifdef SNMPPART_DECL
const SR_UINT32 IDlarus[] = { 1, 3, 6, 1, 4, 1, 24628 };
#else
extern const SR_UINT32 IDlarus[];
#endif	/* SNMPPART_DECL */
#define LNlarus 7
#endif	/* defined(N_larus) */


#if defined(N_larusProducts)
#ifdef SNMPPART_DECL
const SR_UINT32 IDlarusProducts[] = { 1, 3, 6, 1, 4, 1, 24628, 1 };
#else
extern const SR_UINT32 IDlarusProducts[];
#endif	/* SNMPPART_DECL */
#define LNlarusProducts 8
#endif	/* defined(N_larusProducts) */


#if defined(N_larusMgmt)
#ifdef SNMPPART_DECL
const SR_UINT32 IDlarusMgmt[] = { 1, 3, 6, 1, 4, 1, 24628, 2 };
#else
extern const SR_UINT32 IDlarusMgmt[];
#endif	/* SNMPPART_DECL */
#define LNlarusMgmt 8
#endif	/* defined(N_larusMgmt) */


#if defined(N_larusMib)
#ifdef SNMPPART_DECL
const SR_UINT32 IDlarusMib[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2 };
#else
extern const SR_UINT32 IDlarusMib[];
#endif	/* SNMPPART_DECL */
#define LNlarusMib 9
#endif	/* defined(N_larusMib) */


#if defined(N_stsSystem)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsSystem[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1 };
#else
extern const SR_UINT32 IDstsSystem[];
#endif	/* SNMPPART_DECL */
#define LNstsSystem 10
#endif	/* defined(N_stsSystem) */


#if defined(I_stsSystemId)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemId, "stsSystemId")
const SR_UINT32 IDstsSystemId[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 1 };
#else
extern const SR_UINT32 IDstsSystemId[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemId 11
#endif	/* defined(I_stsSystemId) */


#if defined(I_stsSystemMgmtIpOption)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemMgmtIpOption, "stsSystemMgmtIpOption")
const SR_UINT32 IDstsSystemMgmtIpOption[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 2 };
#else
extern const SR_UINT32 IDstsSystemMgmtIpOption[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemMgmtIpOption 11
#endif	/* defined(I_stsSystemMgmtIpOption) */


#if defined(I_stsSystemMgmtIpAddress)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemMgmtIpAddress, "stsSystemMgmtIpAddress")
const SR_UINT32 IDstsSystemMgmtIpAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 3 };
#else
extern const SR_UINT32 IDstsSystemMgmtIpAddress[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemMgmtIpAddress 11
#endif	/* defined(I_stsSystemMgmtIpAddress) */


#if defined(I_stsSystemMgmtIpSubnetMask)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemMgmtIpSubnetMask, "stsSystemMgmtIpSubnetMask")
const SR_UINT32 IDstsSystemMgmtIpSubnetMask[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 4 };
#else
extern const SR_UINT32 IDstsSystemMgmtIpSubnetMask[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemMgmtIpSubnetMask 11
#endif	/* defined(I_stsSystemMgmtIpSubnetMask) */


#if defined(I_stsSystemMgmtIpGatewayAddress)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemMgmtIpGatewayAddress, "stsSystemMgmtIpGatewayAddress")
const SR_UINT32 IDstsSystemMgmtIpGatewayAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 5 };
#else
extern const SR_UINT32 IDstsSystemMgmtIpGatewayAddress[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemMgmtIpGatewayAddress 11
#endif	/* defined(I_stsSystemMgmtIpGatewayAddress) */


#if defined(I_stsSystemSntpIpOption)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemSntpIpOption, "stsSystemSntpIpOption")
const SR_UINT32 IDstsSystemSntpIpOption[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 6 };
#else
extern const SR_UINT32 IDstsSystemSntpIpOption[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemSntpIpOption 11
#endif	/* defined(I_stsSystemSntpIpOption) */


#if defined(I_stsSystemSntpIpAddress)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemSntpIpAddress, "stsSystemSntpIpAddress")
const SR_UINT32 IDstsSystemSntpIpAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 7 };
#else
extern const SR_UINT32 IDstsSystemSntpIpAddress[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemSntpIpAddress 11
#endif	/* defined(I_stsSystemSntpIpAddress) */


#if defined(I_stsSystemSntpIpSubnetMask)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemSntpIpSubnetMask, "stsSystemSntpIpSubnetMask")
const SR_UINT32 IDstsSystemSntpIpSubnetMask[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 8 };
#else
extern const SR_UINT32 IDstsSystemSntpIpSubnetMask[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemSntpIpSubnetMask 11
#endif	/* defined(I_stsSystemSntpIpSubnetMask) */


#if defined(I_stsSystemSntpIpGatewayAddress)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemSntpIpGatewayAddress, "stsSystemSntpIpGatewayAddress")
const SR_UINT32 IDstsSystemSntpIpGatewayAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 9 };
#else
extern const SR_UINT32 IDstsSystemSntpIpGatewayAddress[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemSntpIpGatewayAddress 11
#endif	/* defined(I_stsSystemSntpIpGatewayAddress) */


#if defined(I_stsSystemTime)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemTime, "stsSystemTime")
const SR_UINT32 IDstsSystemTime[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 10 };
#else
extern const SR_UINT32 IDstsSystemTime[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemTime 11
#endif	/* defined(I_stsSystemTime) */


#if defined(I_stsSystemTimeZone)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemTimeZone, "stsSystemTimeZone")
const SR_UINT32 IDstsSystemTimeZone[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 11 };
#else
extern const SR_UINT32 IDstsSystemTimeZone[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemTimeZone 11
#endif	/* defined(I_stsSystemTimeZone) */


#if defined(I_stsSystemIntegratedAlarm)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemIntegratedAlarm, "stsSystemIntegratedAlarm")
const SR_UINT32 IDstsSystemIntegratedAlarm[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 12 };
#else
extern const SR_UINT32 IDstsSystemIntegratedAlarm[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemIntegratedAlarm 11
#endif	/* defined(I_stsSystemIntegratedAlarm) */


#if defined(I_stsSystemAlarmAcoMode)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemAlarmAcoMode, "stsSystemAlarmAcoMode")
const SR_UINT32 IDstsSystemAlarmAcoMode[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 13 };
#else
extern const SR_UINT32 IDstsSystemAlarmAcoMode[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemAlarmAcoMode 11
#endif	/* defined(I_stsSystemAlarmAcoMode) */


#if defined(I_stsSystemAlarmAcoLed)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemAlarmAcoLed, "stsSystemAlarmAcoLed")
const SR_UINT32 IDstsSystemAlarmAcoLed[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 14 };
#else
extern const SR_UINT32 IDstsSystemAlarmAcoLed[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemAlarmAcoLed 11
#endif	/* defined(I_stsSystemAlarmAcoLed) */


#if defined(I_stsSystemAlarmAcoCutOff)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemAlarmAcoCutOff, "stsSystemAlarmAcoCutOff")
const SR_UINT32 IDstsSystemAlarmAcoCutOff[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 15 };
#else
extern const SR_UINT32 IDstsSystemAlarmAcoCutOff[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemAlarmAcoCutOff 11
#endif	/* defined(I_stsSystemAlarmAcoCutOff) */


#if defined(I_stsSystemAlarmEscalatingTime)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemAlarmEscalatingTime, "stsSystemAlarmEscalatingTime")
const SR_UINT32 IDstsSystemAlarmEscalatingTime[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 16 };
#else
extern const SR_UINT32 IDstsSystemAlarmEscalatingTime[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemAlarmEscalatingTime 11
#endif	/* defined(I_stsSystemAlarmEscalatingTime) */


#if defined(I_stsSystemMinorLED)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemMinorLED, "stsSystemMinorLED")
const SR_UINT32 IDstsSystemMinorLED[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 17 };
#else
extern const SR_UINT32 IDstsSystemMinorLED[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemMinorLED 11
#endif	/* defined(I_stsSystemMinorLED) */


#if defined(I_stsSystemMajorLED)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemMajorLED, "stsSystemMajorLED")
const SR_UINT32 IDstsSystemMajorLED[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 18 };
#else
extern const SR_UINT32 IDstsSystemMajorLED[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemMajorLED 11
#endif	/* defined(I_stsSystemMajorLED) */


#if defined(I_stsSystemCriticalLED)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemCriticalLED, "stsSystemCriticalLED")
const SR_UINT32 IDstsSystemCriticalLED[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 19 };
#else
extern const SR_UINT32 IDstsSystemCriticalLED[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemCriticalLED 11
#endif	/* defined(I_stsSystemCriticalLED) */


#if defined(I_stsSystemUpgradeSWAction)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemUpgradeSWAction, "stsSystemUpgradeSWAction")
const SR_UINT32 IDstsSystemUpgradeSWAction[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 20 };
#else
extern const SR_UINT32 IDstsSystemUpgradeSWAction[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemUpgradeSWAction 11
#endif	/* defined(I_stsSystemUpgradeSWAction) */


#if defined(I_stsSystemCurrentSWVersion)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemCurrentSWVersion, "stsSystemCurrentSWVersion")
const SR_UINT32 IDstsSystemCurrentSWVersion[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 21 };
#else
extern const SR_UINT32 IDstsSystemCurrentSWVersion[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemCurrentSWVersion 11
#endif	/* defined(I_stsSystemCurrentSWVersion) */


#if defined(I_stsSystemServiceState)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemServiceState, "stsSystemServiceState")
const SR_UINT32 IDstsSystemServiceState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 22 };
#else
extern const SR_UINT32 IDstsSystemServiceState[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemServiceState 11
#endif	/* defined(I_stsSystemServiceState) */


#if defined(I_stsSystemReset)
#ifdef SNMPPART_DECL
STdeclare(STstsSystemReset, "stsSystemReset")
const SR_UINT32 IDstsSystemReset[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 1, 23 };
#else
extern const SR_UINT32 IDstsSystemReset[];
#endif	/* SNMPPART_DECL */
#define LNstsSystemReset 11
#endif	/* defined(I_stsSystemReset) */


#if defined(N_stsClockInput)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsClockInput[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2 };
#else
extern const SR_UINT32 IDstsClockInput[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInput 10
#endif	/* defined(N_stsClockInput) */


#if defined(I_stsClockInputManualSelect)
#ifdef SNMPPART_DECL
STdeclare(STstsClockInputManualSelect, "stsClockInputManualSelect")
const SR_UINT32 IDstsClockInputManualSelect[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2, 1 };
#else
extern const SR_UINT32 IDstsClockInputManualSelect[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputManualSelect 11
#endif	/* defined(I_stsClockInputManualSelect) */


#if defined(I_stsClockInputOperMode)
#ifdef SNMPPART_DECL
STdeclare(STstsClockInputOperMode, "stsClockInputOperMode")
const SR_UINT32 IDstsClockInputOperMode[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2, 2 };
#else
extern const SR_UINT32 IDstsClockInputOperMode[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputOperMode 11
#endif	/* defined(I_stsClockInputOperMode) */


#if defined(I_stsClockInputProtectedPri)
#ifdef SNMPPART_DECL
STdeclare(STstsClockInputProtectedPri, "stsClockInputProtectedPri")
const SR_UINT32 IDstsClockInputProtectedPri[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2, 3 };
#else
extern const SR_UINT32 IDstsClockInputProtectedPri[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputProtectedPri 11
#endif	/* defined(I_stsClockInputProtectedPri) */


#if defined(I_stsClockInputSetSlip)
#ifdef SNMPPART_DECL
STdeclare(STstsClockInputSetSlip, "stsClockInputSetSlip")
const SR_UINT32 IDstsClockInputSetSlip[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2, 4 };
#else
extern const SR_UINT32 IDstsClockInputSetSlip[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputSetSlip 11
#endif	/* defined(I_stsClockInputSetSlip) */


#if defined(I_stsClockInputType)
#ifdef SNMPPART_DECL
STdeclare(STstsClockInputType, "stsClockInputType")
const SR_UINT32 IDstsClockInputType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 2, 5 };
#else
extern const SR_UINT32 IDstsClockInputType[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputType 11
#endif	/* defined(I_stsClockInputType) */


#if defined(N_stsClockInputSSM)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsClockInputSSM[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 3 };
#else
extern const SR_UINT32 IDstsClockInputSSM[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputSSM 10
#endif	/* defined(N_stsClockInputSSM) */


#if defined(I_stsClockInputSSMSelect)
#ifdef SNMPPART_DECL
STdeclare(STstsClockInputSSMSelect, "stsClockInputSSMSelect")
const SR_UINT32 IDstsClockInputSSMSelect[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 3, 1 };
#else
extern const SR_UINT32 IDstsClockInputSSMSelect[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputSSMSelect 11
#endif	/* defined(I_stsClockInputSSMSelect) */


#if defined(N_stsTop)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsTop[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4 };
#else
extern const SR_UINT32 IDstsTop[];
#endif	/* SNMPPART_DECL */
#define LNstsTop 10
#endif	/* defined(N_stsTop) */


#if defined(I_stsTopSourceIpOption)
#ifdef SNMPPART_DECL
STdeclare(STstsTopSourceIpOption, "stsTopSourceIpOption")
const SR_UINT32 IDstsTopSourceIpOption[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 1 };
#else
extern const SR_UINT32 IDstsTopSourceIpOption[];
#endif	/* SNMPPART_DECL */
#define LNstsTopSourceIpOption 11
#endif	/* defined(I_stsTopSourceIpOption) */


#if defined(I_stsTopSourceIpAddress)
#ifdef SNMPPART_DECL
STdeclare(STstsTopSourceIpAddress, "stsTopSourceIpAddress")
const SR_UINT32 IDstsTopSourceIpAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 2 };
#else
extern const SR_UINT32 IDstsTopSourceIpAddress[];
#endif	/* SNMPPART_DECL */
#define LNstsTopSourceIpAddress 11
#endif	/* defined(I_stsTopSourceIpAddress) */


#if defined(I_stsTopSourceIpSubnetMask)
#ifdef SNMPPART_DECL
STdeclare(STstsTopSourceIpSubnetMask, "stsTopSourceIpSubnetMask")
const SR_UINT32 IDstsTopSourceIpSubnetMask[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 3 };
#else
extern const SR_UINT32 IDstsTopSourceIpSubnetMask[];
#endif	/* SNMPPART_DECL */
#define LNstsTopSourceIpSubnetMask 11
#endif	/* defined(I_stsTopSourceIpSubnetMask) */


#if defined(I_stsTopSourceIpGatewayAddress)
#ifdef SNMPPART_DECL
STdeclare(STstsTopSourceIpGatewayAddress, "stsTopSourceIpGatewayAddress")
const SR_UINT32 IDstsTopSourceIpGatewayAddress[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 4 };
#else
extern const SR_UINT32 IDstsTopSourceIpGatewayAddress[];
#endif	/* SNMPPART_DECL */
#define LNstsTopSourceIpGatewayAddress 11
#endif	/* defined(I_stsTopSourceIpGatewayAddress) */


#if defined(I_stsTopPacketRate)
#ifdef SNMPPART_DECL
STdeclare(STstsTopPacketRate, "stsTopPacketRate")
const SR_UINT32 IDstsTopPacketRate[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 5 };
#else
extern const SR_UINT32 IDstsTopPacketRate[];
#endif	/* SNMPPART_DECL */
#define LNstsTopPacketRate 11
#endif	/* defined(I_stsTopPacketRate) */


#if defined(I_stsTopInputSelect)
#ifdef SNMPPART_DECL
STdeclare(STstsTopInputSelect, "stsTopInputSelect")
const SR_UINT32 IDstsTopInputSelect[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 6 };
#else
extern const SR_UINT32 IDstsTopInputSelect[];
#endif	/* SNMPPART_DECL */
#define LNstsTopInputSelect 11
#endif	/* defined(I_stsTopInputSelect) */


#if defined(I_stsTopTxPackets)
#ifdef SNMPPART_DECL
STdeclare(STstsTopTxPackets, "stsTopTxPackets")
const SR_UINT32 IDstsTopTxPackets[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 7 };
#else
extern const SR_UINT32 IDstsTopTxPackets[];
#endif	/* SNMPPART_DECL */
#define LNstsTopTxPackets 11
#endif	/* defined(I_stsTopTxPackets) */


#if defined(I_stsTopTxBytes)
#ifdef SNMPPART_DECL
STdeclare(STstsTopTxBytes, "stsTopTxBytes")
const SR_UINT32 IDstsTopTxBytes[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 4, 8 };
#else
extern const SR_UINT32 IDstsTopTxBytes[];
#endif	/* SNMPPART_DECL */
#define LNstsTopTxBytes 11
#endif	/* defined(I_stsTopTxBytes) */


#if defined(N_stsPerfMonManual)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsPerfMonManual[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 5 };
#else
extern const SR_UINT32 IDstsPerfMonManual[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonManual 10
#endif	/* defined(N_stsPerfMonManual) */


#if defined(I_stsPerfMonManualInputSelect)
#ifdef SNMPPART_DECL
STdeclare(STstsPerfMonManualInputSelect, "stsPerfMonManualInputSelect")
const SR_UINT32 IDstsPerfMonManualInputSelect[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 5, 1 };
#else
extern const SR_UINT32 IDstsPerfMonManualInputSelect[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonManualInputSelect 11
#endif	/* defined(I_stsPerfMonManualInputSelect) */


#if defined(I_stsPerfMonManualInputScanInterval)
#ifdef SNMPPART_DECL
STdeclare(STstsPerfMonManualInputScanInterval, "stsPerfMonManualInputScanInterval")
const SR_UINT32 IDstsPerfMonManualInputScanInterval[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 5, 2 };
#else
extern const SR_UINT32 IDstsPerfMonManualInputScanInterval[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonManualInputScanInterval 11
#endif	/* defined(I_stsPerfMonManualInputScanInterval) */


#if defined(I_stsPerfMonManualInputNumReport)
#ifdef SNMPPART_DECL
STdeclare(STstsPerfMonManualInputNumReport, "stsPerfMonManualInputNumReport")
const SR_UINT32 IDstsPerfMonManualInputNumReport[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 5, 3 };
#else
extern const SR_UINT32 IDstsPerfMonManualInputNumReport[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonManualInputNumReport 11
#endif	/* defined(I_stsPerfMonManualInputNumReport) */


#if defined(I_stsPerfMonManualInputNumObservation)
#ifdef SNMPPART_DECL
STdeclare(STstsPerfMonManualInputNumObservation, "stsPerfMonManualInputNumObservation")
const SR_UINT32 IDstsPerfMonManualInputNumObservation[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 5, 4 };
#else
extern const SR_UINT32 IDstsPerfMonManualInputNumObservation[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonManualInputNumObservation 11
#endif	/* defined(I_stsPerfMonManualInputNumObservation) */


#if defined(I_stsPerfMonManualInputAbortTest)
#ifdef SNMPPART_DECL
STdeclare(STstsPerfMonManualInputAbortTest, "stsPerfMonManualInputAbortTest")
const SR_UINT32 IDstsPerfMonManualInputAbortTest[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 5, 5 };
#else
extern const SR_UINT32 IDstsPerfMonManualInputAbortTest[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonManualInputAbortTest 11
#endif	/* defined(I_stsPerfMonManualInputAbortTest) */


#if defined(N_stsClockInputStatus)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsClockInputStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 6 };
#else
extern const SR_UINT32 IDstsClockInputStatus[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputStatus 10
#endif	/* defined(N_stsClockInputStatus) */




#if defined(I_stsClockInputStatusIndex)
#ifdef SNMPPART_DECL
STdeclare(STstsClockInputStatusIndex, "stsClockInputStatusIndex")
const SR_UINT32 IDstsClockInputStatusIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 6, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsClockInputStatusIndex[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputStatusIndex 13
#endif	/* defined(I_stsClockInputStatusIndex) */


#if defined(I_stsClockInputState)
#ifdef SNMPPART_DECL
STdeclare(STstsClockInputState, "stsClockInputState")
const SR_UINT32 IDstsClockInputState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 6, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsClockInputState[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputState 13
#endif	/* defined(I_stsClockInputState) */


#if defined(N_stsClockInputSSMStatus)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsClockInputSSMStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7 };
#else
extern const SR_UINT32 IDstsClockInputSSMStatus[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputSSMStatus 10
#endif	/* defined(N_stsClockInputSSMStatus) */




#if defined(I_stsClockInputSSMIndex)
#ifdef SNMPPART_DECL
STdeclare(STstsClockInputSSMIndex, "stsClockInputSSMIndex")
const SR_UINT32 IDstsClockInputSSMIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsClockInputSSMIndex[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputSSMIndex 13
#endif	/* defined(I_stsClockInputSSMIndex) */


#if defined(I_stsClockInputSSMType)
#ifdef SNMPPART_DECL
STdeclare(STstsClockInputSSMType, "stsClockInputSSMType")
const SR_UINT32 IDstsClockInputSSMType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsClockInputSSMType[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputSSMType 13
#endif	/* defined(I_stsClockInputSSMType) */


#if defined(I_stsClockInputSSMValue)
#ifdef SNMPPART_DECL
STdeclare(STstsClockInputSSMValue, "stsClockInputSSMValue")
const SR_UINT32 IDstsClockInputSSMValue[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 7, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsClockInputSSMValue[];
#endif	/* SNMPPART_DECL */
#define LNstsClockInputSSMValue 13
#endif	/* defined(I_stsClockInputSSMValue) */


#if defined(N_stsCard)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsCard[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8 };
#else
extern const SR_UINT32 IDstsCard[];
#endif	/* SNMPPART_DECL */
#define LNstsCard 10
#endif	/* defined(N_stsCard) */




#if defined(I_stsCardShelf)
#ifdef SNMPPART_DECL
STdeclare(STstsCardShelf, "stsCardShelf")
const SR_UINT32 IDstsCardShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsCardShelf[];
#endif	/* SNMPPART_DECL */
#define LNstsCardShelf 13
#endif	/* defined(I_stsCardShelf) */


#if defined(I_stsCardIndex)
#ifdef SNMPPART_DECL
STdeclare(STstsCardIndex, "stsCardIndex")
const SR_UINT32 IDstsCardIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsCardIndex[];
#endif	/* SNMPPART_DECL */
#define LNstsCardIndex 13
#endif	/* defined(I_stsCardIndex) */


#if defined(I_stsCardType)
#ifdef SNMPPART_DECL
STdeclare(STstsCardType, "stsCardType")
const SR_UINT32 IDstsCardType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsCardType[];
#endif	/* SNMPPART_DECL */
#define LNstsCardType 13
#endif	/* defined(I_stsCardType) */


#if defined(I_stsCardDescr)
#ifdef SNMPPART_DECL
STdeclare(STstsCardDescr, "stsCardDescr")
const SR_UINT32 IDstsCardDescr[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsCardDescr[];
#endif	/* SNMPPART_DECL */
#define LNstsCardDescr 13
#endif	/* defined(I_stsCardDescr) */


#if defined(I_stsCardSerial)
#ifdef SNMPPART_DECL
STdeclare(STstsCardSerial, "stsCardSerial")
const SR_UINT32 IDstsCardSerial[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsCardSerial[];
#endif	/* SNMPPART_DECL */
#define LNstsCardSerial 13
#endif	/* defined(I_stsCardSerial) */


#if defined(I_stsCardHwVersion)
#ifdef SNMPPART_DECL
STdeclare(STstsCardHwVersion, "stsCardHwVersion")
const SR_UINT32 IDstsCardHwVersion[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 6 };
#else
extern const SR_UINT32 IDstsCardHwVersion[];
#endif	/* SNMPPART_DECL */
#define LNstsCardHwVersion 13
#endif	/* defined(I_stsCardHwVersion) */


#if defined(I_stsCardCLEICode)
#ifdef SNMPPART_DECL
STdeclare(STstsCardCLEICode, "stsCardCLEICode")
const SR_UINT32 IDstsCardCLEICode[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 7 };
#else
extern const SR_UINT32 IDstsCardCLEICode[];
#endif	/* SNMPPART_DECL */
#define LNstsCardCLEICode 13
#endif	/* defined(I_stsCardCLEICode) */


#if defined(I_stsCardOperStatus)
#ifdef SNMPPART_DECL
STdeclare(STstsCardOperStatus, "stsCardOperStatus")
const SR_UINT32 IDstsCardOperStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 8 };
#else
extern const SR_UINT32 IDstsCardOperStatus[];
#endif	/* SNMPPART_DECL */
#define LNstsCardOperStatus 13
#endif	/* defined(I_stsCardOperStatus) */


#if defined(I_stsCardReset)
#ifdef SNMPPART_DECL
STdeclare(STstsCardReset, "stsCardReset")
const SR_UINT32 IDstsCardReset[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 8, 1, 1, 9 };
#else
extern const SR_UINT32 IDstsCardReset[];
#endif	/* SNMPPART_DECL */
#define LNstsCardReset 13
#endif	/* defined(I_stsCardReset) */


#if defined(N_stsOscillator)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsOscillator[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9 };
#else
extern const SR_UINT32 IDstsOscillator[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillator 10
#endif	/* defined(N_stsOscillator) */




#if defined(I_stsOscillatorIndex)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorIndex, "stsOscillatorIndex")
const SR_UINT32 IDstsOscillatorIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsOscillatorIndex[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorIndex 13
#endif	/* defined(I_stsOscillatorIndex) */


#if defined(I_stsOscillatorModuleType)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorModuleType, "stsOscillatorModuleType")
const SR_UINT32 IDstsOscillatorModuleType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsOscillatorModuleType[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorModuleType 13
#endif	/* defined(I_stsOscillatorModuleType) */


#if defined(I_stsOscillatorEFER)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorEFER, "stsOscillatorEFER")
const SR_UINT32 IDstsOscillatorEFER[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsOscillatorEFER[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorEFER 13
#endif	/* defined(I_stsOscillatorEFER) */


#if defined(I_stsOscillatorESSD)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorESSD, "stsOscillatorESSD")
const SR_UINT32 IDstsOscillatorESSD[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsOscillatorESSD[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorESSD 13
#endif	/* defined(I_stsOscillatorESSD) */


#if defined(I_stsOscillatorESSN)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorESSN, "stsOscillatorESSN")
const SR_UINT32 IDstsOscillatorESSN[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsOscillatorESSN[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorESSN 13
#endif	/* defined(I_stsOscillatorESSN) */


#if defined(I_stsOscillatorFAGE)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorFAGE, "stsOscillatorFAGE")
const SR_UINT32 IDstsOscillatorFAGE[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 6 };
#else
extern const SR_UINT32 IDstsOscillatorFAGE[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorFAGE 13
#endif	/* defined(I_stsOscillatorFAGE) */


#if defined(I_stsOscillatorTIMD)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorTIMD, "stsOscillatorTIMD")
const SR_UINT32 IDstsOscillatorTIMD[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 7 };
#else
extern const SR_UINT32 IDstsOscillatorTIMD[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorTIMD 13
#endif	/* defined(I_stsOscillatorTIMD) */


#if defined(I_stsOscillatorSetActive)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorSetActive, "stsOscillatorSetActive")
const SR_UINT32 IDstsOscillatorSetActive[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 8 };
#else
extern const SR_UINT32 IDstsOscillatorSetActive[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorSetActive 13
#endif	/* defined(I_stsOscillatorSetActive) */


#if defined(I_stsOscillatorStatus)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorStatus, "stsOscillatorStatus")
const SR_UINT32 IDstsOscillatorStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 9, 1, 1, 9 };
#else
extern const SR_UINT32 IDstsOscillatorStatus[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorStatus 13
#endif	/* defined(I_stsOscillatorStatus) */


#if defined(N_stsGPS)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsGPS[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10 };
#else
extern const SR_UINT32 IDstsGPS[];
#endif	/* SNMPPART_DECL */
#define LNstsGPS 10
#endif	/* defined(N_stsGPS) */




#if defined(I_stsGpsIndex)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsIndex, "stsGpsIndex")
const SR_UINT32 IDstsGpsIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsGpsIndex[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsIndex 13
#endif	/* defined(I_stsGpsIndex) */


#if defined(I_stsGpsStatus)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsStatus, "stsGpsStatus")
const SR_UINT32 IDstsGpsStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsGpsStatus[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsStatus 13
#endif	/* defined(I_stsGpsStatus) */


#if defined(I_stsGpsANTD)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsANTD, "stsGpsANTD")
const SR_UINT32 IDstsGpsANTD[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsGpsANTD[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsANTD 13
#endif	/* defined(I_stsGpsANTD) */


#if defined(I_stsGpsAZEL)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsAZEL, "stsGpsAZEL")
const SR_UINT32 IDstsGpsAZEL[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsGpsAZEL[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsAZEL 13
#endif	/* defined(I_stsGpsAZEL) */


#if defined(I_stsGpsRSTG)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsRSTG, "stsGpsRSTG")
const SR_UINT32 IDstsGpsRSTG[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsGpsRSTG[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsRSTG 13
#endif	/* defined(I_stsGpsRSTG) */


#if defined(I_stsGpsBITS)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsBITS, "stsGpsBITS")
const SR_UINT32 IDstsGpsBITS[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 6 };
#else
extern const SR_UINT32 IDstsGpsBITS[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsBITS 13
#endif	/* defined(I_stsGpsBITS) */


#if defined(I_stsGpsPAVG)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsPAVG, "stsGpsPAVG")
const SR_UINT32 IDstsGpsPAVG[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 7 };
#else
extern const SR_UINT32 IDstsGpsPAVG[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsPAVG 13
#endif	/* defined(I_stsGpsPAVG) */


#if defined(I_stsGpsSIGQ)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsSIGQ, "stsGpsSIGQ")
const SR_UINT32 IDstsGpsSIGQ[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 8 };
#else
extern const SR_UINT32 IDstsGpsSIGQ[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsSIGQ 13
#endif	/* defined(I_stsGpsSIGQ) */


#if defined(I_stsGpsSPOS)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsSPOS, "stsGpsSPOS")
const SR_UINT32 IDstsGpsSPOS[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 9 };
#else
extern const SR_UINT32 IDstsGpsSPOS[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsSPOS 13
#endif	/* defined(I_stsGpsSPOS) */


#if defined(I_stsGpsTRMO)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsTRMO, "stsGpsTRMO")
const SR_UINT32 IDstsGpsTRMO[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 10 };
#else
extern const SR_UINT32 IDstsGpsTRMO[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsTRMO 13
#endif	/* defined(I_stsGpsTRMO) */


#if defined(I_stsGpsUTCT)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsUTCT, "stsGpsUTCT")
const SR_UINT32 IDstsGpsUTCT[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 11 };
#else
extern const SR_UINT32 IDstsGpsUTCT[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsUTCT 13
#endif	/* defined(I_stsGpsUTCT) */


#if defined(I_stsGpsVERS)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsVERS, "stsGpsVERS")
const SR_UINT32 IDstsGpsVERS[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 12 };
#else
extern const SR_UINT32 IDstsGpsVERS[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsVERS 13
#endif	/* defined(I_stsGpsVERS) */


#if defined(I_stsGpsDETF)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsDETF, "stsGpsDETF")
const SR_UINT32 IDstsGpsDETF[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 13 };
#else
extern const SR_UINT32 IDstsGpsDETF[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsDETF 13
#endif	/* defined(I_stsGpsDETF) */


#if defined(I_stsGpsEFER)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsEFER, "stsGpsEFER")
const SR_UINT32 IDstsGpsEFER[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 14 };
#else
extern const SR_UINT32 IDstsGpsEFER[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsEFER 13
#endif	/* defined(I_stsGpsEFER) */


#if defined(I_stsGpsESSD)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsESSD, "stsGpsESSD")
const SR_UINT32 IDstsGpsESSD[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 15 };
#else
extern const SR_UINT32 IDstsGpsESSD[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsESSD 13
#endif	/* defined(I_stsGpsESSD) */


#if defined(I_stsGpsESSN)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsESSN, "stsGpsESSN")
const SR_UINT32 IDstsGpsESSN[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 16 };
#else
extern const SR_UINT32 IDstsGpsESSN[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsESSN 13
#endif	/* defined(I_stsGpsESSN) */


#if defined(I_stsGpsFAGE)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsFAGE, "stsGpsFAGE")
const SR_UINT32 IDstsGpsFAGE[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 17 };
#else
extern const SR_UINT32 IDstsGpsFAGE[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsFAGE 13
#endif	/* defined(I_stsGpsFAGE) */


#if defined(I_stsGpsTIMD)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsTIMD, "stsGpsTIMD")
const SR_UINT32 IDstsGpsTIMD[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 18 };
#else
extern const SR_UINT32 IDstsGpsTIMD[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsTIMD 13
#endif	/* defined(I_stsGpsTIMD) */


#if defined(I_stsGpsReset)
#ifdef SNMPPART_DECL
STdeclare(STstsGpsReset, "stsGpsReset")
const SR_UINT32 IDstsGpsReset[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 10, 1, 1, 19 };
#else
extern const SR_UINT32 IDstsGpsReset[];
#endif	/* SNMPPART_DECL */
#define LNstsGpsReset 13
#endif	/* defined(I_stsGpsReset) */


#if defined(N_stsLink)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsLink[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11 };
#else
extern const SR_UINT32 IDstsLink[];
#endif	/* SNMPPART_DECL */
#define LNstsLink 10
#endif	/* defined(N_stsLink) */




#if defined(I_stsLinkIndex)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkIndex, "stsLinkIndex")
const SR_UINT32 IDstsLinkIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsLinkIndex[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkIndex 13
#endif	/* defined(I_stsLinkIndex) */


#if defined(I_stsLinkType)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkType, "stsLinkType")
const SR_UINT32 IDstsLinkType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsLinkType[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkType 13
#endif	/* defined(I_stsLinkType) */


#if defined(I_stsLinkEnable)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkEnable, "stsLinkEnable")
const SR_UINT32 IDstsLinkEnable[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsLinkEnable[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkEnable 13
#endif	/* defined(I_stsLinkEnable) */


#if defined(I_stsLinkLineCode)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkLineCode, "stsLinkLineCode")
const SR_UINT32 IDstsLinkLineCode[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsLinkLineCode[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkLineCode 13
#endif	/* defined(I_stsLinkLineCode) */


#if defined(I_stsLinkFMT)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkFMT, "stsLinkFMT")
const SR_UINT32 IDstsLinkFMT[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsLinkFMT[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkFMT 13
#endif	/* defined(I_stsLinkFMT) */


#if defined(I_stsLinkTermination)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkTermination, "stsLinkTermination")
const SR_UINT32 IDstsLinkTermination[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 6 };
#else
extern const SR_UINT32 IDstsLinkTermination[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkTermination 13
#endif	/* defined(I_stsLinkTermination) */


#if defined(I_stsLinkMFCHK)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkMFCHK, "stsLinkMFCHK")
const SR_UINT32 IDstsLinkMFCHK[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 7 };
#else
extern const SR_UINT32 IDstsLinkMFCHK[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkMFCHK 13
#endif	/* defined(I_stsLinkMFCHK) */


#if defined(I_stsLinkId)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkId, "stsLinkId")
const SR_UINT32 IDstsLinkId[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 11, 1, 1, 8 };
#else
extern const SR_UINT32 IDstsLinkId[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkId 13
#endif	/* defined(I_stsLinkId) */


#if defined(N_stsShelf)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 12 };
#else
extern const SR_UINT32 IDstsShelf[];
#endif	/* SNMPPART_DECL */
#define LNstsShelf 10
#endif	/* defined(N_stsShelf) */




#if defined(I_stsShelfIndex)
#ifdef SNMPPART_DECL
STdeclare(STstsShelfIndex, "stsShelfIndex")
const SR_UINT32 IDstsShelfIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 12, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsShelfIndex[];
#endif	/* SNMPPART_DECL */
#define LNstsShelfIndex 13
#endif	/* defined(I_stsShelfIndex) */


#if defined(I_stsShelfSerial)
#ifdef SNMPPART_DECL
STdeclare(STstsShelfSerial, "stsShelfSerial")
const SR_UINT32 IDstsShelfSerial[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 12, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsShelfSerial[];
#endif	/* SNMPPART_DECL */
#define LNstsShelfSerial 13
#endif	/* defined(I_stsShelfSerial) */


#if defined(I_stsShelfCLEICode)
#ifdef SNMPPART_DECL
STdeclare(STstsShelfCLEICode, "stsShelfCLEICode")
const SR_UINT32 IDstsShelfCLEICode[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 12, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsShelfCLEICode[];
#endif	/* SNMPPART_DECL */
#define LNstsShelfCLEICode 13
#endif	/* defined(I_stsShelfCLEICode) */


#if defined(I_stsShelfReset)
#ifdef SNMPPART_DECL
STdeclare(STstsShelfReset, "stsShelfReset")
const SR_UINT32 IDstsShelfReset[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 12, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsShelfReset[];
#endif	/* SNMPPART_DECL */
#define LNstsShelfReset 13
#endif	/* defined(I_stsShelfReset) */


#if defined(N_stsAlarmThreshold)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsAlarmThreshold[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 13 };
#else
extern const SR_UINT32 IDstsAlarmThreshold[];
#endif	/* SNMPPART_DECL */
#define LNstsAlarmThreshold 10
#endif	/* defined(N_stsAlarmThreshold) */




#if defined(I_stsAlarmThresholdCurrentMon)
#ifdef SNMPPART_DECL
STdeclare(STstsAlarmThresholdCurrentMon, "stsAlarmThresholdCurrentMon")
const SR_UINT32 IDstsAlarmThresholdCurrentMon[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 13, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsAlarmThresholdCurrentMon[];
#endif	/* SNMPPART_DECL */
#define LNstsAlarmThresholdCurrentMon 13
#endif	/* defined(I_stsAlarmThresholdCurrentMon) */


#if defined(I_stsAlarmThresholdType)
#ifdef SNMPPART_DECL
STdeclare(STstsAlarmThresholdType, "stsAlarmThresholdType")
const SR_UINT32 IDstsAlarmThresholdType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 13, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsAlarmThresholdType[];
#endif	/* SNMPPART_DECL */
#define LNstsAlarmThresholdType 13
#endif	/* defined(I_stsAlarmThresholdType) */


#if defined(I_stsAlarmThresholdValue)
#ifdef SNMPPART_DECL
STdeclare(STstsAlarmThresholdValue, "stsAlarmThresholdValue")
const SR_UINT32 IDstsAlarmThresholdValue[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 13, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsAlarmThresholdValue[];
#endif	/* SNMPPART_DECL */
#define LNstsAlarmThresholdValue 13
#endif	/* defined(I_stsAlarmThresholdValue) */


#if defined(I_stsAlarmThresholdTimeInterval)
#ifdef SNMPPART_DECL
STdeclare(STstsAlarmThresholdTimeInterval, "stsAlarmThresholdTimeInterval")
const SR_UINT32 IDstsAlarmThresholdTimeInterval[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 13, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsAlarmThresholdTimeInterval[];
#endif	/* SNMPPART_DECL */
#define LNstsAlarmThresholdTimeInterval 13
#endif	/* defined(I_stsAlarmThresholdTimeInterval) */


#if defined(N_stsLinkAlarmSetting)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsLinkAlarmSetting[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 14 };
#else
extern const SR_UINT32 IDstsLinkAlarmSetting[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkAlarmSetting 10
#endif	/* defined(N_stsLinkAlarmSetting) */




#if defined(I_stsLinkAlarmSettingLinkType)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkAlarmSettingLinkType, "stsLinkAlarmSettingLinkType")
const SR_UINT32 IDstsLinkAlarmSettingLinkType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 14, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsLinkAlarmSettingLinkType[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkAlarmSettingLinkType 13
#endif	/* defined(I_stsLinkAlarmSettingLinkType) */


#if defined(I_stsLinkAlarmSettingType)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkAlarmSettingType, "stsLinkAlarmSettingType")
const SR_UINT32 IDstsLinkAlarmSettingType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 14, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsLinkAlarmSettingType[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkAlarmSettingType 13
#endif	/* defined(I_stsLinkAlarmSettingType) */


#if defined(I_stsLinkAlarmSettingSevirity)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkAlarmSettingSevirity, "stsLinkAlarmSettingSevirity")
const SR_UINT32 IDstsLinkAlarmSettingSevirity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 14, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsLinkAlarmSettingSevirity[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkAlarmSettingSevirity 13
#endif	/* defined(I_stsLinkAlarmSettingSevirity) */


#if defined(I_stsLinkAlarmSevirity)
#ifdef SNMPPART_DECL
STdeclare(STstsLinkAlarmSevirity, "stsLinkAlarmSevirity")
const SR_UINT32 IDstsLinkAlarmSevirity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 14, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsLinkAlarmSevirity[];
#endif	/* SNMPPART_DECL */
#define LNstsLinkAlarmSevirity 13
#endif	/* defined(I_stsLinkAlarmSevirity) */


#if defined(N_stsOscillatorAlarmSetting)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsOscillatorAlarmSetting[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 15 };
#else
extern const SR_UINT32 IDstsOscillatorAlarmSetting[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorAlarmSetting 10
#endif	/* defined(N_stsOscillatorAlarmSetting) */




#if defined(I_stsOscillatorAlarmSettingClock)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorAlarmSettingClock, "stsOscillatorAlarmSettingClock")
const SR_UINT32 IDstsOscillatorAlarmSettingClock[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 15, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsOscillatorAlarmSettingClock[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorAlarmSettingClock 13
#endif	/* defined(I_stsOscillatorAlarmSettingClock) */


#if defined(I_stsOscillatorAlarmSettingType)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorAlarmSettingType, "stsOscillatorAlarmSettingType")
const SR_UINT32 IDstsOscillatorAlarmSettingType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 15, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsOscillatorAlarmSettingType[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorAlarmSettingType 13
#endif	/* defined(I_stsOscillatorAlarmSettingType) */


#if defined(I_stsOscillatorAlarmSettingSeverity)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorAlarmSettingSeverity, "stsOscillatorAlarmSettingSeverity")
const SR_UINT32 IDstsOscillatorAlarmSettingSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 15, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsOscillatorAlarmSettingSeverity[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorAlarmSettingSeverity 13
#endif	/* defined(I_stsOscillatorAlarmSettingSeverity) */


#if defined(I_stsOscillatorAlarmSeverity)
#ifdef SNMPPART_DECL
STdeclare(STstsOscillatorAlarmSeverity, "stsOscillatorAlarmSeverity")
const SR_UINT32 IDstsOscillatorAlarmSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 15, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsOscillatorAlarmSeverity[];
#endif	/* SNMPPART_DECL */
#define LNstsOscillatorAlarmSeverity 13
#endif	/* defined(I_stsOscillatorAlarmSeverity) */


#if defined(N_stsOsPwrAlarmSetting)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsOsPwrAlarmSetting[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16 };
#else
extern const SR_UINT32 IDstsOsPwrAlarmSetting[];
#endif	/* SNMPPART_DECL */
#define LNstsOsPwrAlarmSetting 10
#endif	/* defined(N_stsOsPwrAlarmSetting) */




#if defined(I_stssPwrAlarmSettingShelf)
#ifdef SNMPPART_DECL
STdeclare(STstssPwrAlarmSettingShelf, "stssPwrAlarmSettingShelf")
const SR_UINT32 IDstssPwrAlarmSettingShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16, 1, 1, 1 };
#else
extern const SR_UINT32 IDstssPwrAlarmSettingShelf[];
#endif	/* SNMPPART_DECL */
#define LNstssPwrAlarmSettingShelf 13
#endif	/* defined(I_stssPwrAlarmSettingShelf) */


#if defined(I_stsOsPwrAlarmSettingOsPwr)
#ifdef SNMPPART_DECL
STdeclare(STstsOsPwrAlarmSettingOsPwr, "stsOsPwrAlarmSettingOsPwr")
const SR_UINT32 IDstsOsPwrAlarmSettingOsPwr[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsOsPwrAlarmSettingOsPwr[];
#endif	/* SNMPPART_DECL */
#define LNstsOsPwrAlarmSettingOsPwr 13
#endif	/* defined(I_stsOsPwrAlarmSettingOsPwr) */


#if defined(I_stsOsPwrAlarmSettingSeverity)
#ifdef SNMPPART_DECL
STdeclare(STstsOsPwrAlarmSettingSeverity, "stsOsPwrAlarmSettingSeverity")
const SR_UINT32 IDstsOsPwrAlarmSettingSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsOsPwrAlarmSettingSeverity[];
#endif	/* SNMPPART_DECL */
#define LNstsOsPwrAlarmSettingSeverity 13
#endif	/* defined(I_stsOsPwrAlarmSettingSeverity) */


#if defined(I_stsOsPwrAlarmSeverity)
#ifdef SNMPPART_DECL
STdeclare(STstsOsPwrAlarmSeverity, "stsOsPwrAlarmSeverity")
const SR_UINT32 IDstsOsPwrAlarmSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 16, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsOsPwrAlarmSeverity[];
#endif	/* SNMPPART_DECL */
#define LNstsOsPwrAlarmSeverity 13
#endif	/* defined(I_stsOsPwrAlarmSeverity) */


#if defined(N_stsOutputAlarmSetting)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsOutputAlarmSetting[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17 };
#else
extern const SR_UINT32 IDstsOutputAlarmSetting[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputAlarmSetting 10
#endif	/* defined(N_stsOutputAlarmSetting) */




#if defined(I_stsOutputAlarmSettingShelf)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputAlarmSettingShelf, "stsOutputAlarmSettingShelf")
const SR_UINT32 IDstsOutputAlarmSettingShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsOutputAlarmSettingShelf[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputAlarmSettingShelf 13
#endif	/* defined(I_stsOutputAlarmSettingShelf) */


#if defined(I_stsOutputAlarmSettingSlot)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputAlarmSettingSlot, "stsOutputAlarmSettingSlot")
const SR_UINT32 IDstsOutputAlarmSettingSlot[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsOutputAlarmSettingSlot[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputAlarmSettingSlot 13
#endif	/* defined(I_stsOutputAlarmSettingSlot) */


#if defined(I_stsOutputAlarmSettingPort)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputAlarmSettingPort, "stsOutputAlarmSettingPort")
const SR_UINT32 IDstsOutputAlarmSettingPort[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsOutputAlarmSettingPort[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputAlarmSettingPort 13
#endif	/* defined(I_stsOutputAlarmSettingPort) */


#if defined(I_stsOutputAlarmSettingType)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputAlarmSettingType, "stsOutputAlarmSettingType")
const SR_UINT32 IDstsOutputAlarmSettingType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsOutputAlarmSettingType[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputAlarmSettingType 13
#endif	/* defined(I_stsOutputAlarmSettingType) */


#if defined(I_stsOutputAlarmSettingSeverity)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputAlarmSettingSeverity, "stsOutputAlarmSettingSeverity")
const SR_UINT32 IDstsOutputAlarmSettingSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsOutputAlarmSettingSeverity[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputAlarmSettingSeverity 13
#endif	/* defined(I_stsOutputAlarmSettingSeverity) */


#if defined(I_stsOutputAlarmSeverity)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputAlarmSeverity, "stsOutputAlarmSeverity")
const SR_UINT32 IDstsOutputAlarmSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 17, 1, 1, 6 };
#else
extern const SR_UINT32 IDstsOutputAlarmSeverity[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputAlarmSeverity 13
#endif	/* defined(I_stsOutputAlarmSeverity) */


#if defined(N_stsOutputPortSetting)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsOutputPortSetting[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18 };
#else
extern const SR_UINT32 IDstsOutputPortSetting[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputPortSetting 10
#endif	/* defined(N_stsOutputPortSetting) */




#if defined(I_stsOutputPortSettingShelf)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputPortSettingShelf, "stsOutputPortSettingShelf")
const SR_UINT32 IDstsOutputPortSettingShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsOutputPortSettingShelf[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputPortSettingShelf 13
#endif	/* defined(I_stsOutputPortSettingShelf) */


#if defined(I_stsOutputPortSettingSlot)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputPortSettingSlot, "stsOutputPortSettingSlot")
const SR_UINT32 IDstsOutputPortSettingSlot[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsOutputPortSettingSlot[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputPortSettingSlot 13
#endif	/* defined(I_stsOutputPortSettingSlot) */


#if defined(I_stsOutputPortSettingPort)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputPortSettingPort, "stsOutputPortSettingPort")
const SR_UINT32 IDstsOutputPortSettingPort[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsOutputPortSettingPort[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputPortSettingPort 13
#endif	/* defined(I_stsOutputPortSettingPort) */


#if defined(I_stsOutputPortSettingType)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputPortSettingType, "stsOutputPortSettingType")
const SR_UINT32 IDstsOutputPortSettingType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsOutputPortSettingType[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputPortSettingType 13
#endif	/* defined(I_stsOutputPortSettingType) */


#if defined(I_stsOutputPortSettingName)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputPortSettingName, "stsOutputPortSettingName")
const SR_UINT32 IDstsOutputPortSettingName[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 18, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsOutputPortSettingName[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputPortSettingName 13
#endif	/* defined(I_stsOutputPortSettingName) */


#if defined(N_stsOutputTiuSetting)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsOutputTiuSetting[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19 };
#else
extern const SR_UINT32 IDstsOutputTiuSetting[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputTiuSetting 10
#endif	/* defined(N_stsOutputTiuSetting) */




#if defined(I_stsOutputTiuSettingShelf)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputTiuSettingShelf, "stsOutputTiuSettingShelf")
const SR_UINT32 IDstsOutputTiuSettingShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsOutputTiuSettingShelf[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputTiuSettingShelf 13
#endif	/* defined(I_stsOutputTiuSettingShelf) */


#if defined(I_stsOutputTiuSettingSlot)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputTiuSettingSlot, "stsOutputTiuSettingSlot")
const SR_UINT32 IDstsOutputTiuSettingSlot[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsOutputTiuSettingSlot[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputTiuSettingSlot 13
#endif	/* defined(I_stsOutputTiuSettingSlot) */


#if defined(I_stsOutputTiuSettingPort)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputTiuSettingPort, "stsOutputTiuSettingPort")
const SR_UINT32 IDstsOutputTiuSettingPort[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsOutputTiuSettingPort[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputTiuSettingPort 13
#endif	/* defined(I_stsOutputTiuSettingPort) */


#if defined(I_stsOutputTiuSettingLineCoding)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputTiuSettingLineCoding, "stsOutputTiuSettingLineCoding")
const SR_UINT32 IDstsOutputTiuSettingLineCoding[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsOutputTiuSettingLineCoding[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputTiuSettingLineCoding 13
#endif	/* defined(I_stsOutputTiuSettingLineCoding) */


#if defined(I_stsOutputTiuSettingFMT)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputTiuSettingFMT, "stsOutputTiuSettingFMT")
const SR_UINT32 IDstsOutputTiuSettingFMT[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsOutputTiuSettingFMT[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputTiuSettingFMT 13
#endif	/* defined(I_stsOutputTiuSettingFMT) */


#if defined(I_stsOutputTiuSettingTermination)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputTiuSettingTermination, "stsOutputTiuSettingTermination")
const SR_UINT32 IDstsOutputTiuSettingTermination[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 19, 1, 1, 6 };
#else
extern const SR_UINT32 IDstsOutputTiuSettingTermination[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputTiuSettingTermination 13
#endif	/* defined(I_stsOutputTiuSettingTermination) */


#if defined(N_stsPerfMon)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsPerfMon[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20 };
#else
extern const SR_UINT32 IDstsPerfMon[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMon 10
#endif	/* defined(N_stsPerfMon) */




#if defined(I_stsPerfMonInputCurrentMon)
#ifdef SNMPPART_DECL
STdeclare(STstsPerfMonInputCurrentMon, "stsPerfMonInputCurrentMon")
const SR_UINT32 IDstsPerfMonInputCurrentMon[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsPerfMonInputCurrentMon[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonInputCurrentMon 13
#endif	/* defined(I_stsPerfMonInputCurrentMon) */


#if defined(I_stsPerfMonInputMonPeriod)
#ifdef SNMPPART_DECL
STdeclare(STstsPerfMonInputMonPeriod, "stsPerfMonInputMonPeriod")
const SR_UINT32 IDstsPerfMonInputMonPeriod[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsPerfMonInputMonPeriod[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonInputMonPeriod 13
#endif	/* defined(I_stsPerfMonInputMonPeriod) */


#if defined(I_stsPerfMonInputMonBucket)
#ifdef SNMPPART_DECL
STdeclare(STstsPerfMonInputMonBucket, "stsPerfMonInputMonBucket")
const SR_UINT32 IDstsPerfMonInputMonBucket[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsPerfMonInputMonBucket[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonInputMonBucket 13
#endif	/* defined(I_stsPerfMonInputMonBucket) */


#if defined(I_stsPerfMonInputMonType)
#ifdef SNMPPART_DECL
STdeclare(STstsPerfMonInputMonType, "stsPerfMonInputMonType")
const SR_UINT32 IDstsPerfMonInputMonType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsPerfMonInputMonType[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonInputMonType 13
#endif	/* defined(I_stsPerfMonInputMonType) */


#if defined(I_stsPerfMonInputMonValue)
#ifdef SNMPPART_DECL
STdeclare(STstsPerfMonInputMonValue, "stsPerfMonInputMonValue")
const SR_UINT32 IDstsPerfMonInputMonValue[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsPerfMonInputMonValue[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonInputMonValue 13
#endif	/* defined(I_stsPerfMonInputMonValue) */


#if defined(I_stsPerfMonInputClockType)
#ifdef SNMPPART_DECL
STdeclare(STstsPerfMonInputClockType, "stsPerfMonInputClockType")
const SR_UINT32 IDstsPerfMonInputClockType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 20, 1, 1, 6 };
#else
extern const SR_UINT32 IDstsPerfMonInputClockType[];
#endif	/* SNMPPART_DECL */
#define LNstsPerfMonInputClockType 13
#endif	/* defined(I_stsPerfMonInputClockType) */


#if defined(N_stsTerminal)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsTerminal[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21 };
#else
extern const SR_UINT32 IDstsTerminal[];
#endif	/* SNMPPART_DECL */
#define LNstsTerminal 10
#endif	/* defined(N_stsTerminal) */




#if defined(I_stsTerminalIndex)
#ifdef SNMPPART_DECL
STdeclare(STstsTerminalIndex, "stsTerminalIndex")
const SR_UINT32 IDstsTerminalIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsTerminalIndex[];
#endif	/* SNMPPART_DECL */
#define LNstsTerminalIndex 13
#endif	/* defined(I_stsTerminalIndex) */


#if defined(I_stsTerminalBaudrate)
#ifdef SNMPPART_DECL
STdeclare(STstsTerminalBaudrate, "stsTerminalBaudrate")
const SR_UINT32 IDstsTerminalBaudrate[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsTerminalBaudrate[];
#endif	/* SNMPPART_DECL */
#define LNstsTerminalBaudrate 13
#endif	/* defined(I_stsTerminalBaudrate) */


#if defined(I_stsTerminalDataBits)
#ifdef SNMPPART_DECL
STdeclare(STstsTerminalDataBits, "stsTerminalDataBits")
const SR_UINT32 IDstsTerminalDataBits[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsTerminalDataBits[];
#endif	/* SNMPPART_DECL */
#define LNstsTerminalDataBits 13
#endif	/* defined(I_stsTerminalDataBits) */


#if defined(I_stsTerminalParity)
#ifdef SNMPPART_DECL
STdeclare(STstsTerminalParity, "stsTerminalParity")
const SR_UINT32 IDstsTerminalParity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsTerminalParity[];
#endif	/* SNMPPART_DECL */
#define LNstsTerminalParity 13
#endif	/* defined(I_stsTerminalParity) */


#if defined(I_stsTerminalStopBits)
#ifdef SNMPPART_DECL
STdeclare(STstsTerminalStopBits, "stsTerminalStopBits")
const SR_UINT32 IDstsTerminalStopBits[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 21, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsTerminalStopBits[];
#endif	/* SNMPPART_DECL */
#define LNstsTerminalStopBits 13
#endif	/* defined(I_stsTerminalStopBits) */


#if defined(N_stsAlarmStatus)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsAlarmStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 22 };
#else
extern const SR_UINT32 IDstsAlarmStatus[];
#endif	/* SNMPPART_DECL */
#define LNstsAlarmStatus 10
#endif	/* defined(N_stsAlarmStatus) */




#if defined(I_stsAlarmSource)
#ifdef SNMPPART_DECL
STdeclare(STstsAlarmSource, "stsAlarmSource")
const SR_UINT32 IDstsAlarmSource[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 22, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsAlarmSource[];
#endif	/* SNMPPART_DECL */
#define LNstsAlarmSource 13
#endif	/* defined(I_stsAlarmSource) */


#if defined(I_stsAlarmSourceType)
#ifdef SNMPPART_DECL
STdeclare(STstsAlarmSourceType, "stsAlarmSourceType")
const SR_UINT32 IDstsAlarmSourceType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 22, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsAlarmSourceType[];
#endif	/* SNMPPART_DECL */
#define LNstsAlarmSourceType 13
#endif	/* defined(I_stsAlarmSourceType) */


#if defined(I_stsAlarmSeverity)
#ifdef SNMPPART_DECL
STdeclare(STstsAlarmSeverity, "stsAlarmSeverity")
const SR_UINT32 IDstsAlarmSeverity[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 22, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsAlarmSeverity[];
#endif	/* SNMPPART_DECL */
#define LNstsAlarmSeverity 13
#endif	/* defined(I_stsAlarmSeverity) */


#if defined(I_stsAlarmSrvEff)
#ifdef SNMPPART_DECL
STdeclare(STstsAlarmSrvEff, "stsAlarmSrvEff")
const SR_UINT32 IDstsAlarmSrvEff[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 22, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsAlarmSrvEff[];
#endif	/* SNMPPART_DECL */
#define LNstsAlarmSrvEff 13
#endif	/* defined(I_stsAlarmSrvEff) */


#if defined(N_stsOutputCard)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsOutputCard[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23 };
#else
extern const SR_UINT32 IDstsOutputCard[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputCard 10
#endif	/* defined(N_stsOutputCard) */




#if defined(I_stsOutputShelf)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputShelf, "stsOutputShelf")
const SR_UINT32 IDstsOutputShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsOutputShelf[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputShelf 13
#endif	/* defined(I_stsOutputShelf) */


#if defined(I_stsOutputSlot)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputSlot, "stsOutputSlot")
const SR_UINT32 IDstsOutputSlot[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsOutputSlot[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputSlot 13
#endif	/* defined(I_stsOutputSlot) */


#if defined(I_stsOutputRedState)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputRedState, "stsOutputRedState")
const SR_UINT32 IDstsOutputRedState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsOutputRedState[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputRedState 13
#endif	/* defined(I_stsOutputRedState) */


#if defined(I_stsOutputRedSwitchState)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputRedSwitchState, "stsOutputRedSwitchState")
const SR_UINT32 IDstsOutputRedSwitchState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsOutputRedSwitchState[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputRedSwitchState 13
#endif	/* defined(I_stsOutputRedSwitchState) */


#if defined(I_stsOutputCRCCHK)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputCRCCHK, "stsOutputCRCCHK")
const SR_UINT32 IDstsOutputCRCCHK[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsOutputCRCCHK[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputCRCCHK 13
#endif	/* defined(I_stsOutputCRCCHK) */


#if defined(I_stsOutputCAS)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputCAS, "stsOutputCAS")
const SR_UINT32 IDstsOutputCAS[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 6 };
#else
extern const SR_UINT32 IDstsOutputCAS[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputCAS 13
#endif	/* defined(I_stsOutputCAS) */


#if defined(I_stsOutputSSM)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputSSM, "stsOutputSSM")
const SR_UINT32 IDstsOutputSSM[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 7 };
#else
extern const SR_UINT32 IDstsOutputSSM[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputSSM 13
#endif	/* defined(I_stsOutputSSM) */


#if defined(I_stsOutputSSMValue)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputSSMValue, "stsOutputSSMValue")
const SR_UINT32 IDstsOutputSSMValue[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 8 };
#else
extern const SR_UINT32 IDstsOutputSSMValue[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputSSMValue 13
#endif	/* defined(I_stsOutputSSMValue) */


#if defined(I_stsOutputTimingFormat)
#ifdef SNMPPART_DECL
STdeclare(STstsOutputTimingFormat, "stsOutputTimingFormat")
const SR_UINT32 IDstsOutputTimingFormat[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 23, 1, 1, 9 };
#else
extern const SR_UINT32 IDstsOutputTimingFormat[];
#endif	/* SNMPPART_DECL */
#define LNstsOutputTimingFormat 13
#endif	/* defined(I_stsOutputTimingFormat) */


#if defined(N_stsEmmStatus)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsEmmStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24 };
#else
extern const SR_UINT32 IDstsEmmStatus[];
#endif	/* SNMPPART_DECL */
#define LNstsEmmStatus 10
#endif	/* defined(N_stsEmmStatus) */




#if defined(I_stsEmmShelf)
#ifdef SNMPPART_DECL
STdeclare(STstsEmmShelf, "stsEmmShelf")
const SR_UINT32 IDstsEmmShelf[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsEmmShelf[];
#endif	/* SNMPPART_DECL */
#define LNstsEmmShelf 13
#endif	/* defined(I_stsEmmShelf) */


#if defined(I_stsEmmUnitId)
#ifdef SNMPPART_DECL
STdeclare(STstsEmmUnitId, "stsEmmUnitId")
const SR_UINT32 IDstsEmmUnitId[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsEmmUnitId[];
#endif	/* SNMPPART_DECL */
#define LNstsEmmUnitId 13
#endif	/* defined(I_stsEmmUnitId) */


#if defined(I_stsEmmSensorType)
#ifdef SNMPPART_DECL
STdeclare(STstsEmmSensorType, "stsEmmSensorType")
const SR_UINT32 IDstsEmmSensorType[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsEmmSensorType[];
#endif	/* SNMPPART_DECL */
#define LNstsEmmSensorType 13
#endif	/* defined(I_stsEmmSensorType) */


#if defined(I_stsEmmAlarmStatus)
#ifdef SNMPPART_DECL
STdeclare(STstsEmmAlarmStatus, "stsEmmAlarmStatus")
const SR_UINT32 IDstsEmmAlarmStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsEmmAlarmStatus[];
#endif	/* SNMPPART_DECL */
#define LNstsEmmAlarmStatus 13
#endif	/* defined(I_stsEmmAlarmStatus) */


#if defined(I_stsEmmSensorReading)
#ifdef SNMPPART_DECL
STdeclare(STstsEmmSensorReading, "stsEmmSensorReading")
const SR_UINT32 IDstsEmmSensorReading[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsEmmSensorReading[];
#endif	/* SNMPPART_DECL */
#define LNstsEmmSensorReading 13
#endif	/* defined(I_stsEmmSensorReading) */


#if defined(I_stsEmmMajorAlmHiThresh)
#ifdef SNMPPART_DECL
STdeclare(STstsEmmMajorAlmHiThresh, "stsEmmMajorAlmHiThresh")
const SR_UINT32 IDstsEmmMajorAlmHiThresh[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 6 };
#else
extern const SR_UINT32 IDstsEmmMajorAlmHiThresh[];
#endif	/* SNMPPART_DECL */
#define LNstsEmmMajorAlmHiThresh 13
#endif	/* defined(I_stsEmmMajorAlmHiThresh) */


#if defined(I_stsEmmMajorAlmLoThresh)
#ifdef SNMPPART_DECL
STdeclare(STstsEmmMajorAlmLoThresh, "stsEmmMajorAlmLoThresh")
const SR_UINT32 IDstsEmmMajorAlmLoThresh[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 7 };
#else
extern const SR_UINT32 IDstsEmmMajorAlmLoThresh[];
#endif	/* SNMPPART_DECL */
#define LNstsEmmMajorAlmLoThresh 13
#endif	/* defined(I_stsEmmMajorAlmLoThresh) */


#if defined(I_stsEmmMinorAlmHiThresh)
#ifdef SNMPPART_DECL
STdeclare(STstsEmmMinorAlmHiThresh, "stsEmmMinorAlmHiThresh")
const SR_UINT32 IDstsEmmMinorAlmHiThresh[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 8 };
#else
extern const SR_UINT32 IDstsEmmMinorAlmHiThresh[];
#endif	/* SNMPPART_DECL */
#define LNstsEmmMinorAlmHiThresh 13
#endif	/* defined(I_stsEmmMinorAlmHiThresh) */


#if defined(I_stsEmmMinorAlmLoThresh)
#ifdef SNMPPART_DECL
STdeclare(STstsEmmMinorAlmLoThresh, "stsEmmMinorAlmLoThresh")
const SR_UINT32 IDstsEmmMinorAlmLoThresh[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 24, 1, 1, 9 };
#else
extern const SR_UINT32 IDstsEmmMinorAlmLoThresh[];
#endif	/* SNMPPART_DECL */
#define LNstsEmmMinorAlmLoThresh 13
#endif	/* defined(I_stsEmmMinorAlmLoThresh) */


#if defined(N_stsAnt)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsAnt[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 25 };
#else
extern const SR_UINT32 IDstsAnt[];
#endif	/* SNMPPART_DECL */
#define LNstsAnt 10
#endif	/* defined(N_stsAnt) */




#if defined(I_stsAntIndex)
#ifdef SNMPPART_DECL
STdeclare(STstsAntIndex, "stsAntIndex")
const SR_UINT32 IDstsAntIndex[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 25, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsAntIndex[];
#endif	/* SNMPPART_DECL */
#define LNstsAntIndex 13
#endif	/* defined(I_stsAntIndex) */


#if defined(I_stsAntStatus)
#ifdef SNMPPART_DECL
STdeclare(STstsAntStatus, "stsAntStatus")
const SR_UINT32 IDstsAntStatus[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 25, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsAntStatus[];
#endif	/* SNMPPART_DECL */
#define LNstsAntStatus 13
#endif	/* defined(I_stsAntStatus) */


#if defined(I_stsAntSwitchState)
#ifdef SNMPPART_DECL
STdeclare(STstsAntSwitchState, "stsAntSwitchState")
const SR_UINT32 IDstsAntSwitchState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 25, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsAntSwitchState[];
#endif	/* SNMPPART_DECL */
#define LNstsAntSwitchState 13
#endif	/* defined(I_stsAntSwitchState) */


#if defined(N_stsTopDest)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsTopDest[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 26 };
#else
extern const SR_UINT32 IDstsTopDest[];
#endif	/* SNMPPART_DECL */
#define LNstsTopDest 10
#endif	/* defined(N_stsTopDest) */




#if defined(I_stsTopDestNumber)
#ifdef SNMPPART_DECL
STdeclare(STstsTopDestNumber, "stsTopDestNumber")
const SR_UINT32 IDstsTopDestNumber[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 26, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsTopDestNumber[];
#endif	/* SNMPPART_DECL */
#define LNstsTopDestNumber 13
#endif	/* defined(I_stsTopDestNumber) */


#if defined(I_stsTopDestIp)
#ifdef SNMPPART_DECL
STdeclare(STstsTopDestIp, "stsTopDestIp")
const SR_UINT32 IDstsTopDestIp[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 26, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsTopDestIp[];
#endif	/* SNMPPART_DECL */
#define LNstsTopDestIp 13
#endif	/* defined(I_stsTopDestIp) */


#if defined(I_stsTopDestUdpPort)
#ifdef SNMPPART_DECL
STdeclare(STstsTopDestUdpPort, "stsTopDestUdpPort")
const SR_UINT32 IDstsTopDestUdpPort[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 26, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsTopDestUdpPort[];
#endif	/* SNMPPART_DECL */
#define LNstsTopDestUdpPort 13
#endif	/* defined(I_stsTopDestUdpPort) */


#if defined(I_stsTopDestVlanId)
#ifdef SNMPPART_DECL
STdeclare(STstsTopDestVlanId, "stsTopDestVlanId")
const SR_UINT32 IDstsTopDestVlanId[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 26, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsTopDestVlanId[];
#endif	/* SNMPPART_DECL */
#define LNstsTopDestVlanId 13
#endif	/* defined(I_stsTopDestVlanId) */


#if defined(N_stsTrapReg)
#ifdef SNMPPART_DECL
const SR_UINT32 IDstsTrapReg[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 27 };
#else
extern const SR_UINT32 IDstsTrapReg[];
#endif	/* SNMPPART_DECL */
#define LNstsTrapReg 10
#endif	/* defined(N_stsTrapReg) */




#if defined(I_stsTrapRegMgrNumber)
#ifdef SNMPPART_DECL
STdeclare(STstsTrapRegMgrNumber, "stsTrapRegMgrNumber")
const SR_UINT32 IDstsTrapRegMgrNumber[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 27, 1, 1, 1 };
#else
extern const SR_UINT32 IDstsTrapRegMgrNumber[];
#endif	/* SNMPPART_DECL */
#define LNstsTrapRegMgrNumber 13
#endif	/* defined(I_stsTrapRegMgrNumber) */


#if defined(I_stsTrapRegMgrIp)
#ifdef SNMPPART_DECL
STdeclare(STstsTrapRegMgrIp, "stsTrapRegMgrIp")
const SR_UINT32 IDstsTrapRegMgrIp[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 27, 1, 1, 2 };
#else
extern const SR_UINT32 IDstsTrapRegMgrIp[];
#endif	/* SNMPPART_DECL */
#define LNstsTrapRegMgrIp 13
#endif	/* defined(I_stsTrapRegMgrIp) */


#if defined(I_stsTrapRegMgrUdpPort)
#ifdef SNMPPART_DECL
STdeclare(STstsTrapRegMgrUdpPort, "stsTrapRegMgrUdpPort")
const SR_UINT32 IDstsTrapRegMgrUdpPort[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 27, 1, 1, 3 };
#else
extern const SR_UINT32 IDstsTrapRegMgrUdpPort[];
#endif	/* SNMPPART_DECL */
#define LNstsTrapRegMgrUdpPort 13
#endif	/* defined(I_stsTrapRegMgrUdpPort) */


#if defined(I_stsTrapRegCommunityStr)
#ifdef SNMPPART_DECL
STdeclare(STstsTrapRegCommunityStr, "stsTrapRegCommunityStr")
const SR_UINT32 IDstsTrapRegCommunityStr[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 27, 1, 1, 4 };
#else
extern const SR_UINT32 IDstsTrapRegCommunityStr[];
#endif	/* SNMPPART_DECL */
#define LNstsTrapRegCommunityStr 13
#endif	/* defined(I_stsTrapRegCommunityStr) */


#if defined(I_stsTrapRegState)
#ifdef SNMPPART_DECL
STdeclare(STstsTrapRegState, "stsTrapRegState")
const SR_UINT32 IDstsTrapRegState[] = { 1, 3, 6, 1, 4, 1, 24628, 2, 2, 27, 1, 1, 5 };
#else
extern const SR_UINT32 IDstsTrapRegState[];
#endif	/* SNMPPART_DECL */
#define LNstsTrapRegState 13
#endif	/* defined(I_stsTrapRegState) */


#if defined(N_larusExperiment)
#ifdef SNMPPART_DECL
const SR_UINT32 IDlarusExperiment[] = { 1, 3, 6, 1, 4, 1, 24628, 3 };
#else
extern const SR_UINT32 IDlarusExperiment[];
#endif	/* SNMPPART_DECL */
#define LNlarusExperiment 8
#endif	/* defined(N_larusExperiment) */


#if defined(N_security)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsecurity[] = { 1, 3, 6, 1, 5 };
#else
extern const SR_UINT32 IDsecurity[];
#endif	/* SNMPPART_DECL */
#define LNsecurity 5
#endif	/* defined(N_security) */


#if defined(N_snmpV2)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsnmpV2[] = { 1, 3, 6, 1, 6 };
#else
extern const SR_UINT32 IDsnmpV2[];
#endif	/* SNMPPART_DECL */
#define LNsnmpV2 5
#endif	/* defined(N_snmpV2) */


#if defined(N_snmpDomains)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsnmpDomains[] = { 1, 3, 6, 1, 6, 1 };
#else
extern const SR_UINT32 IDsnmpDomains[];
#endif	/* SNMPPART_DECL */
#define LNsnmpDomains 6
#endif	/* defined(N_snmpDomains) */


#if defined(N_snmpProxys)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsnmpProxys[] = { 1, 3, 6, 1, 6, 2 };
#else
extern const SR_UINT32 IDsnmpProxys[];
#endif	/* SNMPPART_DECL */
#define LNsnmpProxys 6
#endif	/* defined(N_snmpProxys) */


#if defined(N_snmpModules)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsnmpModules[] = { 1, 3, 6, 1, 6, 3 };
#else
extern const SR_UINT32 IDsnmpModules[];
#endif	/* SNMPPART_DECL */
#define LNsnmpModules 6
#endif	/* defined(N_snmpModules) */


#if defined(N_snmpMIB)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsnmpMIB[] = { 1, 3, 6, 1, 6, 3, 1 };
#else
extern const SR_UINT32 IDsnmpMIB[];
#endif	/* SNMPPART_DECL */
#define LNsnmpMIB 7
#endif	/* defined(N_snmpMIB) */


#if defined(N_snmpMIBObjects)
#ifdef SNMPPART_DECL
const SR_UINT32 IDsnmpMIBObjects[] = { 1, 3, 6, 1, 6, 3, 1, 1 };
#else
extern const SR_UINT32 IDsnmpMIBObjects[];
#endif	/* SNMPPART_DECL */
#define LNsnmpMIBObjects 8
#endif	/* defined(N_snmpMIBObjects) */


#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_SNMPPART_H */
